### ISSUE TITLE
Mentors of every culture in Asia

### ISSUE THREAD

**Issue by jayvdb** [fossasia/gci16.fossasia.org#1]
The layout of http://gci15.fossasia.org/ makes it hard to find mentors or students.

It would be great if FOSSASIA GCI 2016 employed a map interface for showing mentors, where the reader can find the mentors/project/tasks being mentored by someone from their own region who speaks their own language.

Then the goal would be to have at least one mentor from each culture, country and/or language in Asia ;-)

Likewise it would be great if the students self-disclosed their country of origin/residence, and language, so they can also be mapped.

**Comment by tradzik** [comment]
I remember we had something like that two years ago. It made our website being really slow. How do you see implementation of such solution? The former one was based on JSON file.

**Comment by jayvdb** [comment]
If it is on a separate page, only that page will be slower.
Ya, http://gci14.fossasia.org/#mentors is roughly what I had in mind.

**Comment by BrainBuzzer** [comment]
I am working on this issue. Just a question though. So far a lot of students have added there info and they will be supposed to add their latitude and longitude. Some of them may add and some of them may not.

**Comment by jayvdb** [comment]
Create a separate issue to add a linter to require or warn on long/lat ?

i.e. for this task, just add the mentors (and students) who have a long/lat.  That is this bug.  Other problems should be a separate task.

**Comment by BrainBuzzer** [comment]
I'll be doing this only for mentors instead of adding students. In next GCI, it would be good to implement this feature completely. But I'll still need mentors to update their info in order to accomplish this.

**Comment by jayvdb** [comment]
OK. Mentors is easier.  After you've build the UI, create a new issue with a list of mentors without long/lat , and ask them to fill in their data. ;-)

**Comment by abishekvashok** [comment]
Any progress guys

**Comment by BrainBuzzer** [comment]
Yes. Just struggling with popups. Will be there soon.

**Comment by abishekvashok** [comment]
Want some help I will help out

**Comment by abishekvashok** [comment]
If u give me the report URL I will remote clone and help out with the pop-up so you could PR

**Comment by abishekvashok** [comment]
Not report but repo

**Comment by BrainBuzzer** [comment]
Thanks. I have almost completed this. Just do what improvements you want once I have completed it. It's almost perfect though.

**Comment by BrainBuzzer** [comment]
Just added these locations for reference.

![Image](http://i.imgur.com/l9vP00A.png)

**Comment by abishekvashok** [comment]
Nice can you make the images a bit more to the center. @BrainBuzzer awesome work though

**Comment by BrainBuzzer** [comment]
https://google-code-in-brainbuzzer.c9users.io/GCI/index.html <- Maybe, if the server will keep running, you can see example here.(sorry for those random points.)

**Comment by m1guelpf** [comment]
Any updates on this?

**Comment by BrainBuzzer** [comment]
Check travis. There is no error but still it shows failing. PR #265

**Comment by abishekvashok** [comment]
@BrainBuzzer the travis is now ok and the map has been added closing this :) nice work.
