### ISSUE TITLE
Require travis fix

### ISSUE THREAD

**Issue by daminisatya** [fossasia/gci16.fossasia.org#106]
Need to fix the failing build. For some reason this is creating a lot of confusion

**Comment by abishekvashok** [comment]
For each build fail, see the Travis page and see why it's failing, there can be anything from line length issue to syntax errors

**Comment by daminisatya** [comment]
@Abhi2424shek Yes true.I'm trying to make GCI must cleaner and faster. Just to make sure you all enjoy the development instead of leaving the task in between due to repeated conflicts and build fails.

**Comment by abishekvashok** [comment]
@daminisatya you could narrow down the tests travis runs, and the tests are taking a long time to finish!

**Comment by abishekvashok** [comment]
@daminisatya another option would be to update the readme.md file to something which describes all the conditions that must be met to not let the tests fail.

**Comment by hemantjadon** [comment]
@daminisatya @jig08 
I was just fiddling with `coala` right now and I think we can remove the `linting errors` which are causing the `builds to fail`. 

* The solution which I can think of is setting up `pre commit git hooks`.

* These hooks can be simple bash script which run all the `CoalaConsistencyBears`, whatever we like and coala will apply patches automatically.

* These will remove all the manual headache and will stop almost the build failures. (as currently all are due to inconsistencies).

* A win-win for students and mentors

Few links which might suggest : 

* [Auto apply patches](https://coala.readthedocs.io/en/latest/Users/Tutorial.html#auto-applying-results)

* [Git hooks with Coala](https://coala.readthedocs.io/en/latest/Users/coala_as_Git_Hook.html#pre-commit-hooks)

One issue I am able to think of is the delievery of these updated `.git/hooks/pre-commit` script to all the forks.

@jayvdb Your views on this solution please.

**Comment by daminisatya** [comment]
@hemantjadon Yes a git hook would solve it! (Y)

**Comment by jayvdb** [comment]
As I noted last night in the mentors channel, I think a git hook will be painful for newbies.
They would need to install coala for that to work, and coala has lots of dependencies.  See https://github.com/coala/coala-bears/issues/1000 for work which would make this approach more feasible.

I have added a different merge driver in #149, which should help... we'll need to watch it closely.

https://gitmate.io is another tool we can use , as it tells participants the problems on GitHub, which means they dont need to find the Travis build log and understand how to fix the problems.  gitmate will provide recommended fixes for most problems, showing them the patch to apply to resolve the issue.

Adding squash as a merge option is a really good idea for the beginner task, but it should be optional and not used for the more advanced tasks.

**Comment by hemantjadon** [comment]
@daminisatya @jig08 @jayvdb 
Let's see how this merge pans out. In the mean time I will integrate `gitmate` here so that it helps the newcomers.

**Comment by abishekvashok** [comment]
@hemantjude what's the progress, I seen some demos and it's working good.

**Comment by hemantjadon** [comment]
@Abhi2424shek we (mentors) are trying to find the best solution for the effective and smooth workflow for both students and mentors.

And you students are welcome to put up the solutions :)

**Comment by abishekvashok** [comment]
Sure :) happy coding keep up the good work

**Comment by m1guelpf** [comment]
Working on this at #226 and (partly) at #235

**Comment by jayvdb** [comment]
What happened with using gitmate ?  That advises people what changes are needed.

**Comment by hemantjadon** [comment]
@jayvdb I started gitmate using my account but it was displaying the analysis with my account(Personal) and was creating some confusion among students

**Comment by jayvdb** [comment]
Can we create and use a bot account?

**Comment by m1guelpf** [comment]
@jayvdb I am using @checkbot for reports, but can change it if someone provides an api token with the repo scope.

**Comment by hemantjadon** [comment]
@jayvdb Yes we can definitely make a bot account. Actually I asked this on slack also but there was no solid reply, I think we should make a bot account as in the brief period of time the `gitmate` was active (3 PR's if I remember correctly) it was useful and helped students to correct themselves.

I think we should go with `gitmate` with `bot account`.

Your views please @m1guelpf @jig08 @daminisatya .

**Comment by abishekvashok** [comment]
@hemantjadon do I create a bot account named something like `gitmate bot`?

**Comment by m1guelpf** [comment]
@hemantjadon @Abhi2424shek So we're using Gitmate and Danger, only Gitmate or only Danger?

**Comment by abishekvashok** [comment]
Danger only, I saw it just now sorry, we can close this... I guess
