### ISSUE TITLE
Suggestion: Make the UI more consistent

### ISSUE THREAD

**Issue by dannymout** [fossasia/gci16.fossasia.org#117]
I noticed a bit of inconsistency in the UI of the website. The students and blog post sections were very different in design compared to the mentors and contributors section. First of all, the students section, doesn't have the separate box that sticks out to show the title. Secondly, the contributor and mentor sections have a material design card look, while the students section doesn't. The cards on the student section have the names on top of the pictures causing the text to be less visible to the user. The padding is also a lot different on the students section, there is nearly no padding on the very left, very right and on the very bottom. The animations for the social media links is significantly different from the one used in the mentors section and the box around the social media links is offset whenever the name of a student exceeds more than a line. The text that says student is not all uppercase and also has a shadow unlike the top two sections. For the students section, I highly suggest reusing the mentors section with the student profile pictures, names and social media links. The blog post section has different padding from the other sections and also doesn't retain the material design card style. The font, once again, is not all uppercase and the divs that have the blog posts in them don't seem to be scaling properly with blog post titles that have lots of characters. 

- [x] Students section consistent with the design of the other sections
- [x] Latest Issue section title needs to be part of the actual box.
 
- [x] MBDyn logo section consistent with the design of the other sections
- [ ] Blog Post section consistent with the design of the other sections

These are all the things that I noticed on the version that is up on the [Fossasia website](http://gci16.fossasia.org).

**Comment by abishekvashok** [comment]
@dannymout I will work on this after my pull #103 is merged :) or, it will leave a lot of conflicts for a lot of people...

**Comment by jigyasa-grover** [comment]
@dannymout Agreed.

**Comment by hemantjadon** [comment]
@dannymout Are you a gci student? 
If yes would you like to work on this?

**Comment by myfrom** [comment]
Is anyone working on this or can I have this one? I'm GCI student

**Comment by gaeun** [comment]
Can I work on this? I could work on making the UI more consistent across different sections.

**Comment by hemantjadon** [comment]
@Witus13 @gaeun 
One of you can have this right now, Then do the enhancement on some part of the site.
Then submit the PR, which after merge, this issue can be taken by the other one.
This one is a quite broad issue so no need to panic all of you will get chance to do it.

Please decide amongst yourself who's gonna go first and fix which part of the site.

Cheers :)
Keep Coding:)

**Comment by gaeun** [comment]
@Witus13 I'm working on modifying the student section design and padding to match the other sections. Do you want to work on implementing material design cards and scaling for the blog posts section?

**Comment by myfrom** [comment]
@gaeun OK, I'll also take the "MBDyn logo designs" section.

**Comment by myfrom** [comment]
I have the blog section done but I heard that someone is working on MDByn logos (#196) so I'll leave it to do't cause conflicts. I'll submit a PR as soon as I'll be able to claim a task. Demo will be live [here](https://witus13.github.io/gci16.fossasia.org/).

**Comment by hemantjadon** [comment]
Hi this issue is certainly a very broad issue, and many of you have opened and submitted PR's for the specific part of the website. So should we close this?
What are your views students?

**Comment by myfrom** [comment]
I think so. But I haven't submitted my PR yet as there were some problems with uploading to GitHub yesterday

**Comment by niccokunzmann** [comment]
@dannymout Can you use bullet points that we can check, so we know what has been done already?
Like this:

- [ ] todo
- [x] done
```
- [ ] todo
- [X] done
```

**Comment by dannymout** [comment]
I've noticed that the blog post section still isn't consistent with the mentors, contributors and student's section if someone wants to work on it.

**Comment by myfrom** [comment]
@dannymount It's because I broke my PR 😜 I'll submit a new one tomorrow

**Comment by wingsylver** [comment]
Is anyone working on the MBDyn logo section? If not, then I'll do it. I'm a GCI student, by the way.

**Comment by jigyasa-grover** [comment]
@william1835 Please take Issue https://github.com/fossasia/gci16.fossasia.org/issues/256 up :)

**Comment by wingsylver** [comment]
@jig08 Cheers

**Comment by abishekvashok** [comment]
Now the logo section is ok @dannymount

**Comment by myfrom** [comment]
@dannymout Blogs done

**Comment by niccokunzmann** [comment]
The last point was addressed in #433. Can we close this?

**Comment by abishekvashok** [comment]
We can close this @niccokunzmann
