### ISSUE TITLE
Student section is currently static, make it dynammic

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/gci16.fossasia.org#119]
The student section of the website is currently static and nothing in the students.yml shows up. Let's make it dynamic, so students need just to insert there info to the students.yml file.

**Comment by abishekvashok** [comment]
I working on it guys, please see my PR #103 can I assign it to myself

**Comment by Princu7** [comment]
@Abhi2424shek Thanks for reporting the issue. It seems that @webhaikal is already working on this issue via the pull request #109 .

**Comment by abishekvashok** [comment]
I made it earlier @Princu7 , SEE THE PREVIEWS: [https://abhi2424shek.github.io/gci16.fossasia.org](https://abhi2424shek.github.io/gci16.fossasia.org)

**Comment by abishekvashok** [comment]
Awaiting @daminisatya

**Comment by abishekvashok** [comment]
@hemantjadon more and more students are added themselves statically, we should do something...

**Comment by abishekvashok** [comment]
Awaiting @jig08
