### ISSUE TITLE
Very slow page speed

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/gci16.fossasia.org#129]
The website [https://gci16.fossasia.org](https://gci16.fossasia.org) is very slow, see the Google page insights their rating on speed is zero. We need to work on this guys a lot.

Page insights for mobile:
![image](https://cloud.githubusercontent.com/assets/8947010/20860343/d5cc251e-b99b-11e6-8429-a0f0ff549689.png)

Page insights for Desktop:
![image](https://cloud.githubusercontent.com/assets/8947010/20860348/e3399b14-b99b-11e6-8628-bb7b3ce4dfeb.png)

I would be more than happy to work on this, however anyone else can also work on this too.

**Comment by abishekvashok** [comment]
I would optimize images, update the readme.md to inform the students to upload only optimized images and optimize css delivery. I will post a PR soon.

**Comment by hemantjadon** [comment]
Go ahead 👍

**Comment by abishekvashok** [comment]
I done a PR, possibly optimizing all that I could #133 please take a look and merge @hemantjadon

**Comment by hemantjadon** [comment]
Well I think this is done for now. Maybe we will reopen this again once we face unacceptable speed delays again.

**Comment by abishekvashok** [comment]
@hemantjadon yes your correct :)

**Comment by abishekvashok** [comment]
Speed is down again:
![image](https://cloud.githubusercontent.com/assets/8947010/21467836/f11a30d2-ca20-11e6-9bd2-e0f31a11e5e6.png)
![image](https://cloud.githubusercontent.com/assets/8947010/21467837/f4d842e0-ca20-11e6-8d35-339fc72db3f0.png)

**Comment by ankitrgadiya** [comment]
This issue is reported as separate issues #632  and #712 So please close this.
