### ISSUE TITLE
Problem with Student Section

### ISSUE THREAD

**Issue by codein-dwij** [fossasia/gci16.fossasia.org#130]
There is a minor problem with student section.
http://prntscr.com/dettek
If the name of the student comes in two lines you can see that the icons go out of the white box.Hope someone can fix it

**Comment by abishekvashok** [comment]
@codein-dwij can I work on this.

**Comment by codein-dwij** [comment]
Yep you can. I am just a student and I found this thing

**Comment by abishekvashok** [comment]
@codein-dwij I am too a student, you can also work on bro!

**Comment by codein-dwij** [comment]
I am not currently familiar with jekyll so go on... I am just finding issues and doing some other tasks :)

**Comment by abishekvashok** [comment]
@codein-dwij fine i will, if you want any help on jekyll feel free to ask.

**Comment by hemantjadon** [comment]
So @Abhi2424shek  you will work on this, Final?

**Comment by abishekvashok** [comment]
@hemantjadon sure finalized

**Comment by sudo-panda** [comment]
Well I have found a way to remove the error. If you could merge the pull request.
https://github.com/fossasia/gci16.fossasia.org/pull/139
It would solve the problem.

**Comment by abishekvashok** [comment]
@hemantjadon I think it's resolved, you merged my PR remember

**Comment by abishekvashok** [comment]
#154

**Comment by hemantjadon** [comment]
@Abhi2424shek It doesn't seem so
![screen shot 2016-12-04 at 5 17 07 pm](https://cloud.githubusercontent.com/assets/11755543/20865956/f4c63766-ba45-11e6-9664-729d936172cb.png)

**Comment by sudo-panda** [comment]
@Abhi2424shek since this one is the only one with the problem you could use word wrap: ellipsis 
I mean just add this in main.css:
.students-sec .avatar p{
	white-space: nowrap;
	text-overflow: ellipsis;
	overflow: hidden;
}

**Comment by abishekvashok** [comment]
@Baidya99 I will give PR soon

**Comment by codein-dwij** [comment]
Okay

**Comment by hemantjadon** [comment]
@Abhi2424shek any updaes on this issue?

**Comment by abishekvashok** [comment]
@hemantjadon I am working will give a huge PR adding the student section geo-location also

**Comment by hemantjadon** [comment]
Okay @Abhi2424shek go on 👍

**Comment by abishekvashok** [comment]
@hemantjadon sure!

**Comment by codein-dwij** [comment]
Can I ask why you closed it ? :P

**Comment by yashNadun** [comment]
![image](https://cloud.githubusercontent.com/assets/16904196/21022141/8456e372-bda1-11e6-9943-8e453725081f.png)
@Abhi2424shek I think you can decrease the font size in main.css line 285 to solve this problem

**Comment by PolBaladas** [comment]
Hi there, is this being solved? @Abhi2424shek

**Comment by abishekvashok** [comment]
Fixed it @PolBaladas @hemantjadon see PR #416

**Comment by codein-dwij** [comment]
Nice
