### ISSUE TITLE
Find image quality and scale images.

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/gci16.fossasia.org#140]
Some student images are very big. This means a slow loading of the website.
Please

- find a good image size
- scale existing images
- Find a way to make new images scaled to the right size:
  - document somewhere where new images are added that there should be a certain size
  - ...?

**Comment by abishekvashok** [comment]
@niccokunzmann I've added a PR and it's merged which solved most of the image problems, the rest come from within via API, let me see what I can do for it.

**Comment by hemantjadon** [comment]
@Abhi2424shek Okay cool so I am assigining you on this :)

**Comment by niccokunzmann** [comment]
@Abhi2424shek Pull-requests and issues have a number:

    https://github.com/fossasia/gci16.fossasia.org/pull/146
                                                        I  See above

You can reference them on Github using `#number`.
Please (always) reference the issue in the pull-request.
And in the text you wrote, you can add a reference to the number of the pull-request, so I know, what you are talking about without searching.

Now, I would like to know if I can close the issue and look at the PR. Can you help me find it?

**Comment by abishekvashok** [comment]
@niccokunzmann the number is #133

**Comment by niccokunzmann** [comment]
Cool, I see it is merged.

**Comment by niccokunzmann** [comment]
@Abhi2424shek What are your thoughts - what is the state of the issue, what did you find?

**Comment by abishekvashok** [comment]
We would add a PR to inform the students in the readme.md to use properly scaled images, and I would provide a link to an image optimiser that we will recommend. Please wait before closing it @niccokunzmann

**Comment by abishekvashok** [comment]
@niccokunzmann after PR #233 is merged we can close this. :)

**Comment by hemantjadon** [comment]
@Abhi2424shek It is not a PR but a closed issue.

**Comment by abishekvashok** [comment]
Sorry please see PR, #233
