### ISSUE TITLE
Put sections in header

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/gci16.fossasia.org#142]
The website has several sections. I would like to skip to them by clicking on some menu in the header.

**Comment by gaeun** [comment]
Can I work on adding the menu? I'm a GCI student.

**Comment by hemantjadon** [comment]
Yes @gaeun  go ahead :)

**Comment by sudo-panda** [comment]
Can I work on this too?

**Comment by hemantjadon** [comment]
Well @Baidya99 multiple students working on same section of code can make an overlap of work.
So i will recommend that you can help @gaeun to fixup the issue, but if she is not able to do so or willing to leave it you can take it up.

**Comment by sudo-panda** [comment]
@gaeun , are you working on it?

**Comment by gaeun** [comment]
@Baidya99 Yep

**Comment by niccokunzmann** [comment]
@Baidya99 and @gaeun You can work together and chat in the Fossasia slack. It is possible that you use the same fork and the same branch to collaborate and submit the work of you two on one branch. So, you can choose what you are comfortable with.

**Comment by hemantjadon** [comment]
Yes @Baidya99 @gaeun you can also do what @niccokunzmann has suggested, It is a more constructive idea.

**Comment by sudo-panda** [comment]
Okay.

**Comment by gaeun** [comment]
I think this issue can be closed now. @niccokunzmann

**Comment by hemantjadon** [comment]
Closing this after #211
