### ISSUE TITLE
What would you like on the website?

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/gci16.fossasia.org#143]
There is so much we can put on the website. Let us discuss it here: What would you like to see on the website for GCI16? It is your site, what are your ideas?

**Comment by abishekvashok** [comment]
A list of student projects

**Comment by niccokunzmann** [comment]
@Abhi2424shek Can you create an issue? I will tag it as feature.

**Comment by abishekvashok** [comment]
@niccokunzmann sure please wait

**Comment by abishekvashok** [comment]
@niccokunzmann we could add a get together map where students could view nearby buddies and meet together. I got the blueprint, we would create a meet with them button for each student just like their fb link pops up. On clicking it returns to another page or a pop-up with an idea me that would display data from the other page, which will receive the student name as a GET request parameter, get their location from students.yml and can send invitations via email(Using Gmail API) . We would make the students upload their location by creating a temporary gio location code which inserts into students.yml. The question is how could I do this insert via Jekyll. Or, we should make them update via PR, but that would be an inconvenience what is your opinion @niccokunzmann

**Comment by niccokunzmann** [comment]
@Abhi2424shek Cool. Would you like to create an issue or split the thing up into several issues?

In case you want to write issues as I think I like them:
If you write an issue, you can use the form:

Context: Which page/section, what is your background.
Goal: What do you want to do?
Problem: What hinders you do reach the goal?
Solution: How would you use the new feature? No code described, no technical requirements
(Implementation) Hints: All tech stuff goes here.

The idea: others can work on the issue and bring in new ideas - this is why problem, solution and hints are split up. If you add only one technical detail to the solution, half the people will decline because they would have liked to do it a bit differently.
You can use the form it if you like :)

**Comment by abishekvashok** [comment]
Nope creating an issue will waste our time this can be done in a single PR I will give one...

**Comment by niccokunzmann** [comment]
I will close this, since nobody answers any more. We can create a new issue like this any time.
