### ISSUE TITLE
Include brief biography in students section

### ISSUE THREAD

**Issue by gaeun** [fossasia/gci16.fossasia.org#147]
The student section currently features photos and social media/Github links of GCI students. It would be nice if the section displayed brief bios that most students write when uploading their information to students.yml.

**Comment by abishekvashok** [comment]
The students section needs a total change both in design and features, let me give it a try or can I.

**Comment by gaeun** [comment]
@Abhi2424shek I'm working on making the design more consistent across sections. We can work together on adding new features! What features do you have in mind?

**Comment by hemantjadon** [comment]
@Abhi2424shek you are already working on 2-3 issues in parallel, so let @gaeun try we can help her out in the mean time by working together :)

**Comment by abishekvashok** [comment]
Sure

**Comment by abishekvashok** [comment]
What's the status @gaeun want some help

**Comment by gaeun** [comment]
@Abhi2424shek Working on it... There are some problems with long names, but I think I figured it out

**Comment by jigyasa-grover** [comment]
@gaeun Update on this ? :)

**Comment by gaeun** [comment]
@jig08 On it! I was working on the web tweets first, sorry :p

**Comment by jigyasa-grover** [comment]
No worries, just follow up on issues/PRs more than 4 days old. 
Expecting your PR for this sson 😉

**Comment by gaeun** [comment]
I'll close this issue now, it's been fixed in the above PR. :)

**Comment by niccokunzmann** [comment]
@gaeun If you reference your cgi-task in the pull-request, we can review it faster.
https://codein.withgoogle.com/dashboard/task-instances/5201318375325696/
