### ISSUE TITLE
Fix second imaged in slider

### ISSUE THREAD

**Issue by rhemon** [fossasia/gci16.fossasia.org#151]
Second image in slider not showing up

![screen shot 2016-12-04 at 11 19 12 am](https://cloud.githubusercontent.com/assets/6615517/20864259/a7a9784e-ba13-11e6-9290-38ca2b8a3e57.png)

**Comment by hemantjadon** [comment]
@rhemon would you like to take this up?

**Comment by rhemon** [comment]
hmm alright, will work on it

**Comment by hemantjadon** [comment]
Seems to be fixed now.
Thanks for the PR @rhemon
