### ISSUE TITLE
Problem with students section.

### ISSUE THREAD

**Issue by sudo-panda** [fossasia/gci16.fossasia.org#159]
Is it just on my computer or that the students section has started looking like this:
![capture](https://cloud.githubusercontent.com/assets/16690760/20864319/f9861052-ba11-11e6-9ff2-2873001593d7.PNG)
![Uploading Capture2.PNG…]()

**Comment by hemantjadon** [comment]
I guess its fixed now. Please check again

**Comment by sudo-panda** [comment]
What happened to the previous format?

**Comment by hemantjadon** [comment]
Which format are you refering to ?

**Comment by sudo-panda** [comment]
One with the red box and the transition with a box opening down.

**Comment by hemantjadon** [comment]
I guess this seems better so closing this, some students are already working on the UI Patches, so let's wait and see their progress.
