### ISSUE TITLE
Social Media part needs improvement

### ISSUE THREAD

**Issue by rhemon** [fossasia/gci16.fossasia.org#163]
If you notice in the end each of social media component are of different size, I think it would look better if we have them of equal size. And  either we make them small and fit in one row, or we can make them big but have better alignment.

**Comment by hemantjadon** [comment]
Would you like to work @rhemon or should wi wait for someone else to claim it?

**Comment by rhemon** [comment]
i am working on it

**Comment by PolBaladas** [comment]
I was thinking abt the same @rhemon. I'd not make them fit in one row. maybe two and have nice box sizes.

**Comment by rhemon** [comment]
yeah its really hard to get them fit in one row @PolBaladas thats why I am going with the later option, making first four big (facebook, g+, twitter, github) with equal width and height. Not doing this to youtube since it will ruin youtube video will get ruined, so I am making that centered in the last row.

**Comment by PolBaladas** [comment]
Yup. Great Idea. Big youtube last row is what I had in my head too. If you need anything... Feel free to ping me. @rhemon

**Comment by rhemon** [comment]
ok thanks then  I will take that offer and request you to fix the youtube row, I am doing a PR on the fix of the first two row, what do you say?

**Comment by rhemon** [comment]
@PolBaladas I am asking this cuz I am having a tough time fixing the youtube thing, its ending up like this for some reason : 
![screen shot 2016-12-04 at 4 37 39 pm](https://cloud.githubusercontent.com/assets/6615517/20865630/73b5cae6-ba41-11e6-848e-d6f3c182f66a.png)

or atleast suggest me what can I do?

**Comment by rhemon** [comment]
@PolBaladas sorry, forget it, somehow managed to solve it

**Comment by rhemon** [comment]
doing the PR now

**Comment by PolBaladas** [comment]
Oops! Too late. Good Job @rhemon well made. Anything else (any task) ping me!

**Comment by rhemon** [comment]
https://github.com/fossasia/gci16.fossasia.org/pull/175 Here's the PR

**Comment by hemantjadon** [comment]
Hey @rhemon @PolBaladas You will have to do some more work again on this. A Flickr album has also been added. Please check

**Comment by abishekvashok** [comment]
I could pop in for help too

**Comment by PolBaladas** [comment]
Okay! @hemantjadon  What else can be done?

**Comment by hemantjadon** [comment]
@PolBaladas Well truly speaking there is a huge scope of improvement in UI behaviours.
The site is not at all mobile responsive, and need many UI patches to be a good site.

That being said I would like to stick to the simple stuff and merge the PR's of newcomers (To motivate and support them), and these PR's contain code which is not that great, but this is a platform to bring up the new developers and many of them are writing html and css for the first time so it will not be fair to judge them on UI/UX patterns and first get them acquainted with git and github along with Merges, PR's and squashing commits.

So for now let's try to improve in parts, section by section trying to improve the design (Not that easy with so much of PR's merging each day) and check for overall design after the things settle down a bit.

**Comment by PolBaladas** [comment]
I agree with you @hemantjadon. GCI site is a support and start place. Working on other open source projects is the main goal here so we can slowly and pacefully (e.g. section by section) improve the site while new students arrive and upload their data. We can make more UI/UX changes later on.

**Comment by rhemon** [comment]
@hemantjadon @PolBaladas 
I am not sure if its a problem in my laptop, but at times some parts (most of the time github) of social media don't show up properly, however it works fine in the pc that we have. 
I would like to confirm that its actually showing up properly, and that its only a problem in my laptop. If not we will have to look into it.

**Comment by hemantjadon** [comment]
@rhemon according to  me the Site is working fine for now so closing this currently will reopen once other ui improvements are required
