### ISSUE TITLE
Which LICENSE to choose?

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/gci16.fossasia.org#171]
This website does not have a license.
It should have a license to make collaboration legal^^

But which license to choose?

I have tree suggestions:

- GPL - so derivates need to be published and we can be sure about the license of new code.
- AGPL - if we serve the code from a server, we may want to get access to the source code.
- Creative Commons Share Alike - This is for creative work.

Which license (also not mentioned above) should be the license for the project? Students: You are welcome to read about the licenses and discuss - after all you wrote the code.

**Comment by abishekvashok** [comment]
GPL is my recommendation

**Comment by PolBaladas** [comment]
I'd go for GPL too.

**Comment by niccokunzmann** [comment]
Who wants to do a PR?
By the way: If you create the LICENSE file with the github GUI, it automatically suggests the full text.

**Comment by PolBaladas** [comment]
Okay, I'll do it.

**Comment by PolBaladas** [comment]
I'll do v3.0.
Is that okay?
Thanks

**Comment by niccokunzmann** [comment]
Okay, can be closed...

**Comment by PolBaladas** [comment]
Okay. Thanks.
