### ISSUE TITLE
Add a section projects

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/gci16.fossasia.org#176]
Add a section students where students could display their projects made in GCI.

**Comment by PolBaladas** [comment]
Agreed!

**Comment by abishekvashok** [comment]
I would work on this guys anyone interested to join me

**Comment by sh4dowb** [comment]
See pull request https://github.com/fossasia/gci16.fossasia.org/pull/301 , should be closed after merge

**Comment by m1guelpf** [comment]
@hesapadim Will be closed when merged.
Your PR still needs more work

**Comment by abishekvashok** [comment]
Since a section has been added we will close this.
