### ISSUE TITLE
Add a space character between 'Open by' and account

### ISSUE THREAD

**Issue by hoangvanthien** [fossasia/gci16.fossasia.org#179]
This is not a big deal but it bothers my eyes. :)
![screen shot 2016-12-04 at 20 08 58](https://cloud.githubusercontent.com/assets/11438948/20866323/ac2da51c-ba5d-11e6-91ec-e6d3e685e775.png)

**Comment by aayusharora** [comment]
ok @hoangvanthien do you like to fix this ?

**Comment by hoangvanthien** [comment]
I'm on my way. :)
