### ISSUE TITLE
move figcaption of MBDyn logos up

### ISSUE THREAD

**Issue by louisgag** [fossasia/gci16.fossasia.org#196]
In its current state, the website is unable to properly show the name of the authors of the MBDyn logos.

This is likely cause by the height (3.5em) of the currently used effect-gcihover / figcaption tag in the stylesheets/main.css file.

It could be changed (unless the figcaption is used somewhere else which would mean it is better to create another figcaption specifically for MBDyn logos...)

Cheers,
![screenshot from 2016-12-04 19-20-31](https://cloud.githubusercontent.com/assets/12291709/20868255/7ce9ba4e-ba57-11e6-8420-1dda1fadd64c.png)
![screenshot from 2016-12-04 19-20-39](https://cloud.githubusercontent.com/assets/12291709/20868256/7ce9bca6-ba57-11e6-8ebe-b0a5c5f09237.png)

-Louis

**Comment by sudo-panda** [comment]
I would like to resolve this.

**Comment by louisgag** [comment]
I think there is a task for it, isn't there ? (I saw at least on for last year's website)

**Comment by jigyasa-grover** [comment]
@Baidya99 If you take up a task corresponding to this, it'll be great. Let us know if you claim it, we can then assign you this accordingly. Cheers !

**Comment by sudo-panda** [comment]
I think tough this issue is resolved there is one more issue in the same section. The names are getting out of the box. Can I solve it.

**Comment by jigyasa-grover** [comment]
@Baidya99 Sure.

**Comment by jigyasa-grover** [comment]
Follow up in Issue #256 , closing this.
