### ISSUE TITLE
Loklak Web Tweets

### ISSUE THREAD

**Issue by PolBaladas** [fossasia/gci16.fossasia.org#197]
Add a Loklak Web Tweets Section for FOSSASIA's account.
https://codein.withgoogle.com/tasks/5745830396952576/

**Comment by PolBaladas** [comment]
I'll start working on it.

**Comment by hemantjadon** [comment]
Hi @PolBaladas would you like to discuss what you will be exactly implementing

**Comment by PolBaladas** [comment]
Sure @hemantjadon 
This would be the idea: https://codein.withgoogle.com/tasks/5745830396952576/

**Comment by hemantjadon** [comment]
Okay that seems cool

Keep Coding :)

**Comment by abishekvashok** [comment]
I too have the task, working on, may we could collaborate @PolBaladas @hemantjadon

**Comment by PolBaladas** [comment]
Sure! If you want to work on HTML i can code the javascript, no problem
We should see if mentors will accept and mark the task as completed for both of us.

**Comment by abishekvashok** [comment]
@hemantjadon your opinion, I can have the API, you customise the UI bro is it fine

**Comment by PolBaladas** [comment]
Is that a question? @Abhi2424shek 😂 😂  
If you wanna do the API, no problem mate.

**Comment by hemantjadon** [comment]
@PolBaladas @Abhi2424shek 
Sure you can do the work together, after all we are here to collaborate and learn together.

But make sure you do the parts with co-ordination and informing each other about the progress, so there are no conflicts.

We will approve both of your tasks if work is completed properly.

But important is that you have good communication with each other and **NO** race around conditions please :)

Cheers :)
Keep Coding :)

**Comment by abishekvashok** [comment]
Sure mate just wait I would give in a PR mate

**Comment by niccokunzmann** [comment]
Just as information: One of you can give the other write access to the own fork and then you can work on the same branch. 
Also: You can do `git remote add <giturl>` to push  and pull changes from another persons branch.

**Comment by PolBaladas** [comment]
Very nice idea @niccokunzmann Will do that. What do you think @Abhi2424shek? Wanna use your fork or mine?

**Comment by abishekvashok** [comment]
@PolBaladas go on i will remote from u, bro 😉

**Comment by hemantjadon** [comment]
@PolBaladas @Abhi2424shek Please decide who is gonna do which part

**Comment by abishekvashok** [comment]
We r on it 😃 don't worry, just see our work fly high 😉 @hemantjude

**Comment by abishekvashok** [comment]
Sorry @hemantjadon

**Comment by PolBaladas** [comment]
@Abhi2424shek Would you mind If i worked on the API? Since I've already started working on it and last year I worked on Loklak's core python and javascript implementations.

Thanks

**Comment by PolBaladas** [comment]
@Abhi2424shek Added you as collaborator in https://github.com/PolBaladas/gci16.fossasia.org Could you update it from upstream? Thanks

**Comment by abishekvashok** [comment]
Sure @PolBaladas

**Comment by abishekvashok** [comment]
@PolBaladas check the PR, remote clone it and let's work: #267

**Comment by PolBaladas** [comment]
Okay @Abhi2424shek

**Comment by abishekvashok** [comment]
Let's make it awesome buddy.

**Comment by PolBaladas** [comment]
@Abhi2424shek Sure 😉

**Comment by gaeun** [comment]
Have you guys actually claimed the task that corresponds to this? I've currently claimed https://codein.withgoogle.com/dashboard/task-instances/5399005351641088/, and I'm wondering which parts you're working on.

**Comment by abishekvashok** [comment]
@gaeun yes we claimed, we could collaborate, I will send you an invite, please wait.

**Comment by abishekvashok** [comment]
@gaeun here's the link: https://github.com/Abhi2424shek/gci16.fossasia.org/invitations and the PR we will be working on is #267

**Comment by gaeun** [comment]
@Abhi2424shek Thanks! Which parts are you each working on

**Comment by abishekvashok** [comment]
@gaeun I am on the api and he's on CSS, I think you could do html and help us both in css as well as javascript, is it ok?

**Comment by gaeun** [comment]
@Abhi2424shek Sounds good, let me know when you have the API implementation figured out (or if I should help in anyway). I can work on styling it.

**Comment by hemantjadon** [comment]
Hi @Abhi2424shek @PolBaladas I think you guys are doing good.
Welcome @gaeun, Please all three of you distribute the roles and work to be done for smoother workflow.

**Comment by PolBaladas** [comment]
Sorry I've been offline for a couple of days (not feeling well) @Abhi2424shek @gaeun Are you on slack? We should talk there and see how we distribute tasks instead of using this thread. The task is not that big.

**Comment by PolBaladas** [comment]
@Abhi2424shek Are you using other people's code? If so, ask @hemantjadon how to proceed, maybe should be mentioned somewhere.

**Comment by hemantjadon** [comment]
@Abhi2424shek @PolBaladas 
What other mentions are you talking to ?

Please Elaborate
> Are you using other people's code?

**Comment by abishekvashok** [comment]
I don't work on any other persons code, I elaborated(understood) from an open source project given in the task I didnt used it as is, the basic idea is taken and I wrote the code in the atom text editor, tested it on Firefox and chrome, and posted as a commit, the codes not perfect yet cause I wrote it... @PolBaldas I wrote the code, it further needs modifications however I used the same names for the functions and the sub functions and the script files so that another file included dynamically works (Cross orgin site errors).

**Comment by abishekvashok** [comment]
@PolBaladas I am on slack will DM you

**Comment by abishekvashok** [comment]
@PolBaladas and about a file I committed it's from a loklak API model site, it is provided as is under the same licence obeying it's conditions. Please see:

**Comment by hemantjadon** [comment]
@PolBaladas @Abhi2424shek No worries, i was just checking out. Is your code now working on your fork (even a part of it)? I would love to check it out.

Cheers :)
Keep Coding :)

**Comment by abishekvashok** [comment]
@hemantjadon we are facing a small bug and I it will need a total makeover, just wait... I would give in a new commit

**Comment by PolBaladas** [comment]
Okay @Abhi2424shek now I know. Don't worrty mate i was just asking. Sorry for being a bit late, Not feeling well yet, still a bit sick.
I've seen the slack channel, good job.

**Comment by abishekvashok** [comment]
@PolBaladas awesome commitment bor, praying for you to get well and can you share your fork's invite.

**Comment by PolBaladas** [comment]
I'll work directly on your fork. @Abhi2424shek

**Comment by abishekvashok** [comment]
@geuan has a fork

**Comment by abishekvashok** [comment]
Let's work there

**Comment by jigyasa-grover** [comment]
Update on this ? :)

**Comment by abishekvashok** [comment]
@jig08 we are working we will submit a PR soon.

**Comment by abishekvashok** [comment]
@jig08 @hemantjadon it's fixed
