### ISSUE TITLE
Open Pull-Requests Piling up :(

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/gci16.fossasia.org#199]
We have a lot of [pull-requests](https://github.com/fossasia/gci16.fossasia.org/pulls) piling up. For me as mentor it is hard to keep the overview.
Also I do not know what should be done with them?

You as contributors know best what you would like to be done with them and how you feel.
What is your preferred strategy to deal with the open pull-requests?

**Comment by sudo-panda** [comment]
Some of them are older than 4 days and no the contributors have not responded to the queries. You should close them.

**Comment by jigyasa-grover** [comment]
Exactly, many contributors don't respond to their prev PRs for days and start with new ones. Duplicity is tough to manage.

**Comment by niccokunzmann** [comment]
@Baidya99 usually, this contract should be written down to not disappoint people or make it look like an act of arbitrary force. The file where to do this is the contributing.md file. It is shown by Github when you create an issue or a pull-request.

Also @jig08 would you like to create the contributing.md file with this one rule?

**Comment by niccokunzmann** [comment]
If you think, this repository needs an other rule, please consider to create an issue which will be tagged as question, we can discuss it a bit and then merge a pull-request.

**Comment by jigyasa-grover** [comment]
@niccokunzmann On it :)
