### ISSUE TITLE
Who could be a maintainer?

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/gci16.fossasia.org#207]
I believe that students can be very good maintainers of this site.

What maintainers do: comment on pull-requests, merge pull-requests. Close pull-requests according to [contributing.md](https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/CONTRIBUTING.md).

What are the rules to be come a maintainer, what are rules to be removed as a maintainer?

**Comment by abishekvashok** [comment]
So that means we could merge a PR sweet. But make a thorough review guys

**Comment by PolBaladas** [comment]
I find this thread interesting. We cannot expect that mentors spend their time reviewing everything 24/7.
I've been trying to help some of you and commenting on PR or Issues to create good working/collaborating "habits". As long as I've already got write access, I volunteer!  

Thanks!

**Comment by niccokunzmann** [comment]
So, I would like to be maintainers:
@oanarosca - [because of the commits](https://github.com/fossasia/gci16.fossasia.org/graphs/contributors)
@PolBaladas - [because of the volunteering](https://github.com/fossasia/gci16.fossasia.org/issues/207#issuecomment-264829618)
@rhemon - [because of the commits](https://github.com/fossasia/gci16.fossasia.org/graphs/contributors)

Any objections, also from the three people?

**Comment by oanarosca** [comment]
If no one has any objections, I'd love to help! Thanks for the opportunity :blush:

**Comment by rhemon** [comment]
seems very interesting, but I am not sure if I am good enough for it. But of course I would love to help, even if I am not sure about merging PRs, I can surely help my commenting and suggesting changes (although i can actually do that now even without being a maintainer). If mentors and partnering student maintainers are ok being annoyed by me (at least for first few days) confirming the merge with them, would love to be a part of it.

**Comment by niccokunzmann** [comment]
@PolBaladas @oanarosca You can now merge pull-requests. Many tasks require only a merged pull-request. When you merge, students may think that this is an approval of their task. Please find a way to spare them their frustration. I will create a document where we write down what your responsibility is and what is not - the document will help you, I believe!

@rhemon I think, you can do this. Let's set up the document and then you can start safely :)

**Comment by rhemon** [comment]
alright, I will try my best

**Comment by niccokunzmann** [comment]
Ups, I wanted to create a PR for you but I accidentially hit commit:

https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/maintainers.md

This file is for you. It is just my start. Now, you can create Pull-requests and merge and change your responsibilities for yourself.

**Comment by niccokunzmann** [comment]
Just delete and add what you find most valuable for yourself.

**Comment by niccokunzmann** [comment]
Happy maintaining! I you have the fear of doing something wrong, you can admit it. This is an experiment for us. Let us see where it leads. You can close this issue if you think so.

**Comment by PolBaladas** [comment]
Okay to all! Thanks @niccokunzmann Great idea creating that guide file for maintainers 👍 😄 
We will need to be careful with our merging requirements and how to tell students that a merge is not directly a task approval.

(bit afraid here too hehe)

**Comment by abishekvashok** [comment]
Best of luck guys

**Comment by m1guelpf** [comment]
If it isn't late, i'd also like to volunteer.

**Comment by niccokunzmann** [comment]
It is never too late. @m1guelpf I am adding you because of your experience in open-source. Please read the rules in CONTRIBUTING.md and maintainers.md. You can add your ideas via pull-request.

@fossasia/gci16-maintainers You got a new team member :)

I am re-opening this so we can have an ongoing discussion about the maintainers :)

**Comment by m1guelpf** [comment]
@niccokunzmann Thank you! I will try my best
Also, I'm seeing in the contributors file that we can merge PR's, but it seems that I don't have that permission. What am I missing?

**Comment by rhemon** [comment]
@m1guelpf @niccokunzmann I think all o us, student mentors are facing that problem.

**Comment by niccokunzmann** [comment]
@rhemon  @m1guelpf Can you try again? I added you, see below.
![capture](https://cloud.githubusercontent.com/assets/564768/21002640/19220570-bd27-11e6-9334-5448e3053639.JPG)

**Comment by niccokunzmann** [comment]
Also, I did not give you administrative access, just write access. As I did not want to give and take too much responsibility from the start. I think, it is going well and if you need administrative access, you can write here and we discuss it.

**Comment by rhemon** [comment]
nah i think its ok without that access. whats important is helping the
students bring a better and suitable work for this project. it is also a
good learning experience for us

**Comment by rhemon** [comment]
and yeah it looks like I can merge now :)

**Comment by abishekvashok** [comment]
We could go for more maintainers @niccokunzmann new and new PRs are emerging fast.

**Comment by niccokunzmann** [comment]
@Abhi2424shek You watched the repository, can you make a suggestion?

**Comment by abishekvashok** [comment]
@niccokunzmann not really but try to get some more maintainers it will definitely help out won't it.

**Comment by jigyasa-grover** [comment]
@niccokunzmann add @Abhi2424shek to @fossasia/gci16-maintainers pls :)

**Comment by codein-dwij** [comment]
Nice Team! Will apply for being a maintainer next year when I will be having a lot of experience , time and will be nearly 16 by then :)

**Comment by niccokunzmann** [comment]
@codein-dwij Would you like to try to be a maintainer, now? It is quite easy: The task is to keep the contributors happy. You can also read about what you can and can not do here: https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/maintainers.md If you do not want to be a maintainer, you can keep going as you already did.
Also, you can add suggestions via pull-request. Also, there is a task especially for the community.

@fossasia/gci16-maintainers Welcome @codein-dwij to the team.

**Comment by codein-dwij** [comment]
Thanks for adding me @niccokunzmann ! I had read everything even before I was added!
It would be a nice experience  being a maintainer. :D

**Comment by m1guelpf** [comment]
Welcome @codein-dwij !
Can you share your FOSSASIA slack username so you can enter the mantainers chat?

**Comment by codein-dwij** [comment]
Yeah. My username is dwij [@dwij]
A silly question : How do I assign someone to an issue and add labels ?

Edit: Sorry I found the answer myself and assigned myself  by mistake

**Comment by gaeun** [comment]
@niccokunzmann If it's not too late to ask, could I be a student maintainer too?

**Comment by niccokunzmann** [comment]
@gaeun You are added. Welcome!

@fossasia/gci16-maintainers - Our team is growing :)

**Comment by m1guelpf** [comment]
@gaeun Welcome!
Also, can I have your FOSSASIA Slack username for adding you to the private mantainers chat?

**Comment by abishekvashok** [comment]
@m1guelpf I ain't there on the channel yet, ping me with the id abishek24 on slack.

**Comment by animeshsinghweb** [comment]
@niccokunzmann can you add me as a maintainer too? My slack username is animeshsinghweb.

**Comment by Hesham-Burawi** [comment]
@m1guelpf If there is still space id like to become a student maintainer as well please!

**Comment by niccokunzmann** [comment]
@animeshsinghweb I added you.

**Comment by niccokunzmann** [comment]
@Hesham-Burawi you are not in the organization, you first need to join @oanarosca knows how to do that, I believe.

**Comment by m1guelpf** [comment]
@Hesam-Burawi https://fossasia.org/apply-pupils

**Comment by gaeun** [comment]
@m1guelpf Sure, my id is just gaeunkim.

**Comment by Hesham-Burawi** [comment]
@niccokunzmann Ive joined the organization

**Comment by niccokunzmann** [comment]
You are in.

**Comment by Hesham-Burawi** [comment]
Thanks!

**Comment by Hesham-Burawi** [comment]
oh and my Slack ID is hesham_burawi19

**Comment by ankitrgadiya** [comment]
@niccokunzmann I'd like the opportunity of being the maintainer of this repo if its not too late.
Maybe I'll learn a thing or two about maintaining.

**Comment by SagarKhodpia** [comment]
hiii

**Comment by BhavyaMittal** [comment]
Hi everyone
How are you all?

**Comment by oanarosca** [comment]
I think it's fine to close this now.
