### ISSUE TITLE
Add good squashing tutorials to contributing.md

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/gci16.fossasia.org#217]
There are some good squashing tutorials out there and I know some of the students have used them.
Can you add links to those tutorials to the contributing file, so we can help beginner much easier and consistently?

**Comment by jigyasa-grover** [comment]
@niccokunzmann 

Apart from that, these are also required:

* [How To Manually Fix Git Merge Conflicts (video)](https://www.youtube.com/watch?v=g8BRcB9NLp4) 
* [Changing a commit message](https://help.github.com/articles/changing-a-commit-message/)

Should I add these in it too  ?

**Comment by PolBaladas** [comment]
I suggest the section to be called "Git Tutorials". We could then include @jig08 links without confusing. @niccokunzmann

**Comment by PolBaladas** [comment]
Just asked on Slack which tutorials have the students found to be the best ones.

**Comment by niccokunzmann** [comment]
Cool. Yes, why not an extra section :)

**Comment by jigyasa-grover** [comment]
Making a separate section in CONTRIBUTING.md file.

*Edit:* Added [here](https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/CONTRIBUTING.md) in a new section, feel free to suggest more such helpful links and add them.

**Comment by PolBaladas** [comment]
Okay!

**Comment by rhemon** [comment]
Found this good guide : 
http://rogerdudler.github.io/git-guide/
add this, I was going to do it but showed merge conflict and stuff, and at the moment really dont feel like dealing with those

**Comment by PolBaladas** [comment]
Ooops, already added @rhemon! 
Okay mate, keep up the good work!

**Comment by rhemon** [comment]
gg no problem

**Comment by rhemon** [comment]
This is done, so it should be closed.
