### ISSUE TITLE
Multiple logos for MBDYN

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/gci16.fossasia.org#223]
@jig08 @hemantjadon As of now, we have three PRs with the same goal: the logo. Is this a problem? If yes, How can we solve this? #221 #202 #200 The students can collaborate but best if all was merged. Are formalities blocking our ability to collaborate? Maybe we should create discussion issues for tasks. What are your thoughts?

**Comment by hemantjadon** [comment]
@niccokunzmann 
The task says to "design the logo matching MbDyn's philosophy" also there is subtask "showcase your selected work on GCI16 website", so here is just a showcase for all the logos created by the students, so I don't think that is an issue for merging the PR (If logo has been showcased as mentioned). 
The broader issue earlier was submissions of some students were not reflecting MbDyns philosophy and I discussed with @louisgag about this in the morning and came up with the Idea that PR should be merged if the work is reflecting MbDyn's pholosophy (even remotely), If not ask the student to improve the design and close the PR temporarily.

**Comment by niccokunzmann** [comment]
Thanks for clarifying! I am relieved :)

**Comment by hemantjadon** [comment]
@niccokunzmann 
Also you mentioned about the `issues for tasks`. That seems to be a great idea as it will provide students to collaborate by helping each other out (True meaning of Open source software). Also some common issues may be specified there and it will help new students to take help from students who previously completed the tasks.
