### ISSUE TITLE
Unnecessary stylesheets

### ISSUE THREAD

**Issue by oanarosca** [fossasia/gci16.fossasia.org#224]
Since the website is currently pretty styled up with the css we've written, the original css files are no longer used (there was no change I could see while trying to remove the links to them one by one), and I suggest that we remove them completely, so that they don't affect the page load speed.

**Comment by jigyasa-grover** [comment]
@oanarosca Would you do the needful ?

**Comment by oanarosca** [comment]
Yep! I'll start right now
