### ISSUE TITLE
Speed up travis build

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/gci16.fossasia.org#226]
Travis can cache certain directories and has cache defaults for several languages.
It may be, we can speed up the testing process.

Hints: The result could be about 5 lines long but the question is how to find the right lines.

**Comment by abishekvashok** [comment]
Yes it could reduce the speed considerably we just need to specify cache:bundler simple and beautiful.

**Comment by niccokunzmann** [comment]
For docker, there could also be a cache so the image is not puled every time.

**Comment by abishekvashok** [comment]
I think it is enabled for default.

**Comment by abishekvashok** [comment]
@niccokunzmann we could also run the jobs in parallel like splitting them up.

**Comment by niccokunzmann** [comment]
Good idea: then, we need to make sure that

- the output is nice: pipe the parallel stuff to a file and view it on exit
- error if the parallel part fails

**Comment by abishekvashok** [comment]
I think if any of the jobs fail, Travis returns exit code 1 that means exit. And about piping we could achieve it easily. @niccokunzmann

**Comment by m1guelpf** [comment]
@niccokunzmann @Abhi2424shek Any updates on this?
Now that we have autocheck, speeding up build is very neccesary, to get faster responses to the user.

**Comment by niccokunzmann** [comment]
Please keep in mind that you can merge pull-requests even if the tests still run or did not succeed. It is more important to get the people on board than to have some tests satisfied. If you require green tests over happy contributors, you need to write it into contributing.md.

**Comment by abishekvashok** [comment]
@niccokunzmann I prefer happy contributors and good code, so we will need to do something and not sit like dull men.

**Comment by abishekvashok** [comment]
Since this issue has been looming large, @niccokunzmann I think we should create a python script that will be executed by travis to fix the failing tests, like adding new line at EOF and other stuff which the tests fail of, what do you say.

**Comment by m1guelpf** [comment]
@Abhi2424shek +1 for that

**Comment by niccokunzmann** [comment]
Maybe, we can change the parameters for coala

**Comment by jayvdb** [comment]
`coala --apply-patches`

**Comment by jayvdb** [comment]
btw, Docker caching isnt supported by Travis (but there are ugly workarounds) : https://github.com/travis-ci/travis-ci/issues/5358

**Comment by m1guelpf** [comment]
@jayvdb if Travis apply patches, then we need to setup git to push changes back...

**Comment by abishekvashok** [comment]
@niccokunzmann we could let coala apply the patches why dont we have a try plus we will rum travis tests parallel and cache travis, wont doing these close up this PR if all those worked :)

**Comment by niccokunzmann** [comment]
Sure, you can give it a try.

**Comment by jayvdb** [comment]
> @jayvdb if Travis apply patches, then we need to setup git to push changes back...

Yup, that can be done, but it isnt relevant to this issue about speeding up the travis build.

We can avoid the Docker if https://github.com/coala/coala-bears/issues/1000 is fixed.

**Comment by abishekvashok** [comment]
I've added travis cache #415 @niccokunzmann @jayvdb @m1guelpf now travis time consumption will start to decrease.

**Comment by abishekvashok** [comment]
@niccokunzmann we could now implement running the jobs in parallel

**Comment by Abhi2424shek** [comment]
@niccokunzmann let me see if we could make coala run parallel... I think I got a solution...

**Comment by m1guelpf** [comment]
@Abhi2424shek We can't, as the Travis tasks need an order.
(for example, We can't push to Percy without building jellkyl first)

**Comment by abishekvashok** [comment]
@m1guelpf I got a solution for that, We could run a job first and execute the next jobs parallel thorught the Travis metrix, but there's a slight bug which I am facing...
I would give in a PR soon.

**Comment by jayvdb** [comment]
> We can avoid the Docker if coala/coala-bears#1000 is fixed.

Subtask https://github.com/coala/coala-bears/issues/1044 is a GCI task https://codein.withgoogle.com/tasks/6276537751961600/

**Comment by abishekvashok** [comment]
I think this is the maximum here!

**Comment by jayvdb** [comment]
I can see many ways to speed it up :P
Is there a GCI task about speeding it up?

**Comment by robbyoconnor** [comment]
Not currently -- too lazy to make one...if you wanna do it -- be my guest @jayvdb -- I'll reopen it

We COULD cache the docker image for coala -- that's an option...

**Comment by abishekvashok** [comment]
We have a seperate issue for it @robbyoconnor

**Comment by jayvdb** [comment]
no, caching the docker image is not helpful (it is too big to be useful cached) and https://github.com/fossasia/gci16.fossasia.org/issues/603 is about caching the coala metadata (good idea, unrelated), are not the only ways to improve the travis build speed.

One of the largest chunks of time is the [`bundle install`](https://travis-ci.org/fossasia/gci16.fossasia.org/builds/190081836#L295), and there are other ways to improve it.

Please re-open.  We have generic "fix an issue" tasks which can be used to optimise the CI for this issue.

**Comment by abishekvashok** [comment]
Here you go @jayvdb

**Comment by m1guelpf** [comment]
@niccokunzmann @Abhi2424shek @jayvdb @robbyoconnor is this still needed not that CodeIn has finished?

**Comment by jayvdb** [comment]
indeed, it can be closed.

**Comment by robbyoconnor** [comment]
I don't think we can speed up the build anymore... The bottleneck is docker...everything else runs fast.
