### ISSUE TITLE
Github usernames' position

### ISSUE THREAD

**Issue by hoangvanthien** [fossasia/gci16.fossasia.org#231]
I'm working on it.
![screen shot 2016-12-06 at 09 27 35](https://cloud.githubusercontent.com/assets/11438948/20910867/cd8063c8-bb96-11e6-9603-2996184e9e5b.png)

**Comment by daminisatya** [comment]
Go ahead, i assigned it to u

**Comment by Worm4047** [comment]
I would like to work on it too.

**Comment by hoangvanthien** [comment]
I've made a PR @Worm4047.
