### ISSUE TITLE
Add Default for blogs without picture

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/gci16.fossasia.org#237]
In [this pull-request](https://github.com/fossasia/gci16.fossasia.org/pull/215) we can find a blog without logo.

- [ ] Create a default logo for blogs which do not have a blog_img or an empty blog_img
- [ ] test and display this default blog_img

**Comment by oanarosca** [comment]
May I work on this please?

**Comment by niccokunzmann** [comment]
Sure, please go ahead!
