### ISSUE TITLE
Increased code

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/gci16.fossasia.org#238]
The code on index.html is huge and can be optimised a lot. The slider can be loaded via Jekyll as well as the logos of MBDyn can be loaded dynamically via Jekyll.

It will definitely improve code quality and reduce quantity, making it easier for debugging.

It can be implemented easily by making changes in the index.html file.

**Comment by hemantjadon** [comment]
Want to take this up @Abhi2424shek ?

Also you will have to make sure that you will touch only the necessary parts of the code otherwise all the future PR's will get conflicts.

**Comment by PolBaladas** [comment]
Good idea @Abhi2424shek indeed, but be careful with merge conflicts.

**Comment by abishekvashok** [comment]
@hemantjadon I take it on.

**Comment by abishekvashok** [comment]
See the PR: #244 @hemantjadon @niccokunzmann after it's merged we could close it.
