### ISSUE TITLE
Test for image size

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/gci16.fossasia.org#239]
Create a travis script that checks for image sizes and fails if images are too big.
This allows us to identify the big images and keep the site loading fast.

**Comment by abishekvashok** [comment]
That's an awesome idea

**Comment by PolBaladas** [comment]
Will start working on it when i finish my current dev. Looks awesome.

**Comment by abishekvashok** [comment]
I done this issue, and added a test to the site that is an image checker but @niccokunzmann @jig08  my task is nt accepted it would be nice if you could review it 😊😋 link: https://codein.withgoogle.com/dashboard/task-instances/6211477637693440/

For give if am rusty... ;)
