### ISSUE TITLE
Add scrolling effect to site

### ISSUE THREAD

**Issue by Princu7** [fossasia/gci16.fossasia.org#250]
Just thought that it would be nice to have a scrolling effect on the page. Like when you click on the student section, it should scroll from the current position to the student section instead of directly jumping to that location. It should look good this way.

@jig08 @daminisatya @hemantjadon @niccokunzmann Please give your opinions and suggestions regarding it.

**Comment by hemantjadon** [comment]
@Princu7 this seems to be nice idea 👍

**Comment by niccokunzmann** [comment]
It is always fine if students create issues. It is their page after all.

**Comment by Princu7** [comment]
Which students are interested in taking this up?

**Comment by abishekvashok** [comment]
Sure for anything anywhere

**Comment by Princu7** [comment]
Closing via #253
