### ISSUE TITLE
Highlight the corresponding section in the navbar

### ISSUE THREAD

**Issue by Princu7** [fossasia/gci16.fossasia.org#251]
Currently, the navbar doesn't highlight the section on which we are present. It would be nice if it could highlight the corresponding section. Like if we are in the mentor section on the page, mentor should be highlighted on the navbar. Similarly, if we are on the students section, student should be highlighted on the navbar.

@jig08 @niccokunzmann @hemantjadon @daminisatya What do you guys think about this? Any student interested in taking this up?

**Comment by hemantjadon** [comment]
@Princu7 sure it will be a pretty neat feature to have .

**Comment by hoangvanthien** [comment]
Okay, let me try if I can help. :) I would call for help if needed !
