### ISSUE TITLE
Changing color of links from grey to black in footer

### ISSUE THREAD

**Issue by Princu7** [fossasia/gci16.fossasia.org#252]
I think this looks better
![screenshot from 2016-12-07 02-55-01](https://cloud.githubusercontent.com/assets/8847265/20944272/bf4b041a-bc28-11e6-82f0-ea5ca44a139a.png)
Compared to this
![screenshot from 2016-12-07 02-55-46](https://cloud.githubusercontent.com/assets/8847265/20944478/a4fc3a24-bc29-11e6-8d91-83136bd2de94.png)

What do you guys @jig08 @hemantjadon @daminisatya @niccokunzmann think? Any student interested in taking this up?

**Comment by oanarosca** [comment]
I want to do it!

**Comment by hemantjadon** [comment]
@oanarosca Sure go ahead 👍
