### ISSUE TITLE
Improve MBDyn logo design layout

### ISSUE THREAD

**Issue by SaptakS** [fossasia/gci16.fossasia.org#256]
![screenshot from 2016-12-07 12-38-39](https://cloud.githubusercontent.com/assets/9530293/20958161/3bb4d282-bc7a-11e6-8782-348a43e94965.png)

This looks a little disoriented.

**Comment by animeshsinghweb** [comment]
@hemantjadon @SaptakS I think I had resolved this. Does it still prevails, if so, assign it to me and I would work on it.
Thanks.

**Comment by hemantjadon** [comment]
Hi @Abhi2424shek Please check why there is so much  empty space in logo section?

**Comment by animeshsinghweb** [comment]
Can I try?

**Comment by abishekvashok** [comment]
@hemantjadon it's because the images are in a row and one of the elements in the row is larger than the other. To solve it @animeshsinghweb you could other resize the image or remove the row class name from the parent div. Go and try.

**Comment by hemantjadon** [comment]
Ya sure @animeshsinghweb you check this out.

**Comment by wingsylver** [comment]
Hi all, I've worked on this, and have the website working on my repo [here](https://william1835.github.io/gci16.fossasia.org/). If you approve the changes, I'll create a pull request for it. I'm a GCI student, by the way.

**Comment by oanarosca** [comment]
Issue if now fixed, so I'm closing this.
