### ISSUE TITLE
Mentors: Add Latitude and Longitude

### ISSUE THREAD

**Issue by BrainBuzzer** [fossasia/gci16.fossasia.org#266]
All mentors are requested to add their latitude and longitude to the YML file so that you will be located on the map. Read readme for more info about what to add.

PR #265 Issue #1

**Comment by abishekvashok** [comment]
@BrainBuzzer I will give in a PR which will make it more easy for mentors...

**Comment by jigyasa-grover** [comment]
@Abhi2424shek That'll be great !

**Comment by BrainBuzzer** [comment]
I've added both of those things to yml file.

**Comment by abishekvashok** [comment]
See PR #357

**Comment by abishekvashok** [comment]
@jig08 and all mentors I request you all to take a look at [https://gci16.fossasia.org/geo/](https://gci16.fossasia.org/geo/) and add your code urgently for the map has no mentors displayed.

**Comment by abishekvashok** [comment]
Mentors 😢 please co-operate yourself

**Comment by m1guelpf** [comment]
@Abhi2424shek Say it on Slack...

**Comment by jigyasa-grover** [comment]
I'll post it on the private mentors channel, or you could try adding info from the rough idea of their location you have :)
Or go ahead, ask 'em directly !

**Comment by abishekvashok** [comment]
@jig08 i will try to ping them on slack

**Comment by m1guelpf** [comment]
ping to @fossasia/fossasia-gci

**Comment by abishekvashok** [comment]
@m1guelpf they're floating in the sea of notifs but I will take a try pinging @fossasia/gci16-maintainers please all mentors, add your lat and lng using our geo locator and add it as a PR.

**Comment by m1guelpf** [comment]
@Abhi2424shek gci-mantainers team aren't mentors but students helping in the project.

**Comment by abishekvashok** [comment]
Some mentors are in it like (a)niccokunzmann

**Comment by m1guelpf** [comment]
@Abhi2424shek yes, but that ones have already added them.

**Comment by rhemon** [comment]
It might be faster if you just put the location based on their country. its
not necessary to know their exact possition. as far as i remember this was
to help students who are only good with their native language. right?

**Comment by robbyoconnor** [comment]
I am already in it.. @rhemon that won't work...for example the United States, Canada is HUGE

**Comment by abishekvashok** [comment]
@robbyoconnor can you post in the mentors channel sir

**Comment by robbyoconnor** [comment]
@Abhi2424shek this was the approriate place to say this.

**Comment by abishekvashok** [comment]
@robbyoconnor I am sorry then!

**Comment by abishekvashok** [comment]
Since this is in the standard form closing this....
