### ISSUE TITLE
Blog boxes need to be resized

### ISSUE THREAD

**Issue by hoangvanthien** [fossasia/gci16.fossasia.org#271]
![screen shot 2016-12-07 at 22 55 23](https://cloud.githubusercontent.com/assets/11438948/20974952/731bd332-bcd0-11e6-85d7-b944e65495a3.png)

**Comment by oanarosca** [comment]
You're right, I noticed this problem some time ago as well. Do you want to work on fixing this?

**Comment by hoangvanthien** [comment]
Let me try if I can help !
