### ISSUE TITLE
Broken image link in students section for `Ha Minh Chien`

### ISSUE THREAD

**Issue by jigyasa-grover** [fossasia/gci16.fossasia.org#287]
Broken image link in students section for `Ha Minh Chien`
Refer screenshot attached.

<img width="1280" alt="screen shot 2016-12-08 at 2 08 48 pm" src="https://cloud.githubusercontent.com/assets/9291400/21003185/f723205c-bd4f-11e6-8cbf-0197fa056305.png">

**Comment by hoangvanthien** [comment]
His image was saved as `hmc.jpg` while in the `students.yml` he typed it `chien.jpg`. Let me fix this.

**Comment by m1guelpf** [comment]
Fixed in #288
