### ISSUE TITLE
Is squashing really needed?

### ISSUE THREAD

**Issue by m1guelpf** [fossasia/gci16.fossasia.org#290]
Rigth now, we require all commits to be squashed into one to be merged, but Github has an squash and merge button, that would make everything easier.
Is manual squashing really needed for students?

**Comment by tradzik** [comment]
The most important thing is that commits are squashed before merged into repository. Otherwise it would cause big mess... 

I like encouraging students to do manual rebasing as it has more educational value. However, in my opinion if student does rebasing using Github app it is also fine.

Closing.
