### ISSUE TITLE
Add loklak web tweets section

### ISSUE THREAD

**Issue by gaeun** [fossasia/gci16.fossasia.org#291]
This is for the task https://codein.withgoogle.com/dashboard/task-instances/5399005351641088/

**Comment by m1guelpf** [comment]
@gaeun You have to open a pull request

**Comment by abishekvashok** [comment]
An issue is there already #197 , please check next time before opening one @gaeun

**Comment by m1guelpf** [comment]
So, then we can close this

**Comment by abishekvashok** [comment]
@m1guelpf we could have but waited for @gaeun

**Comment by m1guelpf** [comment]
@Abhi2424shek Sorry, should I reopen it?

**Comment by gaeun** [comment]
@m1guelpf No, it's fine. I'm working on it on his original issue.
