### ISSUE TITLE
Add favicon to gci16.fossasia.org

### ISSUE THREAD

**Issue by jigyasa-grover** [fossasia/gci16.fossasia.org#304]
Currently, there is no favicon for [gci16.fossasia.org](http://gci16.fossasia.org/), pls design one or simply add FOSSASIA's default one.

<img width="1280" alt="screen shot 2016-12-09 at 12 28 14 am" src="https://cloud.githubusercontent.com/assets/9291400/21023432/83257e82-bda6-11e6-95ca-f536816014b3.png">

**Comment by oanarosca** [comment]
I'm on it! :smile:

**Comment by jigyasa-grover** [comment]
Go ahead :)

**Comment by jigyasa-grover** [comment]
Also @oanarosca , change the title from `Gci16.fossasia.org` to a more suitable one or in proper format 😉
