### ISSUE TITLE
What is revert-148-gh-pages branch?

### ISSUE THREAD

**Issue by m1guelpf** [fossasia/gci16.fossasia.org#306]
What is that branch for?
It seems that it is only causing confusion to students...

**Comment by jigyasa-grover** [comment]
@m1guelpf Agreed, I suggest we should remove it.

**Comment by m1guelpf** [comment]
@jig08 It's currently blocked.
Should I close all open pull requests to that branch and remove it?

**Comment by m1guelpf** [comment]
@jig08 Also, offtopic but could you have a look to my GCI task?

**Comment by jigyasa-grover** [comment]
@m1guelpf Link please :)

**Comment by jigyasa-grover** [comment]
>@jig08 It's currently blocked.
>Should I close all open pull requests to that branch and remove it?

@m1guelpf Go ahead.

**Comment by m1guelpf** [comment]
Done
