### ISSUE TITLE
Use standard color for the footer

### ISSUE THREAD

**Issue by jigyasa-grover** [fossasia/gci16.fossasia.org#314]
It is observed that currently `#f7462c` is being used as background colour for the footer in [gci16.fossasia.org](http://gci16.fossasia.org/)

<img width="1280" alt="screen shot 2016-12-09 at 1 13 37 pm" src="https://cloud.githubusercontent.com/assets/9291400/21041498/61b34bb0-be11-11e6-82bd-97bbe2e832fb.png">

Use `#e12b00` instead which is being used as a standard in all [fossasia.org](http://fossasia.org/) sites :) 

<img width="1280" alt="screen shot 2016-12-09 at 1 14 01 pm" src="https://cloud.githubusercontent.com/assets/9291400/21041542/ab163cea-be11-11e6-9465-6c7bf0d40707.png">

**Comment by m1guelpf** [comment]
@jig08 Should I try or we are leaving this for CodeIn?

**Comment by jigyasa-grover** [comment]
@m1guelpf Let's leave some easier tasks for Code-In 😉
