### ISSUE TITLE
What is the difference between blogs.yml and blogs.yml~ ?

### ISSUE THREAD

**Issue by m1guelpf** [fossasia/gci16.fossasia.org#319]
I can see that in the _data/ folder there are two blog files:
The blogs.yml and the blogs.yml~
Which one of these files are neccesary, and can the other be deleted?

**Comment by abishekvashok** [comment]
@m1guelpf the ~ one is temporary, generated by some text editors like gedit. You can delete the ~ one it's unnecessary.

**Comment by Princu7** [comment]
Someone make a PR and delete it please.

**Comment by jigyasa-grover** [comment]
Closed via https://github.com/fossasia/gci16.fossasia.org/commit/682bc6d28e7857dff2efb56ebf3ad28decf59763
