### ISSUE TITLE
Broken "events" link in footer

### ISSUE THREAD

**Issue by ankitrgadiya** [fossasia/gci16.fossasia.org#328]
Events link in the footer is broken. It redirects to blog.fossasia.org/events which is not the right link.

**Comment by jigyasa-grover** [comment]
Thanks @ankitrgadiya , would like to rectify it ?

**Comment by m1guelpf** [comment]
@jig08 What's the correct link?

**Comment by jigyasa-grover** [comment]
[events.fossasia.org](http://events.fossasia.org/) shall be the one, I believe :)

**Comment by ankitrgadiya** [comment]
Yes I'll fix it Yeah events.fossasia.org is the correct one.
@jig08 Can I use it for this task. "Website: Claim an issue for the GCI website on github and make a substantial contribution"??

**Comment by jigyasa-grover** [comment]
@ankitrgadiya Sure, just include the link to your task in the corresponding PR.

**Comment by ankitrgadiya** [comment]
Okay thanks ! That's an easy one.
