### ISSUE TITLE
Find out what people of closed PR felt like and needed

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/gci16.fossasia.org#346]
@fossasia/gci16-maintainers This is for you:

Every closed and timed-out PR is our failed chance to bring someone into the community of contributors.
The problem occurs much before the time-out: The person does not like to contribute.
They once wanted: They created a pull-request.
But, they abandoned this.

For you: Find 3-5 People whose Pull-Request timed out, speak to them and find out, how they felt, what they needed. Find solutions with them that solve such future problems, suggest changes to our process.

If you like, we can create a GCI-Task for this.

**Comment by abishekvashok** [comment]
Yes that would be great, a GCI task @niccokunzmann that would encourage a lot of people, nice suggestion keep up the good work. 💡✅🎆🌲😉

**Comment by rhemon** [comment]
thats actually difficult, but it will be something helpful. i will have to look into all the PRs to find those people. however I think the biggest fear is the build checks. it would be nice if we were a bit flexible on that, i know its necessary but its something thats definitely scary and hard to absorb for beginners.

**Comment by abishekvashok** [comment]
@rhemon finding people is easy

**Comment by rhemon** [comment]
yeah but there is a chance someone who abandoned their work will not respond, he could have moved to some other task. but yeah its possible, and personally i find it hard to persuade people, since this will be a matter where we have to get them back into the work :P

**Comment by rhemon** [comment]
but we should do this

**Comment by abishekvashok** [comment]
Yes for a better community.

**Comment by niccokunzmann** [comment]
To correct: We can merge if the checks fail.
I created a task: https://codein.withgoogle.com/dashboard/tasks/5698701760659456/ But it is not yet published.

**Comment by abishekvashok** [comment]
We could ignore that section where the tests fail by adding a ignore tag

**Comment by champforevaa** [comment]
I think this is a very good idea and this may help us in improving the website, and also motivate the people.

**Comment by niccokunzmann** [comment]
I once heard a quote for teachers: "Before starting to motivate people, one should stop demotivating them." - just came to my mind.
Also, the task is published and you can claim it. Different and maybe difficult one, too.

**Comment by niccokunzmann** [comment]
Should I close it, since it is a task?

**Comment by m1guelpf** [comment]
@niccokunzmann I think so
