### ISSUE TITLE
Mentor note: Please mentors read

### ISSUE THREAD

**Issue by m1guelpf** [fossasia/gci16.fossasia.org#349]
#347 introduced a function to fail Travis and warn the user if editing index.html
This was made because students wewre editing this file to add them statically, instead of editing the data fields.
Now, what if you really want to edit index.html?
You could simply ignore Travis build, but that could cause confusion, so there's another way:
Just add 
```
<!-- Safe Edit -->
```
somewhere in the PR body and It will automatically hide the line and skip the test.
Thank you

**Comment by niccokunzmann** [comment]
Can you add this to the maintainers.md file somewhere?

**Comment by m1guelpf** [comment]
@niccokunzmann I'll do it later

**Comment by m1guelpf** [comment]
@niccokunzmann Done. Closing this.
