### ISSUE TITLE
Name getting out of the box

### ISSUE THREAD

**Issue by ankitrgadiya** [fossasia/gci16.fossasia.org#358]
Name box is not able to handle longer names like one in screenshot.

![screenshot from 2016-12-10 12-54-57](https://cloud.githubusercontent.com/assets/18071765/21071956/f9af4164-bed7-11e6-87ca-7f61c1131d2d.png)

**Comment by codein-dwij** [comment]
I think Someone is working on it.. If someone isn't Then I would love to :)

**Comment by jigyasa-grover** [comment]
@codein-dwij Ask about it on Slack or skim through prev open issues, resolve it ASAP.

**Comment by codein-dwij** [comment]
The issue is fixed.
