### ISSUE TITLE
Remove merge lines

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/gci16.fossasia.org#361]
#301 added merge lines.

- https://github.com/fossasia/gci16.fossasia.org/pull/301/files#diff-eacf331f0ffc35d4b482f1d15a887d3bR177
- https://github.com/fossasia/gci16.fossasia.org/pull/301/files#diff-eacf331f0ffc35d4b482f1d15a887d3bR209

@hesapadim What do you think?

**Comment by sh4dowb** [comment]
@niccokunzmann removed them, is it okay now?

**Comment by niccokunzmann** [comment]
I would like to merge it. Can you show me the PR?

**Comment by sh4dowb** [comment]
https://github.com/fossasia/gci16.fossasia.org/pull/364  @niccokunzmann
