### ISSUE TITLE
Fix Mentor Map & Flickr Photo sections that makes it difficult to scroll

### ISSUE THREAD

**Issue by gaeun** [fossasia/gci16.fossasia.org#365]
The mentor map section on the website makes it difficult to scroll through the website. I could work on creating margins next to the section so that scrolling doesn't zoom in or out on the map.

**Comment by Princu7** [comment]
@gaeun I was about to open the same issue. Thanks for creating it. Please make the margins. :+1:

**Comment by jigyasa-grover** [comment]
Exactly, scrolling has become extremely difficult.

**Comment by abishekvashok** [comment]
@jig08 I see it fixed, can we close this.

Current Flickr section:
![image](https://cloud.githubusercontent.com/assets/8947010/21078938/e7c6f5f2-bfa7-11e6-8331-ce46fc525034.png)

Current maps section:
![image](https://cloud.githubusercontent.com/assets/8947010/21078940/eded4436-bfa7-11e6-835c-f9a76901b28a.png)
