### ISSUE TITLE
Students map

### ISSUE THREAD

**Issue by m1guelpf** [fossasia/gci16.fossasia.org#371]
Having all mentors in a map is cool, but having both mentors and students would be awesome!
This should be easy, as the mentor code is already implemented.
To test it, I've added lat and lng to my student profile so, if it's working, I should appear in the map.

**Comment by abishekvashok** [comment]
I am working on it see issue #143

**Comment by m1guelpf** [comment]
@Abhi2424shek any updates on this?

**Comment by abishekvashok** [comment]
@m1guelpf would submit a PR today :)

**Comment by Elgayar** [comment]
Did someone solve this issue, or can I work on it?

**Comment by m1guelpf** [comment]
@Elgayar I think @Abhi2424shek is on it, maybe you should talk with him to coordinate.
(ping @Abhi2424shek )

**Comment by Elgayar** [comment]
@Abhi2424shek If you're stuck, let me help you! If you're not working on it, tell me so I can get my sleeves up and get the job done ;)

**Comment by gaeun** [comment]
I'll close this issue now that student maps have been added. Thanks!

**Comment by abishekvashok** [comment]
@Elgayar sorry for being late, I was multitasking with pretty good number of repos..
I don't mind you popping in for the organization i just want it to be implemented and that's all thankyou for your work.
