### ISSUE TITLE
Fix Student Projects section

### ISSUE THREAD

**Issue by m1guelpf** [fossasia/gci16.fossasia.org#373]
The projects section looks very strange...
![ScreenShot](http://marker.screenshots.prod.s3.amazonaws.com/9d8115d1ad334ae49d3f590ceb66607d-1481373878170.png)
<table><tr><td><strong>Browser</strong></td><td>Chrome 55.0.2883.75</td></tr><tr><td><strong>Screen Size</strong></td><td>1920 x 1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920 x 987</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></table>

**Comment by abishekvashok** [comment]
I would work on it

**Comment by PolBaladas** [comment]
Hey, similar to https://github.com/fossasia/gci16.fossasia.org/issues/358 @m1guelpf @Abhi2424shek

**Comment by abishekvashok** [comment]
Yes that why i said i would work @PolBaladas

**Comment by codein-dwij** [comment]
I would also love to wok on it :) I have a codein task

**Comment by m1guelpf** [comment]
@PolBaladas Not so similar... This issue is more complete, as it also includes the image issue.

**Comment by abishekvashok** [comment]
@m1guelpf images shall be resized and names shall also be fit into...

**Comment by ankitrgadiya** [comment]
The image is not in 1:1 ratio as required.

**Comment by abishekvashok** [comment]
please see PR #416
