### ISSUE TITLE
Blog section is not showing photos.

### ISSUE THREAD

**Issue by ankitrgadiya** [fossasia/gci16.fossasia.org#400]
We're all adding photos for blogs but its not showing on site.

**Comment by champforevaa** [comment]
Yes. I have noticed the same issue.

**Comment by ankitrgadiya** [comment]
I'll work on it once the building issue is resolved

**Comment by abishekvashok** [comment]
@ankitrgadiya building issue has been resolved so you can start your work :)

**Comment by ankitrgadiya** [comment]
Yep working on it

**Comment by jigyasa-grover** [comment]
Closed via PR https://github.com/fossasia/gci16.fossasia.org/pull/418
