### ISSUE TITLE
No Squashing any more :)

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/gci16.fossasia.org#402]
Hi, I just saw something:

![capture](https://cloud.githubusercontent.com/assets/564768/21076358/7f6e7c10-bf29-11e6-9600-57e9afd169cf.PNG)

@fossasia/gci16-maintainers @jig08 I think, they do not need to squash after all.

**Comment by niccokunzmann** [comment]
Just creating this issue to inform you.

**Comment by niccokunzmann** [comment]
Please close if you feel infomed.

**Comment by niccokunzmann** [comment]
Also, I recognized a button - I do not know who can see it:

![capture](https://cloud.githubusercontent.com/assets/564768/21076448/c0c4183a-bf2b-11e6-9b59-765e995d2187.PNG)

Maybe that is the way to go for new people.

**Comment by codethejason** [comment]
I personally know the option is there, but I think the point of having the PR people squashing their commits is for practice and Git knowledge.

**Comment by abishekvashok** [comment]
I too knew about squashing and merging commits cause i had write access when the competition has started, I also recommended this to a lot of mentors but theu failed to know of it, this way we could help new members and help them out. While after we could offer them tutorials they could either look or not look at them let it be their choice. They would learn it in the coarse of time. @niccokunzmann i am not seeing that button. I am not having write access. This is the way to go for new people surely.

**Comment by jigyasa-grover** [comment]
>I personally know the option is there, but I think the point of having the PR people squashing their commits is for practice and Git knowledge.

++

**Comment by animeshsinghweb** [comment]
That's great, but it can sometimes be overwhelming for students to completely understand rebasing in quick span of time, and hence if there is no merge conflict and if students need help squashing, this can be a great option @niccokunzmann  :)

**Comment by m1guelpf** [comment]
@niccokunzmann I shared that a few days ago, but mentors told me that squashing was a great practice

**Comment by m1guelpf** [comment]
@niccokunzmann Maybe we should add this to mantainers.md, as some emntors are merging unsquashed PRs, and this may be the solution to that.

**Comment by jigyasa-grover** [comment]
@m1guelpf Update `mantainers.md` accordingly.
Either the student should squash the commits into one, or the mentors should `squash & merge` before committing into the main repo.

**Comment by m1guelpf** [comment]
@niccokunzmann I opened an issue on the Danger repo asking how to get number of commits. The idea is to warn the user and/or mentor. Waiting for their response...

**Comment by m1guelpf** [comment]
@jig08 Updated mantainers.md and left there this issue for info. I think this can be closed...
