### ISSUE TITLE
Map and Flickr Zooms in as I scroll down

### ISSUE THREAD

**Issue by rhemon** [fossasia/gci16.fossasia.org#405]
If its possible I think it would be good if we change how we zoom in in the map and flickr. Every time I slowly scroll down, when its on top of map/flickr it zooms in, which can be very annoying to users.

**Comment by sudo-panda** [comment]
Yes it is. Can I work on it?

**Comment by jigyasa-grover** [comment]
Sure, go ahead.

**Comment by sudo-panda** [comment]
Can you give me the link to flickr embed api documentation.

**Comment by jigyasa-grover** [comment]
[blog.flickr.net/2013/12/18/flickr-web-embeds](http://blog.flickr.net/2013/12/18/flickr-web-embeds/) this ?

Code Snippet: [gci16.fossasia.org/gh-pages/index.html#L406-L409](https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/index.html#L406-L409)

**Comment by jigyasa-grover** [comment]
Copy of Issue #365 , follow up there please :)

**Comment by sudo-panda** [comment]
No I meant like this https://developers.google.com/maps/documentation/geolocation/intro if there is one.
Also I could not find the css or javascript linked to flickr embed.

**Comment by abishekvashok** [comment]
Since this is a copy of issue #365 closing this...
