### ISSUE TITLE
Making coala auto applying patches

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/gci16.fossasia.org#414]
We don't want our code to be bad so we have introduced travis CI tests with coala bears to check them and report. However, we have recent findings that tests are irritating new users and are forcing them to leave the arena of FOSSASIA. We can't ignore both, we want good code and happy contributors for our society so I put forward the concept of making coala to auto apply the patches, this is form the coala documentation:

> Often you don’t want to look at trivial results like spacing issues. For that purpose coala includes a special setting called default_actions that allows you to set the action for a bear that shall be automatically applied on run. We have a command line alias --apply-patches to make it easier to use.

@jig08 @hemantjadon @niccokunzmann @Princu7 @fossasia/gci16-maintainers can I add this functionality, this would both improve our code and also lead to more happy contributors :) What are your opinions hall I proceed with it.

**Comment by hemantjadon** [comment]
Well @Abhi2424shek seems a good idea, I think you should proceed. I have few concerns though but let's see what you come up with :)

**Comment by Princu7** [comment]
Seems like a fine idea. Let us proceed and see how it turns out.

**Comment by abishekvashok** [comment]
@hemantjadon what are your concerns... :)

**Comment by m1guelpf** [comment]
@Abhi2424shek So, then we have to setup a way to make Coala push back to the repo...

**Comment by abishekvashok** [comment]
@m1guelpf yes after script to push back the changes on.

**Comment by abishekvashok** [comment]
so shall we do this.

**Comment by hemantjadon** [comment]
@Abhi2424shek you start working on this and we will follow you up there as PR progresses.
Also you might want to test it on some other repository (Test) so thant we can safely test.

**Comment by abishekvashok** [comment]
K @hemantjadon let me try it on my fork...

**Comment by abishekvashok** [comment]
@hemantjadon @Princu7 @niccokunzmann @jig08 

Got the solution see the screen shot:
![image](https://cloud.githubusercontent.com/assets/8947010/21293457/72363920-c54b-11e6-8d30-ca1f1b25d2e7.png)

Now travis auto applies coala patches to the repository.
This will lead us to a state where code quality is automatically fixed and we will get more happy contributors just like we all want.

I used my own account for the test but we would require another account with some access.
I got the scripts ready and would deliver in a PR but that would be a work in progress as I will leave the username and password as <username> and <password>. Please give an account soon.

Please see PR #599

**Comment by abishekvashok** [comment]
We could close this after PR #599 is merged.

**Comment by abishekvashok** [comment]
![image](https://cloud.githubusercontent.com/assets/8947010/21343411/93acc2b4-c6bc-11e6-91db-4f74e0f9d48a.png)
Working, Closing
