### ISSUE TITLE
Add logo from #277

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/gci16.fossasia.org#419]
In #277 there is a logo as a comment.
Please help to show this logo on the FOSSASIA page, so it does not get lost.

**Comment by abishekvashok** [comment]
@niccokunzmann  Should we start a new PR or inform @Melo5154 to update it.

**Comment by ashwini0529** [comment]
Hey. Can I take this issue?

**Comment by jigyasa-grover** [comment]
@ashwini0529 Yes, dont forget to refer issue number in your commit.
@Abhi2424shek yes pls, direct the PR to this issue and close it for the time being :)

**Comment by ashwini0529** [comment]
So what basically needs to be done?

**Comment by jigyasa-grover** [comment]
Utilise the logo in comments section of PR #277  & add it to the website following instructions provided in [gci16.fossasia.org#adding-logos](https://github.com/fossasia/gci16.fossasia.org#adding-logos)

**Comment by ashwini0529** [comment]
@jig08 In `author` what should come?

**Comment by ashwini0529** [comment]
Also, as per the guidelines, the name should match with the `logo` file name.
But it is not practiced over there.

**Comment by jigyasa-grover** [comment]
Give due credits to `Melo5154`

**Comment by ashwini0529** [comment]
Alright!
