### ISSUE TITLE
Broken Image link for student Tan Ngo Minh

### ISSUE THREAD

**Issue by jigyasa-grover** [fossasia/gci16.fossasia.org#422]
Broken Image link for student `Tan Ngo Minh`.

Refer screenshot attached.
<img width="1280" alt="screen shot 2016-12-11 at 2 39 54 pm" src="https://cloud.githubusercontent.com/assets/9291400/21079196/d0bcb754-bfaf-11e6-8d1b-261a27f4f9e2.png">

**Comment by ankitrgadiya** [comment]
I noticed that earlier, he/she forgot to upload image and he/she not in slack so How to fix that?
I can replace it with a different image if you want.

**Comment by prabhdeep29** [comment]
I got his image and im fixing the issue

**Comment by jigyasa-grover** [comment]
@prabhdeep29  Thanks.
@ankitrgadiya We could design a template for default images or simply take their Github avatar :)

**Comment by prabhdeep29** [comment]
Issue fixed

**Comment by prabhdeep29** [comment]
![screen shot 2016-12-11 at 3 56 40 pm](https://cloud.githubusercontent.com/assets/16387636/21079532/7c1f25e6-bfba-11e6-809b-c507919db96a.png)
Here is a screenshot

**Comment by jigyasa-grover** [comment]
Thanks !
