### ISSUE TITLE
Wrong padding on the <p> at .logos images when hovered

### ISSUE THREAD

**Issue by animeshsinghweb** [fossasia/gci16.fossasia.org#425]
The p tag should have more padding for the logo images.
Look at the image:
![newissue](https://cloud.githubusercontent.com/assets/16618931/21079619/edbc38ea-bfbc-11e6-8cfd-f2b8840a9331.png)

If you can assign the issue to me, I can fix it within a moment.
Thanks.

**Comment by oanarosca** [comment]
Go ahead! :)

**Comment by abishekvashok** [comment]
Sure @animeshsinghweb

**Comment by animeshsinghweb** [comment]
@Abhi2424shek it is @animeshsinghweb BTW :)
Thanks.

**Comment by abishekvashok** [comment]
Sorry bro

**Comment by animeshsinghweb** [comment]
Fixed by https://github.com/fossasia/gci16.fossasia.org/pull/427
Thanks.
