### ISSUE TITLE
There is an abrupt overflow y in the grids of students

### ISSUE THREAD

**Issue by animeshsinghweb** [fossasia/gci16.fossasia.org#428]
The overflow below the grid is destroying the UX.

Have a look:
![newissue](https://cloud.githubusercontent.com/assets/16618931/21079693/a96ebd0e-bfbf-11e6-8484-f9faa573b241.png)

If assigned, I can try fixing within a couple of minute.
Thanks.

**Comment by oanarosca** [comment]
That was added for longer names, what do you plan to do with overflowing ones?

**Comment by abishekvashok** [comment]
Yes what are you planning to do mate @animeshsinghweb

**Comment by animeshsinghweb** [comment]
We can either short the name of the person in the students.yml for restricting their name to initials (for longer names), as we have their image and their Github/social link there would not be any kind of problems in the differentiating them. 
A bad initiative would be to reduce the font-size of h2 element, which I don't want to do for just a few big names.

After either of this process, we can change the `overflow` to **hidden**.
Believe me, this is just killing the UI and UX.

We would even 'add' a **note** in README.md to use initials if they have long names.

And after that we can use .logos images grid styling for the students-projects grid.

What do you say @oanarosca @Abhi2424shek ?

**Comment by abishekvashok** [comment]
@animeshsinghweb resizeing the font size would be a problem, and also making short names won't help either, what we could do is make the scroll bar look more good. Can you do that. Some sites have this implemented.

**Comment by abishekvashok** [comment]
The proposed initiative won't help because if we modify the scroll here you would have to modify all other sections in the site except the blog section.

**Comment by animeshsinghweb** [comment]
I know to design scroll bar, but the problem is -moz- doesn't accept it. It is widely accepted by chrome itself.

**Comment by animeshsinghweb** [comment]
The best initiative is to shorten their name and use only their initiative names.
For example: We can use A.V.Ashok if you don't mind (just example).
If I have name such as: Animesh Prasad Singh, I don't have any problem using Animesh P. Singh or just Animesh Singh.

What do you think @Abhi2424shek mate?

**Comment by oanarosca** [comment]
In my opinion, I think it's best to add to README that initials should be used, and for the long names we got now, maybe shorten them with ... and add a ```title``` tag to them, so that on hover, the whole name will appear.

**Comment by abishekvashok** [comment]
You can do it with JavaScript there are cross browser solutions @animeshsinghweb :)

**Comment by abishekvashok** [comment]
@oanarosca that would be nice if we could make text-overflow ellipsis and then on hover displays the complete name but on hover of the p has been tied up to another animation so that may lead to bad results

**Comment by animeshsinghweb** [comment]
@oanarosca you gave an addon to my suggestion, that's best.
We can use that, for people having longer name we can add a new property in yml, i.e. `full-name:` and we can use them as title or as an abr to the `name:` when hovered. And for rest people we would just duplicate their names in `full-name` and can inform them via **README.md**.
What do you say @Abhi2424shek?

**Comment by oanarosca** [comment]
@Abhi2424shek that's not a problem. A ```title``` tag needs no javascript, it's all html. It's a lesser known html attribute, but it comes in handy here!

**Comment by abishekvashok** [comment]
@oanarosca then try it, :) @animeshsinghweb proceed bro.

**Comment by animeshsinghweb** [comment]
Yes instead of 'title' we can even use an abbr tag for that, have a look here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/abbr

As title can be a better attribute of 'abbr' as @oanarosca says.

So, can I try doing that?

**Comment by jigyasa-grover** [comment]
@animeshsinghweb Pls post relevant mock-ups before you go ahead with the implementations.

**Comment by animeshsinghweb** [comment]
Yes @jig08 wait let me show you by trying in Inspect Element though. :)

**Comment by oanarosca** [comment]
@animeshsinghweb that would be good, but as @Abhi2424shek suggested, ```text-overflow: ellipsis``` solves that problem and automatically shows dots. Your idea of adding a new field is good, but for newcomers, I feel it's easier if there are fewer fields to complete :) Yes! the abbr thing is good!

**Comment by animeshsinghweb** [comment]
Look here, is it suiting the process?

**Before**

![image](https://cloud.githubusercontent.com/assets/16618931/21079845/77ca5902-bfc4-11e6-8a3c-d2692a854d40.png)

**After**

![newissue](https://cloud.githubusercontent.com/assets/16618931/21079858/ed94589a-bfc4-11e6-8903-14df03fe6491.png)


We can use that, for people having a longer name we can add a new property in yml, i.e. `full-name:` and we can use them as a title or as an abbr to the `name:` when hovered. And for rest people, we would just duplicate their names in `full-name` and can inform them via **README.md**.

Is this process acceptable?
Let me know @jig08 @oanarosca @Abhi2424shek 
Thanks.

**Comment by abishekvashok** [comment]
@animeshsinghweb don't add a new field that would make our lives miserable try to gow ith ellipsis and title.

**Comment by animeshsinghweb** [comment]
Resolved via : 
https://github.com/fossasia/gci16.fossasia.org/pull/441
Hence, closing this.
Thanks friends.
