### ISSUE TITLE
Slider about CodeHeat not displayed properly - PR #432

### ISSUE THREAD

**Issue by nikhilchandak** [fossasia/gci16.fossasia.org#434]
I made a pull request to add a slider containing a image of almost the same size as the previous ones and the with text regarding 'CodeHeat'. The PR got merged but no text is being displayed and the image is also too zoomed in. 
Please help. 
Thanks.

**Comment by Princu7** [comment]
@nikhilchandak If you like, then please work on it. Thanks.

**Comment by nikhilchandak** [comment]
@Princu7 Thanks for the kind reply. I am new to github, so can you please tell where I could I find a url to the website of the forked repo to see the changes ?

**Comment by Princu7** [comment]
@nikhilchandak No problem. Well, the live gh-pages are usually of the form {yourname}.github.io/{reponame} so in this case it should be
http://nikhilchandak.github.io/gci16.fossasia.org

**Comment by jigyasa-grover** [comment]
@Abhi2424shek @oanarosca @PolBaladas @m1guelpf @rhemon  input pls.

**Comment by abishekvashok** [comment]
Checking @jig08
