### ISSUE TITLE
Blog post images not showing up

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/gci16.fossasia.org#435]
The images of the blog posts do not show up.
![capture](https://cloud.githubusercontent.com/assets/564768/21080082/06173a78-bfa6-11e6-8607-58eef53743d7.PNG)

http://gci16.fossasia.org/#

**Comment by Princu7** [comment]
@niccokunzmann This issue is being resolved by the PR #418 by @ankitrgadiya.

**Comment by myfrom** [comment]
Could be my mistake, check line 227 of index.html

**Comment by jigyasa-grover** [comment]
@niccokunzmann Latest update, follows up on Issue #443 , closing this hence.
