### ISSUE TITLE
Fix flickr photo zoom on scroll.

### ISSUE THREAD

**Issue by sudo-panda** [fossasia/gci16.fossasia.org#440]
Even though it seems to have been solved ( #365  ) for scrolling down but it is still there for scrolling up.
Also even though the photo doesn't zoom in when scrolling down, the website doesn't scroll down.

**Comment by abishekvashok** [comment]
@Baidya work on it then will you :)

**Comment by sudo-panda** [comment]
Okay.
Can you assign me?

**Comment by abishekvashok** [comment]
Happy :) ?

**Comment by jigyasa-grover** [comment]
Seems to be fixed, closing this.

**Comment by sudo-panda** [comment]
It is not fixed.
