### ISSUE TITLE
[urgent] "Blogs" section is a mess

### ISSUE THREAD

**Issue by jigyasa-grover** [fossasia/gci16.fossasia.org#443]
Please fix it at the earliest !

<img width="1280" alt="screen shot 2016-12-11 at 7 11 13 pm" src="https://cloud.githubusercontent.com/assets/9291400/21080570/5fc0830e-bfd8-11e6-849e-07414cbcc2ef.png">

**Comment by myfrom** [comment]
It works on my devices, what browser do you use?

**Comment by jig08** [comment]
Few uncovered points still, refer screenshot attached.

<img width="1280" alt="screen shot 2016-12-11 at 8 11 44 pm" src="https://cloud.githubusercontent.com/assets/9291400/21080790/2071f204-bfde-11e6-8efb-fb2bc10ede13.png">

**Comment by Witus13** [comment]
Also when image is mostly white, the text is unreadable
