### ISSUE TITLE
Improve Page Load time

### ISSUE THREAD

**Issue by DeeprajPandey** [fossasia/gci16.fossasia.org#448]
The page now takes upwards of 10 seconds to load. As a first step towards reducing the load time, I am adding the async attribute to <script></script> tags in html files. Will work on optimising the images available and thinking of adding information about optimising images before uploading them to the repository in the README file for new students/contributors.

**Comment by m1guelpf** [comment]
Just optimized images at #451

**Comment by DeeprajPandey** [comment]
Thanks!
FInished working on index.htm and the css files. Submitting PR soon

**Comment by simonnarang** [comment]
^ I did some more things for this

**Comment by ankitrgadiya** [comment]
It has improved after #458
