### ISSUE TITLE
More tasks

### ISSUE THREAD

**Issue by m1guelpf** [fossasia/gci16.fossasia.org#453]
@fossasia/fossasia-gci We need more ideas for GCI tasks related to this website!

**Comment by william1835** [comment]
I agree, I can't find anything within my capabilities!

**Comment by ankitrgadiya** [comment]
Yeah I'm interested in working on this site

**Comment by prabhdeep29** [comment]
I got some Ideas. We can have tasks like - 
1. Setting up lolak: Setup lokal and use it for the first time.
2. A blog post about experience with using lolak.
3. Add a new slider to the GCI website.
4. Create a small DOS based game in C++.
5. Create a small game in any language.
6. Make a video about adding stuff to GCI website through Github.
7. Create a new Fossasia website and make a repository for the website.

I hope these suggestions help you in some way. Trying to fix this issue for a GCI task. Task instance - https://codein.withgoogle.com/dashboard/task-instances/5471329681670144/

**Comment by robbyoconnor** [comment]
A large majority of those ideas aren't related to the site at all...in addition you didn't do the task correctly.

**Comment by m1guelpf** [comment]
Locked as this is a discussion for mentors and mantainers.

**Comment by m1guelpf** [comment]
I suggest a task to add project to the projects section, as it seems empty.
What do you think?
ping @jig08 @fossasia/fossasia-gci

**Comment by codein-dwij** [comment]
Yes.. The project section is really kind of empty.

**Comment by jigyasa-grover** [comment]
@m1guelpf Sure, this sounds good. Thanks :)

**Comment by hemantjadon** [comment]
@m1guelpf Hi, Actually this is something not related to new feature but existing ones. I also don't know whether these will even classify as tasks but an overall improvement of site.

* The application load time is exceptionally slow. [25sec approx] (First load is even slower)[~1min]

* Size of application is huge (>10mb)

* No caching mechanisim (requierd as a lot of media resources are present)

* Scroll jank

* Social media scripts take a lot of time to render. 

* Steep initial learning curve for new comers (Jekyll/ Travis/ Coala)

I don't know that how these can be formed as tasks but these are things which needed to be addressed whether as tasks or as issues.

[Edit]

70+ MB. I guess this size issue needs to me addressed.

![screen shot 2016-12-12 at 9 39 48 pm](https://cloud.githubusercontent.com/assets/11755543/21106359/cfb18876-c0b3-11e6-8aa2-1217d05e3e6b.png)

**Comment by m1guelpf** [comment]
@hemantjadon @jig08 Can you create tasks?

**Comment by jigyasa-grover** [comment]
@m1guelpf Created for `students projects` section, shall be up soon :)

**Comment by m1guelpf** [comment]
@jig08 Could you share the task link?
I've scrolled trought all FOSSASIA tasks and can't find it.

**Comment by rhemon** [comment]
it would be also good if there were tasks for adding proper bio for each student & mentor since now info are displayed with popup, a proper bio would make it look useful and full :P

**Comment by m1guelpf** [comment]
@jig08 Could you share the task link?
I've scrolled trought all FOSSASIA tasks and can't find it.

**Comment by abishekvashok** [comment]
Are having the discussion live it's not been active so what should this issue's status then guys.?

**Comment by Elgayar** [comment]
The mentors could add tasks as learning something new and doing a basic application on it.
For example, Learn Laravel and create a simple blog from scratch.

And all these apps could be added to the student's projects section of the gci16 website.

**Comment by robbyoconnor** [comment]
@fossasia/fossasia-gci What's your take on @Elgayar's suggestion?

**Comment by abishekvashok** [comment]
I accept it thumbs up.

**Comment by jigyasa-grover** [comment]
We had tasks like these last season @Elgayar , but this time we are focussing on using the student contributions to improvise the existing FOSSASIA projects. Cheers !

**Comment by abishekvashok** [comment]
Any more suggestions???
