### ISSUE TITLE
MDByn logos don't display correctly on mobile

### ISSUE THREAD

**Issue by myfrom** [fossasia/gci16.fossasia.org#454]
Images are squashed in small viewport. Refer to screenshot
![screenshot_20161211-194352](https://cloud.githubusercontent.com/assets/19410489/21082375/8a52497a-bfda-11e6-9521-bbe303040f1e.png)

**Comment by wingsylver** [comment]
Can I do this?

**Comment by abishekvashok** [comment]
Sure

**Comment by abishekvashok** [comment]
Now it looks fine, @Witus13 @william1835 fixed it for good. So closing this.
