### ISSUE TITLE
Blogs are still broken

### ISSUE THREAD

**Issue by myfrom** [fossasia/gci16.fossasia.org#455]
Refer to screenshot 
![screenshot_20161211-194831](https://cloud.githubusercontent.com/assets/19410489/21082413/4262d700-bfdb-11e6-9c6b-eeb479141914.png)

Chrome Beta 55

**Comment by simonnarang** [comment]
I am looking into this... Feel free to assign to me

**Comment by jigyasa-grover** [comment]
@simonnarang Unable to assign you, have you joined the FOSSASIA Github GCI team ?

**Comment by ghost** [comment]
Please can I work on this task

**Comment by codein-dwij** [comment]
Yes you can :)

**Comment by simonnarang** [comment]
@codein-dwij No I haven't, how should I so so?

**Comment by ankitrgadiya** [comment]
I fixed it #458

**Comment by codein-dwij** [comment]
@simonnarang Sorry, what do you want to do?

**Comment by codein-dwij** [comment]
Fixed :)
