### ISSUE TITLE
Travis CI not activated. 

### ISSUE THREAD

**Issue by darshil** [fossasia/gci16.fossasia.org#46]
A repository has not yet been created on Travis Cl. An admin is needed to perform this action.
![capture](https://cloud.githubusercontent.com/assets/12867510/20775846/0de5a7cc-b72b-11e6-960c-13c695a59523.PNG)

More information: https://travis-ci.org/fossasia/gci16.fossasia.org

**Comment by tradzik** [comment]
I have turned it on. Thanks for letting me know.
