### ISSUE TITLE
UI Improvements to be made.

### ISSUE THREAD

**Issue by dannymout** [fossasia/gci16.fossasia.org#465]
So, I made an issue talking about inconsistencies in the UI, since then there have been some improvements, and I've looked for more issues. Here is a list of them:

- [x] Blog Post section title needs to match the style of the other sections (title pops out of the top of the box.)
- [x] MBDyn Logos section title needs to match the style of the other sections (title pops out of the top of the box.)
- [x] The "See all issues on GitHub" button should be on the bottom of the section, not on the top.
- [x] Social media section should have a box around it, like the other sections.
- [x] The MBDyn logos in the boxes should be displayed at their proper aspect ratio.
- [x] In the blog post section, the text on top of the cards should be moved underneath for better visibility, like the other sections.
- [x] In the MBDyn logos section, the names of the creators should be moved underneath and should have a material design type card design like the other sections.
- [x] The title of the MBDyn logos section needs to be h2, not h1, like the other section titles.
- [x] The title of the Social media section needs to be h2, not h1, like the other section titles.
- [x] The names on the cards in the students section have slightly more padding on the top than the bottom.
- [x] Padding/margin of the "See all issues on GitHub" button on the left is different than the padding/margin on the left of `.issues-category`
- [x] The icons in the footer under Fossasia Links, are black and should be white to match the typography.
- [x] There should be higher resolution icons for the social media section in the footer, the Fossasia logo, and the "Fork me on GitHub" ribbon for higher res. Retina displays for devices like Macs. [Retina.js](https://imulus.github.io/retinajs/) might be able to help with that.

**Comment by abishekvashok** [comment]
Would you like to work on @dannymount

**Comment by dannymout** [comment]
@Abhi2424shek Yes, I might be working on a few of these tasks.

**Comment by abishekvashok** [comment]
I've assigned you @dannymout but other could also help out, as there are more tasks so if anyone is interested comment and I will assign you too! 😊👍

**Comment by kartikhsr** [comment]
@Abhi2424shek i would like to fix these issues if you assign me too, although i have a basic knowledge but i will try to fix them

**Comment by abishekvashok** [comment]
@kartikhsr go for it.

**Comment by kartikhsr** [comment]
@Abhi2424shek ohky sir thank you..!!

**Comment by abishekvashok** [comment]
No need to call me sir ;)

**Comment by myfrom** [comment]
Can I work on social media section or am I too late?

**Comment by jigyasa-grover** [comment]
@Witus13 It still needs improvement, so go ahead :)

**Comment by kartikhsr** [comment]
is this fine with blog posts poping up

**Comment by kartikhsr** [comment]
![Uploading Screenshot from 2016-12-12 13-04-13.png…]()

**Comment by kartikhsr** [comment]
![screenshot from 2016-12-12 13-04-13](https://cloud.githubusercontent.com/assets/22699153/21091371/b99d22d6-c06b-11e6-96ee-0fc0ae6dfb2e.png)
is it fine @jig08 done blog posts popping up

**Comment by myfrom** [comment]
@kartikhsr Make the background colour match the background of header

**Comment by codein-dwij** [comment]
I wanna work on the issues. Please assign me too!

**Comment by myfrom** [comment]
Maybe let's discuss who is working on what or we'll end up doing the same.
@dannymount @codein-dwij @kartikhsr

I'm taking social media section, OK?

**Comment by kartikhsr** [comment]
@Witus13 work on social media

**Comment by ankitrgadiya** [comment]
* Blog Post section title needs to match the style of the other sections (title pops out of the top of the box.)
* MBDyn Logos section title needs to match the style of the other sections (title pops out of the top of the box.)
* The MBDyn logos in the boxes should be displayed at their proper aspect ratio.
* In the blog post section, the text on top of the cards should be moved underneath for better visibility, like the other sections.
* In the MBDyn logos section, the names of the creators should be moved underneath and should have a material design type card design like the other sections.
* The title of the MBDyn logos section needs to be h2, not h1, like the other section titles.
* The title of the Social media section needs to be h2, not h1, like the other section titles.

Fixed  #458

**Comment by codein-dwij** [comment]
I have updated the issues which are merged (or completed)

**Comment by abishekvashok** [comment]
@codein-dwij nice

**Comment by codein-dwij** [comment]
There are still some left to be completed

**Comment by abishekvashok** [comment]
@dannymout we could still go for improvements in blogs section, so let's uncheck it.

**Comment by kartikhsr** [comment]
@Abhi2424shek any issue which can be assigned to me ?

**Comment by Princu7** [comment]
@kartikhsr Any ones which you would like to work on?

**Comment by abishekvashok** [comment]
Which one would you want bro @kartikhsr

**Comment by kartikhsr** [comment]
@Abhi2424shek actually i am a learner .... learning github too just 1 day old i am .... after learning github i will try to resolve issue

**Comment by kartikhsr** [comment]
@Abhi2424shek can we catch on slack ? if you can help me ? my username : kartikhsr85

**Comment by kartikhsr** [comment]
@Princu7 @Abhi2424shek @codein-dwij blogpost,mbdyn logos header have still some errors i think ? can i get the sample as like to be made for mbdyn,blogpost header...?

**Comment by codein-dwij** [comment]
Point no. 1,2 and 6 are completed ( Someone had removed it)
The blog and MBDyn having matching styles with the other sections(now it doesn't need to pop out)
and the text in blog section is moved underneath

**Comment by kartikhsr** [comment]
point no 3
![screenshot from 2016-12-14 21-33-40](https://cloud.githubusercontent.com/assets/22699153/21189538/09235ade-c245-11e6-9c52-a5571ee673b4.png)
is it fine?
@codein-dwij @Abhi2424shek @Princu7 @ankitrgadiya 
point no 12
![screenshot from 2016-12-14 21-48-45](https://cloud.githubusercontent.com/assets/22699153/21190230/257fa028-c247-11e6-816c-8284c183402f.png)

**Comment by abishekvashok** [comment]
@codein-dwij the blog needs more improvement

**Comment by animeshsinghweb** [comment]
@kartikhsr Point no. 3 LGTM. Your PR?

**Comment by codein-dwij** [comment]
@Abhi2424shek Please tell what more you want :)
@kartikhsr Looks Good! Please provide a PR
@animeshsinghweb :P what's LGTM?

**Comment by animeshsinghweb** [comment]
@codein-dwij LGTM = Looks Good To Me. 👍 you can try www.giyf.com

**Comment by ankitrgadiya** [comment]
@kartikhsr you picked it quite nicely. I'd like to see PR. Thanks for contribution Happy Coding

**Comment by kartikhsr** [comment]
@ ankitrgadiya @animeshsinghweb @codein-dwij i am making pr now

**Comment by ankitrgadiya** [comment]
@kartikhsr That's cool. Don't forget to mention this issue(part of issue) there. :-)

`LOL we both asked the same thing at same time.` - ❤️ @animeshsinghweb

**Comment by animeshsinghweb** [comment]
@kartikhsr make sure to refer the issue and point number you worked on with the live gh-page.

**Comment by ankitrgadiya** [comment]
I think Point 4 "Social Media section should have a box around it" is fixed.

**Comment by kartikhsr** [comment]
@ankitrgadiya yeah done point 4

**Comment by ankitrgadiya** [comment]
12 Point or 2<sup>nd</sup> last point is also fixed.

**Comment by kartikhsr** [comment]
@ankitrgadiya @animeshsinghweb 
check point 10
![screenshot from 2016-12-14 22-19-29](https://cloud.githubusercontent.com/assets/22699153/21191549/7b1257ca-c24b-11e6-84fd-9951ec26a4e3.png)

**Comment by ankitrgadiya** [comment]
@kartikhsr it seems like 10 point is fixed as well. Thanks for pointing it out.

**Comment by kartikhsr** [comment]
@ankitrgadiya actually i have to make a pr for it....it is on my local repo point 10  ... i was showing you the sample

**Comment by animeshsinghweb** [comment]
@kartikhsr I guess you need to add some extra space of `padding-left` and `padding-right` as well because it can be awkward for students with bigger names. Do PR and refer the issue with point you fixed.

**Comment by kartikhsr** [comment]
@animeshsinghweb 
![screenshot from 2016-12-14 22-31-17](https://cloud.githubusercontent.com/assets/22699153/21192017/16db16f0-c24d-11e6-9a1d-f3e7e86a98e5.png)
using padding-left, padding-right will lead to this

**Comment by ankitrgadiya** [comment]
@kartikhsr  Sorry I misread the point. sorry sorry.

**Comment by kartikhsr** [comment]
@animeshsinghweb @m1guelpf point 13, we have to deploy retina.min.js or import retinajs NPM in ourrepository , will it be feasible solution to do so, if yes then i can proceed with the issue

**Comment by animeshsinghweb** [comment]
@kartikhsr Sure you can go ahead and try. We would see if that doesn't cause any problem.

**Comment by kartikhsr** [comment]
@animeshsinghweb i have done it, but how will i feel the difference between normal image and after using retina.js ?

**Comment by dannymout** [comment]
@kartikhsr The difference will be that on Retina devices or a device with a higher res screen, the higher res graphics will be used.

**Comment by animeshsinghweb** [comment]
@dannymout I think all the issues are fixed now so we can close this. Or is there anything left/missing?

**Comment by abishekvashok** [comment]
@animeshsinghweb yes the site looks good now is'nt it @dannymout, if you want you could open a new issue with what all other improvements you find wanted so closing this now!
