### ISSUE TITLE
Not all contributors are showing up

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/gci16.fossasia.org#472]
In the contributors' section, it seems like only the people merging pull-requests show up.
![capture](https://cloud.githubusercontent.com/assets/564768/21090822/a5a4b4fc-c042-11e6-9e7a-908acc87c3ef.PNG)
I would like that everyone who contributed is shown.

**Comment by abishekvashok** [comment]
@niccokunzmann its the top contributors who pop up here, even before I had write access i was there.

**Comment by simonnarang** [comment]
should probably close this now

**Comment by niccokunzmann** [comment]
This would be a lot of people to display, I think, we could use a random collection of contributors and those with most contributions are shown with some higher probability.

**Comment by abishekvashok** [comment]
It is as it is the people who commit more than 4 commits are currently shown

**Comment by hoangvanthien** [comment]
This is because when we get contributors via GitHub API, we only get data on page 1. I also want all contributors seen on the page. Let me try if I can fix this.

**Comment by jigyasa-grover** [comment]
@hoangvanthien Sweet, assigned you this task.

**Comment by Hesham-Burawi** [comment]
@hoangvanthien Do you want some help this seems like something I can try?
