### ISSUE TITLE
MBDyn logos don't display correctly.

### ISSUE THREAD

**Issue by sudo-panda** [fossasia/gci16.fossasia.org#477]
![capture](https://cloud.githubusercontent.com/assets/16690760/21096123/8fff107e-c084-11e6-8dc1-5199fb9ec445.PNG)

**Comment by sudo-panda** [comment]
I would like to work on this

**Comment by rhemon** [comment]
can you describe what is this issue about? what is it that you want to change?

**Comment by codein-dwij** [comment]
Was having the same question since you posted the issue.

**Comment by rhemon** [comment]
is that picture your fixed version?

**Comment by m1guelpf** [comment]
ping @Baidya99

**Comment by codein-dwij** [comment]
http://prntscr.com/difh4z

I don't find any problem here

**Comment by animeshsinghweb** [comment]
@Baidya99 Can you elaborate what do you find wrong in the issue?

**Comment by ankitrgadiya** [comment]
I fixed the aspect ratio #458
