### ISSUE TITLE
Three MBDyn logos missing on the website

### ISSUE THREAD

**Issue by louisgag** [fossasia/gci16.fossasia.org#478]
These three logos made by students for the gci16 were not added to the website (two of the students showed difficulties, and were passed after having tried a few times to push) and the other student abandoned the task.

This issue/task is thus to add the three of them, along with the student names, to the MBDyn logos section.
See pull request by Lee Care Gene to get an idea of how to proceed: https://github.com/fossasia/gci16.fossasia.org/commit/4603dad1470669ccacafeb3382b9fa7527c114a1

prabhdeep_singh:
![prabhdeep_singh_small](https://cloud.githubusercontent.com/assets/12291709/21097011/cf7b309c-c062-11e6-903e-8c9dad7c2865.png)

alexandru_nasta:
![alexandru_nasta_small](https://cloud.githubusercontent.com/assets/12291709/21097036/ea532e2e-c062-11e6-9cc8-90a5c956db44.png)

dannymout:
![dannymout](https://cloud.githubusercontent.com/assets/12291709/21097042/f02b38e6-c062-11e6-8fab-3385d4b1bd23.png)

Regards,

-Louis

**Comment by sudo-panda** [comment]
I would like to work on this.

**Comment by codein-dwij** [comment]
Go ahead and work on it. It seems you are not Fossasia team member so I can't assign you.

**Comment by sudo-panda** [comment]
How do I become a member?

**Comment by louisgag** [comment]
I think you can work on the task and submit a pull request even if you're not a member..

**Comment by oanarosca** [comment]
You can work on this even without being a member, but here's the link for joining the team: http://fossasia.org/apply-pupils

**Comment by codein-dwij** [comment]
Yes he can work on the issue without being a member.

**Comment by sudo-panda** [comment]
@oanarosca I have already submitted the form.

**Comment by codein-dwij** [comment]
I will work on this ( but will take some 24 hrs)
If someone else wants to do, do the number 2 and 3. I will do the first one

**Comment by prabhdeep29** [comment]
im doing it

**Comment by prabhdeep29** [comment]
I did it

**Comment by prabhdeep29** [comment]
Link to pull request - https://github.com/fossasia/gci16.fossasia.org/pull/490

**Comment by animeshsinghweb** [comment]
@louisgag Is the task removed from GCI? I just made a logo for MBDyn (https://animeshsinghweb.github.io/gci16.fossasia.org/) but I can't claim the task.

Here is my PR: https://github.com/fossasia/gci16.fossasia.org/pull/491

Thanks.

**Comment by prabhdeep29** [comment]
@animeshsinghweb Yes the task was removed

**Comment by animeshsinghweb** [comment]
@prabhdeep29, any reasons?
I made the logo and updated in the gci16,fossasia.org though, but was unable to claim it.
Any help would be appreciated. Thanks.

**Comment by louisgag** [comment]
there were 10 instances of the task and the last one is currently block for another 10 hours or so by a student who claimed it and has not yet submitted anything...

**Comment by prabhdeep29** [comment]
@animeshsinghweb This may be because the task might have reached its deadline and no mentor increased the time i guess

**Comment by prabhdeep29** [comment]
@louisgag Well that throws my theory outta the window :)

**Comment by prabhdeep29** [comment]
@louisgag Can you merge the pull request #490 to fix this current logo issue??

**Comment by animeshsinghweb** [comment]
@louisgag So, will that be available after 10 hours? Let me know the link, thanks.

**Comment by louisgag** [comment]
@prabhdeep29 I think you have to fix the issue pointed out by @m1guelpf first
@animeshsinghweb in theory you are not supposed to work on tasks before claiming them, but the link will be the same as before...

**Comment by animeshsinghweb** [comment]
@louisgag Thanks for making that point clear. 👍  I would take care. :)

**Comment by animeshsinghweb** [comment]
@louisgag Check the PR #493 with https://animeshsinghweb.github.io/gci16.fossasia.org/

**Comment by sudo-panda** [comment]
@louisgag can you merge any one of the three commits given by the three of us, please.
