### ISSUE TITLE
Percy: Visual diff

### ISSUE THREAD

**Issue by m1guelpf** [fossasia/gci16.fossasia.org#488]
In my last PR, I implemented Percy.
To make it work well, you need to add the Percy integration to this repo.
Thank you!
ping @jig08

**Comment by hemantjadon** [comment]
@m1guelpf Percy seems to be a great 👍

**Comment by m1guelpf** [comment]
@hemantjadon Thank you!
I found it in the changelog nightly newsletter and thought in this repo.

**Comment by jigyasa-grover** [comment]
>To make it work well, you need to add the Percy integration to this repo.

@m1guelpf walk me through the required steps..

**Comment by m1guelpf** [comment]
@jig08 Settings -> Integrations -> Add -> Percy

**Comment by Abhi2424shek** [comment]
@jig08 i also wanted to ask you whether we have build pushes enabled in this repo.

**Comment by jigyasa-grover** [comment]
@mariobehling , could you please ? Seems like I don't have enough rights.

**Comment by m1guelpf** [comment]
@hemantjadon @jig08 @mariobehling Any updates on this?

**Comment by Abhi2424shek** [comment]
@m1guelpf @mariobehling would help you keep calm...
