### ISSUE TITLE
Please maintain aspect ratio when reducing dimensions of images

### ISSUE THREAD

**Issue by sudo-panda** [fossasia/gci16.fossasia.org#495]
My logo was originally
![mbdyn2](https://cloud.githubusercontent.com/assets/16690760/21110855/f2ee55ba-c0c4-11e6-8db0-15b75911fb47.png)

but now it looks like this:
![capture](https://cloud.githubusercontent.com/assets/16690760/21110909/31b42216-c0c5-11e6-9f3f-8b3139c64169.PNG)

**Comment by animeshsinghweb** [comment]
@Baidya99 This is your job. :) 
Read the instructions at the logo section of **README.md** carefully!
That dimension was reduced for better UX and overcome grid issues at #256 :)

**Comment by ankitrgadiya** [comment]
@Baidya99 I fixed it no worries #458

**Comment by codein-dwij** [comment]
Fixed :)
