### ISSUE TITLE
Loklak API Tweets not loading

### ISSUE THREAD

**Issue by gaeun** [fossasia/gci16.fossasia.org#500]
The loklak API section on the website worked well until yesterday, but currently the tweets are not loading.
@niccokunzmann This might be because https://loklak.quelltext.eu/ is down... If not, any ideas on how to fix this? The javascript files seem fine to me.

**Comment by simonnarang** [comment]
Maybe get the tweets directly from twitter API?

**Comment by abishekvashok** [comment]
Let me look after it @gaeun

**Comment by gaeun** [comment]
@Abhi2424shek What's the plan?

**Comment by niccokunzmann** [comment]
I restarted the server, can you check back?

**Comment by gaeun** [comment]
@niccokunzmann I think the website still isn't loading :(

**Comment by niccokunzmann** [comment]
I created an issue for a JavaScript which chooses among loklak instances. https://github.com/loklak/loklak_server/issues/888

**Comment by niccokunzmann** [comment]
Maybe we can create such a script here and give it to loklak.

**Comment by abishekvashok** [comment]
@niccokunzmann a model mini project of our community which has loklak tweets gets the tweets correctly let me check the code... @gaeun i think i got the solution would do a PR.
