### ISSUE TITLE
Latest Issues Section Broken

### ISSUE THREAD

**Issue by ankitrgadiya** [fossasia/gci16.fossasia.org#505]
Due to my latest Pull Request, Latest Issue Section broke.

**Comment by animeshsinghweb** [comment]
@ankitrgadiya I can't understand can you elaborate the issue with references?

**Comment by jigyasa-grover** [comment]
Seems fine, closing this for now.

**Comment by animeshsinghweb** [comment]
@ankitrgadiya I'd fixed that in my PR: #510. 👍

**Comment by ankitrgadiya** [comment]
@animeshsinghweb Thanks Its fixed now.
