### ISSUE TITLE
Awkward Design of Projects>Latest Issues

### ISSUE THREAD

**Issue by pipix51** [fossasia/gci16.fossasia.org#511]
The Latest Issues section in the webpage does not look streamlined with the overall design, with the tags having different alignments.

**Comment by gaeun** [comment]
I can work on this if that's ok.

**Comment by gaeun** [comment]
It seems like this issue is fixed now.

**Comment by ankitrgadiya** [comment]
Its fixed now, I think we can close the issue now.

**Comment by animeshsinghweb** [comment]
Yeah, it was fixed through my PR #510
