### ISSUE TITLE
Mentors are not showing up on the map!

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/gci16.fossasia.org#528]
@Princu7 you added it right but we can't see you in:
![image](https://cloud.githubusercontent.com/assets/8947010/21178029/acc35b3a-c213-11e6-8049-4fe2243d12f4.png)
@BrainBuzzer any guesses bro

**Comment by Princu7** [comment]
@Abhi2424shek Yeah. I was discussing this problem with Robby Sir. No markers are being shown on the map. Let's look for the bug.

**Comment by abishekvashok** [comment]
@Princu7 sure going through the code now...

**Comment by abishekvashok** [comment]
@Princu7 got the problem, the yml reader based on js reads a file at _data/mentors.yml which cannot be accessed with http protocol online on the website as jekyll hides them down...

I got the solution

**Comment by BrainBuzzer** [comment]
Most of the times it was happening to me. The page is being cached and hence it does not get updated. As I go in incognito mode, it shows all the markers.

**Comment by abishekvashok** [comment]
@BrainBuzzer I don't get it while going to incognito mode either, because the file _data/mentors.yml cannot be handled over the internet protocol and will be hid by jekyll.

**Comment by animeshsinghweb** [comment]
@BrainBuzzer even I can't find it on incognito mode either as @Abhi2424shek said.

**Comment by abishekvashok** [comment]
@animeshsinghweb its a javascript error as I stated above the file cant be handled externally.

**Comment by animeshsinghweb** [comment]
@Abhi2424shek I saw that. I was just reading our new commit https://github.com/Abhi2424shek/gci16.fossasia.org/commit/22f4a2dd55902628d54c08d8b021655874df3edf 👍

**Comment by abishekvashok** [comment]
It can be closed after my PR is merged @Princu7 @animeshsinghweb @BrainBuzzer #536 
Update: it's merged!
Preview:
![image](https://cloud.githubusercontent.com/assets/8947010/21190743/e11c8822-c248-11e6-9511-e116acb6ea48.png)
