### ISSUE TITLE
Fix multiple UX and UI issues at Footer and Social Media Section

### ISSUE THREAD

**Issue by animeshsinghweb** [fossasia/gci16.fossasia.org#534]
Here are the lists of modifications regarding UI and UX,

**First of all a glimpse of current version:**
![image](https://cloud.githubusercontent.com/assets/16618931/21183201/cf7428e4-c22c-11e6-9a4c-92d668feb1d6.png)

**Here are the modifications I would like to propose/work on**

- A container wrapper for footer-sec
- Replace the media images with relative social media `fa-icons`.
- Remove the `bulleted` version of the `<ul>` on the **Links** sections and give the `fa`s proper colour
- Improve the margin and padding of the wrapper
- Give some more custom styling to the copyright section at the bottom
- Maybe much more which I may resolve at the time.

**Comment by kartikhsr** [comment]
![screenshot from 2016-12-15 00-38-48](https://cloud.githubusercontent.com/assets/22699153/21196760/dff364a0-c25e-11e6-83b4-74230ad21f67.png)
@animeshsinghweb These kind of icons might work ?

**Comment by kartikhsr** [comment]
![screenshot from 2016-12-15 00-44-51](https://cloud.githubusercontent.com/assets/22699153/21196969/b79934fc-c25f-11e6-80da-56f71e4b7f84.png)
does this look bit decent ?
@codein-dwij @animeshsinghweb

**Comment by kartikhsr** [comment]
@animeshsinghweb does this look nice ?
![screenshot from 2016-12-15 00-57-00](https://cloud.githubusercontent.com/assets/22699153/21197431/70669bd6-c261-11e6-8bbd-c08206f4e524.png)
i need to change color only now

**Comment by kartikhsr** [comment]
@codein-dwij please have a look above

**Comment by m1guelpf** [comment]
@kartikhsr Awesome!

**Comment by kartikhsr** [comment]
@m1guelpf can you suggest me somr changes, or shall i make PR

**Comment by animeshsinghweb** [comment]
Yes, you can do PR, and refer the issue with the points you solved. 👍

**Comment by kartikhsr** [comment]
@animeshsinghweb i think we can close this issue

**Comment by animeshsinghweb** [comment]
Point number 1, 5 and 6 resolved on PR #555 👍
