### ISSUE TITLE
Use background-size: cover on blog post images

### ISSUE THREAD

**Issue by myfrom** [fossasia/gci16.fossasia.org#535]
This would resolve the problem of squashing images

**Comment by animeshsinghweb** [comment]
@Witus13, I didn't find any problem with the images at the blog posts, can you please elaborate your issue to some extent, and provide images if possible.
Thanks.

**Comment by myfrom** [comment]
Take your one as an example: [Original image](http://gci16.fossasia.org/images/blogs/animeshsinghweb.jpg), Rendered image:
![screenshot 2016-12-14 at 16 51 46](https://cloud.githubusercontent.com/assets/19410489/21189055/b13dd528-c21d-11e6-8b5a-cd0709b49ab2.png)

**Comment by animeshsinghweb** [comment]
@Witus13 So, you want to work on this issue?

**Comment by myfrom** [comment]
@animeshsinghweb Yup

**Comment by animeshsinghweb** [comment]
@Witus13 Go ahead mate. :D
Do Refer this Issue when you request PR. :)

**Comment by abishekvashok** [comment]
@Witus I prefer you make the images a bit more small so the UI would match that of the other sections :) or we could provide another PR... The blogs are ruining the look of the site.

**Comment by myfrom** [comment]
@Abhi2424shek I don't have much time today... Maybe let's merge that one to don't cause conflicts and I'll submit another one tomorrow, ok?

**Comment by abishekvashok** [comment]
@Witus13 sure

**Comment by myfrom** [comment]
Main issue is fixed, I'm moving discussion about changing size of cards to #546
