### ISSUE TITLE
Resize Picture "images/students/zahari.jpg"

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/gci16.fossasia.org#545]
The picture [images/students/zahari.jpg](https://raw.githubusercontent.com/fossasia/gci16.fossasia.org/0965c0e8e430d77397067dd0718769db6d65ccff/images/students/zahari.jpg) is skewed.
We can resize it, so it is in the 240x240 dimensions.

**Comment by m1guelpf** [comment]
@niccokunzmann I could do it, but now I'm not at home. If this can wait, I'd do it later.

**Comment by niccokunzmann** [comment]
@m1guelpf I think, it is too easy for you :)

**Comment by niccokunzmann** [comment]
Closed by #544

**Comment by animeshsinghweb** [comment]
@niccokunzmann Is the image resized to 240x240?

**Comment by niccokunzmann** [comment]
Uh no, it is 800x800

**Comment by animeshsinghweb** [comment]
@niccokunzmann Yes, not yet resized. :D

**Comment by kartikhsr** [comment]
@niccokunzmann @animeshsinghweb i have resized it, shall i make a PR?

**Comment by animeshsinghweb** [comment]
@kartikhsr Sure,

**Comment by m1guelpf** [comment]
Done
