### ISSUE TITLE
Should we make blogs cards smaller?

### ISSUE THREAD

**Issue by myfrom** [fossasia/gci16.fossasia.org#546]
We certainly should add media query to CSS because cards are too big in phone viewport and I'll work on it. But should we make the cards match the size of other sections' cards also on desktop? Since people say the actual size brakes the design but other say it is good as blogs provide more information than name cards and need more space.

**Comment by animeshsinghweb** [comment]
Yes, @Witus13 I guess you may trying using `@media` queries for the mobile viewport. I agree that on mobile large blogs card are not appealing to UX.

**Comment by myfrom** [comment]
@animeshsinghweb but what do you think about changing the size of those cards in all viewports. To make them look like other section cards?

**Comment by animeshsinghweb** [comment]
@Witus13 I guess it must **not** look like other section cards. I would like them to look to be larger than the other cards. Maybe you can try 'col-md-4' and see how it looks with 3 grids in a row.

**Comment by myfrom** [comment]
@animeshsinghweb OK, I'll go with media query now and then I'll make some demos to see what's better

**Comment by animeshsinghweb** [comment]
@Witus13 Sure, also do asks for suggestion or review here when you had finished the task and ready for PR. 👍

**Comment by myfrom** [comment]
How about making them look like [this](https://witus13.github.io/gci16.fossasia.org/#blogs)?

**Comment by animeshsinghweb** [comment]
@Witus13 I guess this was the previous design of the blogs, but it changed I guess due to few people disliking this; though I didn't have any problem.
The thing that I can suggest is:
- Move the truncated desc. such that it appears inside `img` container when hovered over that particular img. (The truncated text yet doesn't have any `spam title` class which would show the complete desc when hovered over them, look `students cards` for example.)

**Comment by abishekvashok** [comment]
Since @Witus13 has done a good work in his PR lets close this, can we @animeshsinghweb or should we improve it more.

**Comment by animeshsinghweb** [comment]
@Abhi2424shek Yes, I guess since the topic was of making the blog cards smaller in mobile devices.
@Witus13 you can open up a new issue for it (updating UX for blogs) and use the suggestion I made/or ask people for their opinion, and then we can improve upon it there more.

**Comment by Witus13** [comment]
@Abhi2424shek Well, I thought about changing the look of the blog cards also on bigger screens, not only fixing it on mobile. We're discussing what can make them look better

**Comment by animeshsinghweb** [comment]
@Witus13 anyways, you can open a new issue for that, and we can discuss further on that. 👍

**Comment by myfrom** [comment]
Ok, I'll leave it as it is now. 
One thing - I'm boy, not girl. Everyone thinks I'm a girl, lol.

**Comment by abishekvashok** [comment]
@Witus13 ok bro

**Comment by animeshsinghweb** [comment]
@Witus13 I don't consider you as a girl, though. Com'on ;)
