### ISSUE TITLE
Problem with bio of some student/s 

### ISSUE THREAD

**Issue by codein-dwij** [fossasia/gci16.fossasia.org#554]
There are some students who have kept a lengthy bio! 
![screenshot_3](https://cloud.githubusercontent.com/assets/16368363/21226504/c94e0d34-c2fb-11e6-9431-997a9e9af416.png)
This should be fixed :)
If anyone wants to work on this issue please tell!

**Comment by kartikhsr** [comment]
@codein-dwij is there only need of moving this box little above right?

**Comment by rhemon** [comment]
we could keep it as overflow:hidden and then on hover it would rise

**Comment by codein-dwij** [comment]
You decide what you want to do...Maybe make it such that bio exceeding certain characters will be cut short just like name of students in students section or move the box a little above.

**Comment by kartikhsr** [comment]
@rhemon  what if we add margin-top: -()px?
@codein-dwij decreasing font-size will also work

**Comment by rhemon** [comment]
you can do it in any way you are comfortable

**Comment by rhemon** [comment]
and about decreasing font size. make sure not to get it too small.

**Comment by codein-dwij** [comment]
Font size is already small so making it more small wouldn't help! 
The best is to cut the lengthy bios

**Comment by kartikhsr** [comment]
![screenshot from 2016-12-15 19-38-14](https://cloud.githubusercontent.com/assets/22699153/21227003/0e9f09ae-c2fe-11e6-8b89-87c0941172de.png)
@rhemon @codein-dwij

**Comment by animeshsinghweb** [comment]
@ankitrgadiya Suggesting you to update your bio, LOL 👍

**Comment by rhemon** [comment]
seems fine to me

**Comment by kartikhsr** [comment]
@ankitrgadiya haha ultimate , i have not uploaded yet for this reason =D

**Comment by kartikhsr** [comment]
@rhemon Shall i PR?

**Comment by animeshsinghweb** [comment]
@kartikhsr go ahead, and refer the issue. 👍

**Comment by codein-dwij** [comment]
Decreased font size? there is one drawback : if someone new makes another lengthy bio the issue will come again

**Comment by animeshsinghweb** [comment]
@codein-dwij Should we update our **Readme.md**, providing instructions to add/update the bio with 50-70 character limits?

**Comment by codein-dwij** [comment]
Thats also a good way :)

**Comment by codein-dwij** [comment]
@kartikhsr go ahead and make the PR(and refer this issue)

**Comment by codein-dwij** [comment]
http://prntscr.com/djrl2i http://prntscr.com/djrlbj http://prntscr.com/djrlif
3 more people with such bios (including @rhemon :P

**Comment by kartikhsr** [comment]
@codein-dwij https://kartikhsr.github.io/gci16.fossasia.org/ see live link

**Comment by codein-dwij** [comment]
Its solving the issue :)

**Comment by animeshsinghweb** [comment]
@codein-dwij  
![image](https://cloud.githubusercontent.com/assets/16618931/21227609/c3e60bf8-c300-11e6-9343-7cba732e4add.png)

@kartikhsr This is from your live link your provided.

**Comment by codein-dwij** [comment]
me?

**Comment by animeshsinghweb** [comment]
@codein-dwij  I pointed @kartikhsr in the last line.

**Comment by codein-dwij** [comment]
hmm I see it fixed! PLease reload and check again :)

**Comment by rhemon** [comment]
its a good idea to have instructions  on readme. for now we can go with that

what if we centre the text vertically as well?  pushing the social links
top. not sure abt this

also abt font size maybe it would be a good idea to follow material design?

**Comment by kartikhsr** [comment]
![screenshot from 2016-12-15 20-03-39](https://cloud.githubusercontent.com/assets/22699153/21227864/a1b60014-c301-11e6-854c-d6d8e2e8f4d5.png)
in my browser it is fixed @animeshsinghweb

**Comment by animeshsinghweb** [comment]
Ok,
@kartikhsr I was viewing your site's cache.
Anyway I had suggested you some changes in your PR.

**Comment by rhemon** [comment]
btw what if we dont doo anything like thay  rather we only show one line of
bio ending with '... ' . and then on click we show a pop up window with all
details.

we could also do this by linking a different page. this should be easy with
jekyll

**Comment by rhemon** [comment]
do* that*

**Comment by animeshsinghweb** [comment]
@rhemon I guess pushing the social links a little upward to just adjust a text for _few peoples_ would be unfare,

**Comment by rhemon** [comment]
i dont know. we dont really need all that padding on top. but no problem. we could try the pop window thing/page ?

**Comment by animeshsinghweb** [comment]
@rhemon I guess this would make the stuff more complex, we don't need those. If you are thinking of using JS here, it can be a little tiresome with Jekyll.
Anyways if you think you can work on it then go ahead.

> btw what if we dont doo anything like thay  rather we only show one line of
> bio ending with '... ' . and then on click we show a pop up window with all
> details.
> 
> we could also do this by linking a different page. this should be easy with
> jekyll

**Comment by rhemon** [comment]
that would be cool too have not only for students but mentors as well. in that part we could also include blog info, student project if they have any

**Comment by animeshsinghweb** [comment]
@rhemon You can go ahead and work on it and let's see how the thing go. 👍

**Comment by codein-dwij** [comment]
Well such thing should be a part of another issue and not this one :) @rhemon can you create a new issue?

**Comment by rhemon** [comment]
ok will create an issue later on. presently away from home so cant work now. will do it once I get back

**Comment by codein-dwij** [comment]
Fixed! Closing This...
