### ISSUE TITLE
Pop up window/Pages for mentors and students

### ISSUE THREAD

**Issue by rhemon** [fossasia/gci16.fossasia.org#558]
After looking at the issues for too much text in bio, and there were also similar issues of having some parts too big. I was thinking if  if we have all the sections (student/mentor/blog)  link to a page or some kind of pop up that would display all the detailed information -  I guess its going to be a profile for everyone. all data can be taken from existing students.yml, blog.yml, mentors.yml and all those other files.

What do you think?

**Comment by animeshsinghweb** [comment]
@rhemon If you would like to do make a sample on it, and then we can give our opinions. Remember not to make things too complicated.

**Comment by codein-dwij** [comment]
@rhemon would you like working on it? You haven't stated that..

**Comment by rhemon** [comment]
yeah will start today

**Comment by abishekvashok** [comment]
Give us a popup

**Comment by rhemon** [comment]
yeah i am working on popup. hope its not a problem if I am a bit slow (plan
to finish by sunday)

**Comment by abishekvashok** [comment]
No bro take your own time, @rhemon

**Comment by abishekvashok** [comment]
@rhemon nice job but I can't see popup for mentors

**Comment by rhemon** [comment]
@Abhi2424shek it is showing up for me on click. can you check my version again?

**Comment by abishekvashok** [comment]
@rhemon wait...

**Comment by abishekvashok** [comment]
@rhemon sorry I had to refresh the cache, now it's working nice job.

**Comment by abishekvashok** [comment]
@rhemon nice work bro since it's merged closing this....
