### ISSUE TITLE
Travis build fails

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/gci16.fossasia.org#566]
Why does [the current travis build](https://travis-ci.org/fossasia/gci16.fossasia.org/builds/184473563) fail? 

Error:
```
/home/travis/.rvm/gems/ruby-2.3.3/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:143:in `parse': 
(/home/travis/build/fossasia/gci16.fossasia.org/_data/logosv2.yml): 
did not find expected '-' indicator while parsing a block collection at line 2 column 1 (Psych::SyntaxError)
```

But if I look at the [file](https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/_data/logosv2.yml), I see this:

```

- author: Nguyen Chanh Dai
  img: NguyenChanhDai.svg
```

Where is the problem? How can we fix travis?

**Comment by m1guelpf** [comment]
@niccokunzmann I'll have a look

**Comment by animeshsinghweb** [comment]
@niccokunzmann Maybe due to extra line in the beginning?

**Comment by niccokunzmann** [comment]
Cool, this error is removed now. https://travis-ci.org/fossasia/gci16.fossasia.org/builds/184477402
