### ISSUE TITLE
Code Quality: Fix some error.

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/gci16.fossasia.org#570]
The [build](https://travis-ci.org/fossasia/gci16.fossasia.org/builds/184477402#L454) shows a long list of errors we have.

In each file shown as
```
|----|    | /app/stylesheets/main.css
|    |++++| /app/stylesheets/main.css
```
There is a problem in a line (here 128):
```
| 128|    |-	margin-left:-7px;
```
And a possible solution:
```
|    | 128|+    margin-left:-7px;
```

We can go through the list and fix some of them.

**Comment by abishekvashok** [comment]
sure @niccokunzmann I was about to open an issue regarding the same...

**Comment by abishekvashok** [comment]
@niccokunzmann it's done with my new PR so closing this on your behalf and asking whether can we integrate codeacy to the website to get code coverage data
