### ISSUE TITLE
Can we have a sitemap.xml for this site

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/gci16.fossasia.org#571]
> A site map (or sitemap) is a list of pages of a web site accessible to crawlers or users. It can be either a document in any form used as a planning tool for Web design, or a Web page that lists the pages on a website, typically organized in hierarchical fashion.

 This would improve our points in google search and more google crawlers will index the site what is your opinion guys,

**Comment by m1guelpf** [comment]
@Abhi2424shek We only have one page, so I don't think we need this.
Anyway, do it if you want

**Comment by abishekvashok** [comment]
but @m1guelpf we have images, a lot of images...

**Comment by m1guelpf** [comment]
@Abhi2424shek You don't add images to a sitemap

**Comment by abishekvashok** [comment]
@m1guelpf yes we do, not only images but also videos have place in a sitemap.xml file

**Comment by abishekvashok** [comment]
Since none of you are wanting it let's close this :) ;)
