### ISSUE TITLE
Geolocation can't be served from insecure orgins

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/gci16.fossasia.org#583]
Google just shut out more features for `http` protocol including geo location api, so we must either:

- **Move the geo page to a separate github repo so it will be served over `https://` protocol**
- **Add an ssl certificate to our official site by using github or other means**

Your opinions please.
Ping @fossasia/gci16-maintainers 
**...**

**Comment by niccokunzmann** [comment]
Can you provide a link, so I can reproduce the problem?

**Comment by abishekvashok** [comment]
Sure sir,

@niccokunzmann this is our error:
![image](https://cloud.githubusercontent.com/assets/8947010/21285660/db2b3620-c464-11e6-99ca-299bb9c6e4a4.png)

See the explanation for it here: https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins

As I said above we have two solutions which one should we go for :thinking: 💭

**Comment by niccokunzmann** [comment]
Github provides https: https://niccokunzmann.github.io
Also for sub-projects: https://fossasia.github.io/flappy-svg/
I tried https://fossasia.github.io/gci16.fossasia.org/geo but it redirected me.

Thus, I conclude, we can create a new repository and redirect to that from http://gci16.fossasia.org/geo
If anyone likes to do that, please step ahead.

**Comment by abishekvashok** [comment]
@niccokunzmann no you can't try https:// to achieve https protocol go to settings and turn on https sir :)

However, that would have an effect on loklak, as loklak is served via http and rules state that only https contents be delivered from https sites.

**Comment by niccokunzmann** [comment]
![image](https://cloud.githubusercontent.com/assets/564768/21285743/d6d5c216-c441-11e6-8eee-101bed077cf3.png) from https://github.com/fossasia/gci16.fossasia.org/settings
HTTPS cannot be turned on on this site.

**Comment by abishekvashok** [comment]
@niccokunzmann k so will our community host the code in a new repo or should I make a new repo.

**Comment by niccokunzmann** [comment]
I will ask in the mentors' chat for someone to create the repository.

**Comment by abishekvashok** [comment]
@niccokunzmann k that will be great after the repo is created we will ship the code from here to there, simple as that :)

**Comment by ankitrgadiya** [comment]
@Abhi2424shek @niccokunzmann Its working for me.
![screenshot from 2016-12-17 18-59-26](https://cloud.githubusercontent.com/assets/18071765/21287140/f2b3c8a4-c48a-11e6-8995-bf7efb457fab.png)

**Comment by m1guelpf** [comment]
@Abhi2424shek @niccokunzmann The only way I know for setting up ssl on custom github pages domains is to use Cloudflare. If you want, I can donate geo.miguelpiedrafita.com for a new repo.

**Comment by abishekvashok** [comment]
No need github does that for us, thanks for your willingness. On gh-pages such as the links niccokunzmann posted we have aal by default. So no worries :) 👍

**Comment by abishekvashok** [comment]
@niccokunzmann whats the progress, we need to move quickly 😊😺🎅🏃👣👟💎

**Comment by niccokunzmann** [comment]
@Abhi2424shek until now, I can not create repositories, it would be ok to host it somewhere else and then fork it here later.

**Comment by abishekvashok** [comment]
@niccokunzmann I would create a github repository under my name and we'd move once someone like sir @mariobehling would create a new repository for us and move there, won't you @mariobehling sir.

Please give me some time as I am working with coala now please...

**Comment by niccokunzmann** [comment]
@Abhi2424shek It is open for everyone to solve. I will not assign it to you. The more easy tasks we have, the more people contribute.

**Comment by abishekvashok** [comment]
@niccokunzmann sure I will keep aloof then :) let's flag it as beginners

**Comment by niccokunzmann** [comment]
@Abhi2424shek I am closing this, so the description is smaller. You can edit #618 if you like to add something.
