### ISSUE TITLE
Travis is not working

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/gci16.fossasia.org#585]
Travis is not working at all, this would give us severe bad effects, We need to first identify the problem and deliver the solution it's extra urgent!

Here are the logs of travis it ran only 14 hours before and stopped thereafter!
![image](https://cloud.githubusercontent.com/assets/8947010/21285112/926436b2-c455-11e6-98a5-3e752377c4ae.png)

![image](https://cloud.githubusercontent.com/assets/8947010/21285110/85535318-c455-11e6-9c69-31f0b7641b46.png)

**Comment by shubham-padia** [comment]
Looks to me it was caused by #499 . Someone rewrote in JSON format. @Abhi2424shek Are you willing to work on this

**Comment by abishekvashok** [comment]
@shubham-padia if you want me on this I am happy to help, I would give in a PR now itself then :)

**Comment by abishekvashok** [comment]
@shubham-padia my latest PR did'nt help...

**Comment by shubham-padia** [comment]
@Abhi2424shek Looks like there are some issues with the yml you commited. Reverting it to this version :
https://github.com/fossasia/gci16.fossasia.org/blob/1f7d95afab246b3f09ed0cbb696f6ffd0ba7287f/.travis.yml
will do to fix the issue.
open another PR for the same.
