### ISSUE TITLE
Add caching to CI to make it faster

### ISSUE THREAD

**Issue by yukiisbored** [fossasia/gci16.fossasia.org#603]
Travis has a feature to cache files, it can be used to make the process faster

**Comment by abishekvashok** [comment]
@yukiisbored it is already added see the travis.yml file :) and see the line `cache: bundler` please check the code next time. Since, we have already implemented it closing this...

**Comment by yukiisbored** [comment]
Hello, there's still room for improvement. `cache: bundler` only caches the downloaded ruby gems that are used for dependencies. coala has caching so why not cache that as well.

**Comment by codein-dwij** [comment]
@yukiisbored Would you work on it?

**Comment by yukiisbored** [comment]
@codein-dwij Thanks, but I'm more interested with other things. I think it's nice to have someone else do it so they can have an experience with travis and docker.

**Comment by abishekvashok** [comment]
coala has caching by default and we did'not disable it so closing this....

**Comment by yukiisbored** [comment]
@Abhi2424shek I meant cache the cached data generated from coala with Travis. Travis has it's own caching system. Not to mention the other ways you can cache and make CI faster. Please don't close the issue without having a good reason. Since, caching is not just a single road, it can be improved in the future.

**Comment by jayvdb** [comment]
@Abhi2424shek , the coala caching is deleted when the CI job and its virtual machine  is terminated. Voodoo is needed to save the cached files and restore them in the next build.

**Comment by abishekvashok** [comment]
@jayvdb then we will workout with voodoo, I ask sorry for closing this really sorry!

**Comment by abishekvashok** [comment]
@jayvdb can you create an issue to use Voodoo
