### ISSUE TITLE
Use waving octocat for fork me on github

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/gci16.fossasia.org#605]
There is a much nicer banner for the github link, a waving octocat.
This can be used instead of "forkme on github"

Example: http://hpimakerklub.github.io/

![image](https://cloud.githubusercontent.com/assets/564768/21296681/bb5f4d96-c571-11e6-9cb5-5fb6a5f862c6.png)

**Comment by robbyoconnor** [comment]
:+1:

**Comment by m1guelpf** [comment]
@niccokunzmann Please make a PR

**Comment by abishekvashok** [comment]
@niccokunzmann we could make it beginner only

**Comment by Elgayar** [comment]
Pull Request Merged.
