### ISSUE TITLE
Create issues on responsive design

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/gci16.fossasia.org#606]
For a Laptop page, this site is almost perfect. However, mobile first design would be nice, so that it works on smartphones and tablets.

Please test the Website on your smartphone or tablet and note down errors you see.
Also, you can use the responsive design view of firefox:

![image](https://cloud.githubusercontent.com/assets/564768/21296712/468b1ecc-c572-11e6-86e9-3171b4d57ebe.png)

Please create more issues for that.

Issues related to this topic : #625

**Comment by myfrom** [comment]
Maybe for now let's use 
````
body {
    width: 100vw;
    overflow-y: hidden;
}
````
It would make the website look better at cost of cutting some margin from social section (cards there are too wide)

**Comment by abishekvashok** [comment]
@Witus13 wanna work at it.

**Comment by myfrom** [comment]
@Abhi2424shek I can do something with the social section

**Comment by abishekvashok** [comment]
@Witus13 which issue

**Comment by myfrom** [comment]
@Abhi2424shek #625

**Comment by jigyasa-grover** [comment]
@Witus13 Status of this pls ?

**Comment by myfrom** [comment]
@jig08 #625 closed, social media section no longer brakes the ux on mobile

Buy I noticed that text "Thanks for contribution ..." Is not optimised for smaller viewports

**Comment by jigyasa-grover** [comment]
@Witus13 modify it accordingly pls ?

**Comment by myfrom** [comment]
@jig08 I'm currently working on another issue and I have never touched this text before and don't want to break it. @ankitrgadiya worked on it before, maybe he'll take it?

**Comment by ankitrgadiya** [comment]
@jig08  @Witus13 Let me see what I can do about "Thanks for Contribution".

**Comment by abishekvashok** [comment]
@Witus13 @ankitrgadiya status please...

**Comment by myfrom** [comment]
@Abhi2424shek still some small improvements, I'll submit issues later today

**Comment by ankitrgadiya** [comment]
@Abhi2424shek Thanks Contributors is fixed here #759

**Comment by abishekvashok** [comment]
So we need the rest fixed... We can have an issue even this issue states to do so... Let me create one with lots of check boxes...

**Comment by myfrom** [comment]
@Abhi2424shek There are a lot of problems, but happily they're not so big
#796 #795 #794 #792

**Comment by abishekvashok** [comment]
Wed just keep this open.
