### ISSUE TITLE
Move Geolocations to other repository

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/gci16.fossasia.org#618]
The geo-locations can be found here: http://gci16.fossasia.org - which is not able to work because it must use HTTPS. A solution, see #583 is to move the content from 
http://gci16.fossasia.org to https://github.com/fossasia/geolocation
And redirect to it.

So, please

- [x] create a pull-request to https://github.com/fossasia/geolocation with the current content of the geo folder
- [x] redirect from /geo to https://github.com/fossasia/geolocation

**Comment by sudo-panda** [comment]
@niccokunzmann I would like to try this.

**Comment by niccokunzmann** [comment]
Sure! Please go ahead.

**Comment by sudo-panda** [comment]
@niccokunzmann could you please tell me how to upload to the geolocation repo as I am unable to fork it as there is no code in it. Or you could add an empty .txt file.

**Comment by niccokunzmann** [comment]
@Baidya99 I uploaded something.

**Comment by sudo-panda** [comment]
@niccokunzmann thankyou.

**Comment by abishekvashok** [comment]
@niccokunzmann @Baidya99 it's resolved right? Hurray!

**Comment by niccokunzmann** [comment]
The redirect is not there, yet: http://gci16.fossasia.org/geo/

**Comment by sudo-panda** [comment]
I am working on it.

**Comment by sudo-panda** [comment]
Will post the PR any minute.

**Comment by abishekvashok** [comment]
@niccokunzmann sorry for that sincerely sir sorry :)
@Baidya99 keep up the good work.

**Comment by niccokunzmann** [comment]
@Abhi2424shek No problem, really.

**Comment by abishekvashok** [comment]
@niccokunzmann :)

**Comment by niccokunzmann** [comment]
redirect is done!
