### ISSUE TITLE
Use IntersectionObserver to lazy-load social media section

### ISSUE THREAD

**Issue by myfrom** [fossasia/gci16.fossasia.org#626]
No one or really small amount of people go to the social media section of our website right after the page loads. However, this section is loading and brings some junk to the page. I think making a progressive enhancement - in browsers supporting IntersectionObserver API social widgets will load when the users scrolls down to social media section. Other browsers will load it as they are now. I'll make a demo soon.

**Comment by abishekvashok** [comment]
@Witus13 load them only onscroll would help us. You could get the user's scroll position too, here is a cross browser api.

**Comment by myfrom** [comment]
@Abhi2424shek I know onscroll but IntersectionObserver's are faster, using onscroll would bring junk that we are trying to remove. Onscroll fires every time user scrolls the page while IO runs callback when the element enters viewport

**Comment by abishekvashok** [comment]
@Witus13 it's not onscroll listener I am mentioning of but of getting the scroll position,
for reference: https://plainjs.com/javascript/styles/get-and-set-scroll-position-of-an-element-26/

**Comment by myfrom** [comment]
@Abhi2424shek yep, but you still need a way to know when users scrolls through that threshold

**Comment by codein-dwij** [comment]
Will you work on this @Witus13 ?

**Comment by myfrom** [comment]
@codein-dwij I'm going to but first I need to work on #625

**Comment by abishekvashok** [comment]
@Witus13 check that link again it gives a lot of explanation to solve the problem. If you want more info please ping me on slack.
