### ISSUE TITLE
Beginners: Adding/Fixing Bio of Mentors and Students

### ISSUE THREAD

**Issue by codein-dwij** [fossasia/gci16.fossasia.org#630]
Now we have a good pop up window for students and mentors put up by @rhemon . But there is a lack of bio for the mentors. Try getting the bio of each and every mentor so that it looks good.

You can also improve the bio of other students if you want to!

This issue is for the beginners who have recently joined FOSSASIA organization so let them work on this! 

EDIT:
If you want to know the bio of mentors(or student) ask them in Slack or Gitter. More info on how to join in contributing.md

**Comment by codein-dwij** [comment]
Remember: This is an ISSUE for BEGINNERS!

**Comment by abishekvashok** [comment]
To get the bio of each mentor try to ask them via slack or gitter.

**Comment by abishekvashok** [comment]
Can we have a task for it @niccokunzmann @jig08 no beginner is claiming it.

**Comment by ankitrgadiya** [comment]
Existing data for students is fixed for typos #780.

**Comment by abishekvashok** [comment]
That's reverted @ankitrgadiya

**Comment by ankitrgadiya** [comment]
Yeah, so what do we do now? Do you want me to fix or we'll have to wait till some beginner fix it.?

**Comment by abishekvashok** [comment]
The bio is almost ok @ankitrgadiya let's wait for some beginners to claim it...

**Comment by abishekvashok** [comment]
To fix the rest

**Comment by robbyoconnor** [comment]
With regards to mentor profiles: **_DO NOT_** write a bio from their linkedin profile -- Talk to them!

**Comment by robbyoconnor** [comment]
I reverted #780 because it didn't fix typos -- in fact it introduced grammatical errors and did other things that shouldn't have happened as changing `FOSS` to `FOSSASIA` -- people meant FOSS.

**Comment by robbyoconnor** [comment]
You have to actually look at each change made here -- and if it doesn't fix the problem, or does something that's doesn't make sense...don't merge it. Optimistic merging is great, except when you wind up putting words in people's mouth in their bios...

**Comment by abishekvashok** [comment]
It almost looks ok, shall we close this

**Comment by robbyoconnor** [comment]
No, because it wasn't done.
