### ISSUE TITLE
A lot of javascript errors exist

### ISSUE THREAD

**Issue by robbyoconnor** [fossasia/gci16.fossasia.org#631]
If you look at the developers console, you will see a lot of javascript errors. 

This needs to be fixed.

**Comment by abishekvashok** [comment]
@robbyoconnor All of them are CORS errors and are caused from the flickr section of the website, we could provide a workout by adding some tweaks for the flickr section besides it's not working also

**Comment by Elgayar** [comment]
The only javascript errors in my developers' console are:
```
Uncaught TypeError: Cannot read property 'text' of undefined
    at parser (tweet.js:7)
    at parseFunc (tweet.js:4)
```

Is that right?

**Comment by Elgayar** [comment]
Apparently, they (errors) keep incrementing every time a new tweet from Lok Lak API tweets is previewed.

**Comment by abishekvashok** [comment]
Can you reset cache and retry

**Comment by idealadarsh** [comment]
As far I see it shows only this JS error "ReferenceError: IntersectionObserver is not defined   social-widgets-loader.js:1:1" on my console.

**Comment by robbyoconnor** [comment]
@adarsh-ideal ?!

**Comment by abishekvashok** [comment]
@robbyoconnor @adarsh-ideal I can't see any javascript errors:
![image](https://cloud.githubusercontent.com/assets/8947010/21580502/add621e4-d021-11e6-8bc6-022f0ac9a1ca.png)

I am only getting a 404 error

@adarsh-ideal The intersection observer was implemented well by @Witus13 and it works fine too, can you reset the cache and recheck

**Comment by myfrom** [comment]
@adarsh-ideal What browser are you on?

**Comment by robbyoconnor** [comment]
Yeah -- It's worth noting I use Google Chrome Beta.

**Comment by myfrom** [comment]
It's strange I tested it on Chrome Beta. Can you please provide me some details like system, browser version number, I'll test it on Sauce Labs

**Comment by robbyoconnor** [comment]
Weird -- seems to be fixed..

**Comment by abishekvashok** [comment]
Yep! @robbyoconner can we close this and open when newer ones pop up

**Comment by Elgayar** [comment]
Yes, I see we should close this because currently, I am not seeing any JavaScript errors either.
