### ISSUE TITLE
Improve the UX of the site

### ISSUE THREAD

**Issue by robbyoconnor** [fossasia/gci16.fossasia.org#632]
The site loads painfully slow on my laptop. This is not good. We should fix this.

**Comment by m1guelpf** [comment]
@robbyoconnor Can you post more data (network section of google developers console, type of computer, speedtest of your network...)

**Comment by robbyoconnor** [comment]
Speedtest
![](http://www.speedtest.net/result/5898598263.png)

[My laptop](http://support.hp.com/us-en/document/c03383054) -- 16GB of RAM.  Running Linux Mint 18 w/ Cinnamon and I'm using Google Chrome Beta. 

Took ~53s to load the site...this shouldn't be...

**Comment by abishekvashok** [comment]
@robbyoconnor you got a nice system :)
@m1guelpf here are more accurate results from page insights:
![image](https://cloud.githubusercontent.com/assets/8947010/21384985/bf53ba36-c792-11e6-8549-949b4e624101.png)

i think we have an issue for this already...

**Comment by Elgayar** [comment]
The images are one big problem. We should consider having them compressed.

**Comment by abishekvashok** [comment]
Yes we could compress all the images but the students put in new images in and on i think i had made a script that uses an api from anish.it to optimize images let me make it available for this repo... But it could take some time so if anyone else is interested please go on as I will be off city for a couple of days so @Elgayar would you like to work

**Comment by abishekvashok** [comment]
We have an issue for it already, can we close this duplicate one then

**Comment by Elgayar** [comment]
This one is more concerned about compressing images.

**Comment by abishekvashok** [comment]
Since Shrinkray.io is implemented closing this ☺. Feel free to reopen when the site speed goes down! 👍
