### ISSUE TITLE
Automate integration of Coala patches

### ISSUE THREAD

**Issue by robbyoconnor** [fossasia/gci16.fossasia.org#633]
Currently -- we have coala pushing fixes to a [separate branch](https://github.com/fossasia/gci16.fossasia.org/tree/coala-fix). What would be REALLY cool, is if it created a pull request with the changes so we could merge them faster. 

There is a [script](https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/scripts/coala_patch.sh), this script is **NOT** run for pull requests. 

Your task: have it make a pull request!

**Comment by m1guelpf** [comment]
Maybe using the Github API?
If @Abhi2424shek  mails me an api token for coala-autofix-bot, I can try. I think cURL can do this.

**Comment by robbyoconnor** [comment]
THAT would need to be secure.

**Comment by m1guelpf** [comment]
@robbyoconnor I will set it as a secure value on TravisCI

**Comment by abishekvashok** [comment]
@m1guelpf be aware : Travis values are not available for PRs

**Comment by robbyoconnor** [comment]
that's fine...we don't run commit patches for PRs

**Comment by abishekvashok** [comment]
@robbyoconnor can't we push directly to the gh-pages branch sir! Any possiblities?

**Comment by m1guelpf** [comment]
@Abhi2424shek I meant running it after the push is executed.

**Comment by abishekvashok** [comment]
@m1guelpf you can't run with travis variables on forks

**Comment by m1guelpf** [comment]
@Abhi2424shek But we can run them on this repo. The coala-autofix also doesn't work on forks.

**Comment by robbyoconnor** [comment]
@Abhi2424shek, perhaps I wasn't clear: The git patches that are pushed by coala, are not even run if it's a PR. Put another way, we only care about what's committed directly to the repository.

**Comment by robbyoconnor** [comment]
@Abhi2424shek, also I would prefer it NOT be pushed directly -- and rather be suggested...as it would cause a mess...a pull request gives us more control. I like the way we're doing it now.

**Comment by abishekvashok** [comment]
@robbyoconnor so you want a PR to the gh-pages branch instead of a commit to the coala-autofix branch sir?

**Comment by m1guelpf** [comment]
@Abhi2424shek You push to the coala-fix branch and a PR is created (using github api).

**Comment by robbyoconnor** [comment]
@Abhi2424shek, **No**, it will still push to the `coala-fix` branch. After it does that, if it determines anything changed, it will then make a pull request against the `gh-pages` branch. 

A pull request requires it be pushed to a branch. Keep things the way they are. We could even use [curl](https://curl.haxx.se/docs/manpage.html) to issue the API call.

**Comment by m1guelpf** [comment]
This iis the Github api endpoint: https://developer.github.com/v3/pulls/#create-a-pull-request
May I work on it?

**Comment by abishekvashok** [comment]
@m1guelpf sure, it should be an easy one.

**Comment by robbyoconnor** [comment]
By all means -- do it in the shell script I created @m1guelpf...this way it's only run on commits and not pull requests.

**Comment by m1guelpf** [comment]
@robbyoconnor Ok, just made m1guelpf-patch-1 branch on this repo.

**Comment by robbyoconnor** [comment]
Alright, that's fine...make a PR against `gh-pages` when you're done and I'll review :-)

**Comment by robbyoconnor** [comment]
You MIGHT need to install curl -- I don't think they have it on the server...We really don't need anything fancy...

**Comment by robbyoconnor** [comment]
The other fix is that we need to use the email address for `coala-autofix-bot` -- I don't know what that is...either that or you need to add the email we're using to their account.

**Comment by robbyoconnor** [comment]
@m1guelpf, The other fix is that we need to use the email address for `coala-autofix-bot` -- I don't know what that is...either that or you need to add the email we're using to their account. We might as well do this as well.

**Comment by abishekvashok** [comment]
@robbyoconnor see slack
