### ISSUE TITLE
Improve the students projects section

### ISSUE THREAD

**Issue by nadunys** [fossasia/gci16.fossasia.org#644]
There is a issue in the names of the projects
![image](https://cloud.githubusercontent.com/assets/16904196/21445902/80b68f02-c8e5-11e6-8003-604bef716784.png)

**Comment by Princu7** [comment]
@yashNadun Are you willing to work on this issue?

**Comment by abishekvashok** [comment]
There was a patch provided hah it must have been broken!

**Comment by hemanthsavasere** [comment]
I want to work.

**Comment by codein-dwij** [comment]
Sure you can work!

**Comment by AlexTurning** [comment]
@codein-dwij can i solve this issue,Please

**Comment by Elgayar** [comment]
@AlexTurning Dude, you got taste, you love Alex Turner 💃 Tell me if you need any help while working on that!

**Comment by Elgayar** [comment]
I made a fix. Submitting a PR now.
