### ISSUE TITLE
Blog Section needs improvement!

### ISSUE THREAD

**Issue by codein-dwij** [fossasia/gci16.fossasia.org#646]
![screenshot_14](https://cloud.githubusercontent.com/assets/16368363/21452244/9bc6a1f6-c92b-11e6-826f-ea2c91e7c3ec.png)
In the above image you can see that the text for the blog is aligned to left which shouldn't be the case! It should be aligned to the centre ! I would love fixing this :) If anyone can do before me , please do that :)

**Comment by Elgayar** [comment]
I am fixing it right now.

**Comment by myfrom** [comment]
@Elgayar @codein-dwij When you fix it be sure to check it also in smaller viewport. There's a media query made to fit those cards on phone, wouldn't be good to break it

**Comment by Elgayar** [comment]
@Witus13 I'll keep an eye on that! Thanks!

**Comment by Elgayar** [comment]
Live Link: https://elgayar.github.io/gci16.fossasia.org/
