### ISSUE TITLE
Thankyou for contribution not displaying names correctly

### ISSUE THREAD

**Issue by codein-dwij** [fossasia/gci16.fossasia.org#647]
![screenshot_15](https://cloud.githubusercontent.com/assets/16368363/21452308/20c556f4-c92c-11e6-838c-9ae18619f267.png)
I don't know what that thing is! First the name should be appearing on the top and not below and second the thing should be placed in the Contributors box and not outside it!
If anyone wants to work on this please tell :)

**Comment by ankitrgadiya** [comment]
@codein-dwij  I can fix this.

**Comment by ankitrgadiya** [comment]
I can bring it on top easily but I think it will not look good inside the contribution wrappper.

**Comment by codein-dwij** [comment]
Ping @ankitrgadiya The issue is back again will you continue on his?

**Comment by ankitrgadiya** [comment]
codein-dwij I tried increasing the width but no good. I think it is javascript problem which is out of my scope. Maybe the creator can help us.

**Comment by codein-dwij** [comment]
You know who he was?

**Comment by abishekvashok** [comment]
Git blame may can come to our help but beware not to blame him
