### ISSUE TITLE
Students are requested add your geo co-ordinates

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/gci16.fossasia.org#658]
All GCI students are requested to add their geo co-ordinates to the site for being displayed in the map which the site employs. To get your location you may use the community's official geolocator website at https://fossasia.github.io/geolocation. Please do do so!

happy coding :)

**Comment by m1guelpf** [comment]
@Abhi2424shek Maybe the mentors should create a GCI task...
ping @fossasia/fossasia-gci

**Comment by abishekvashok** [comment]
@m1guelpf no they just need to update the task which states to add "yourselves" or it should be flagged as beginner!

**Comment by abishekvashok** [comment]
We got a nice bunch now for the rest the info is in the readme so that would be enough
