### ISSUE TITLE
Replace Percy with Gitmate

### ISSUE THREAD

**Issue by jayvdb** [fossasia/gci16.fossasia.org#660]
[percy](https://percy.io/) only allows 500 diffs per month, and the reports are not publicly accessible.  I get an error message when I try to see the errors it is blocking a PR for.
They have released their front-end as open source at https://github.com/percy , but the important engine in the backend is not open source.

[Gitmate](https://gitlab.com/gitmate) is a front end for [coala](https://github.com/coala), a part of FOSSASIA, the engine is open source, and all of the checkers used are open source.  If "percy" is better, then the appropriate response is to create GCI tasks to improve coala.  That is the open source way.

**Comment by jayvdb** [comment]
And the reports are not public.

**Comment by jayvdb** [comment]
I've written up a non-coding task to compare percy with coala ; its not published yet, but here is the link for anyone interested https://codein.withgoogle.com/tasks/5696099832561664/

**Comment by sils** [comment]
@jayvdb percy seems to be doing something else, visually diffing a website

**Comment by jayvdb** [comment]
@sils it is automatically rejecting PRs based on something.  See https://github.com/fossasia/gci16.fossasia.org/pull/655 , which links to https://percy.io/FOSSASIA/gci16.fossasia.org/builds/145748 , which ... is a "HTTP/1.1 200" response that says

> Forbidden
>
> You do not have access to this resource or the resource does not exist in Percy. Feel free to contact us if you believe you have reached this in error.
>
> An administrator can send you an invite to join this organization.

**Comment by m1guelpf** [comment]
@jayvdb Give an email address and I will add you to the Percy team.

**Comment by jayvdb** [comment]
It is on my profile.

**Comment by m1guelpf** [comment]
@jayvdb just sent you an invite, so I think this can be closed. Feel free to reopen it.
