### ISSUE TITLE
Issues section is not good at UI level

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/gci16.fossasia.org#662]
![image](https://cloud.githubusercontent.com/assets/8947010/21467860/6c041a42-ca21-11e6-997e-d66cb9a4d5ad.png)

See the comment link boxes floating all around, please try to fix them.
Further they float around and do unwanted overflows, see the image posted by @ankitrgadiya just down to this post.

**Comment by ankitrgadiya** [comment]
Also this 
![screenshot from 2016-12-26 21-46-25](https://cloud.githubusercontent.com/assets/18071765/21484202/ca59b90a-cbb4-11e6-9be5-d13dfdbead96.png)

**Comment by kaine119** [comment]
Buttons in the `.issues-category` div were not styled at all; they took the styling of the other buttons, explaining why they're so wide. Making them 90% wide should work

As for the comment label behaving strangely, I'll try to rework it with flexbox.
