### ISSUE TITLE
Improve footer section

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/gci16.fossasia.org#663]
![image](https://cloud.githubusercontent.com/assets/8947010/21467871/dc96f612-ca21-11e6-9d4a-37e0596042af.png)
Improve the UI, it doesnot look good right, you can easily provide a fix, so go for it.

**Comment by oanarosca** [comment]
Wow. Any ideas which commit caused this? I'll try reverting it to the previous design, the reddish one

**Comment by codein-dwij** [comment]
Fixed :)
