### ISSUE TITLE
[DISCUSSION] Should we run coala-ci vs coala? 

### ISSUE THREAD

**Issue by robbyoconnor** [fossasia/gci16.fossasia.org#666]
Coala CI will fail the build if it finds issues...HOWEVER we have it set up where it will make a Pull Request and auto-apply fixes -- currently not possible if we pass `--ci` to it...I think the sane middle-ground is as I have it right now...where it applies patches and makes a pull request. 

Opinions? Students, this is how you make us like you -- by participating in discussions like this!

**Comment by abishekvashok** [comment]
Coala non interactive is my go

**Comment by robbyoconnor** [comment]
There is a caveat here: we can't apply patches..I tested running coala twice(once to apply patches; once to fail the build if it couldn't apply some patches) -- it adds something like ~10 or so seconds to the build to run `coala --ci` -- which is neglible in my eyes.

**Comment by abishekvashok** [comment]
@robbyoconnor coala --ci is depreciated and will be removed in the future, we have to use coala --non-interactive instead!

**Comment by robbyoconnor** [comment]
I'm going to close this -- We're running coala twice -- but it actually doesn't take much more time to run...so it's not a huge deal...

**However still question remains:** Do we wanna be applying fixes in CI like we are? I think it's probably a nice thing...but I'm not married to it

**Comment by abishekvashok** [comment]
Yes we should auto apply patches it is a boon for beginners and can prevent fall outs...

I wanted to ask since there are duplicate PRs should we make it to PR or Commit

**Comment by robbyoconnor** [comment]
That's one option -- but I want more than two of us to okay this...

**Comment by m1guelpf** [comment]
@robbyoconnor @Abhi2424shek I'd say commit, but the problem here comes when working locally. If the student does not git pull and continues working, then he will not be able tu git push.

**Comment by abishekvashok** [comment]
@m1guelpf it's the same when we merge PRs

**Comment by m1guelpf** [comment]
@Abhi2424shek but we have conflicts between forks. They'd had problems in they master branch (i think)

**Comment by abishekvashok** [comment]
@m1guelpf its the same when me merge we github creates a commit for the changes in the merge with some additional things like updating the contributors list and so on, when we commit it is directly commited

From github docs:

> You can merge pull requests by retaining all the commits in a feature branch, squashing all commits into a single commit, or by rebasing individual commits from the head branch onto the base branch.
When you click the default Merge pull request option on your pull request on GitHub, all your commits from the feature branch are added to the base branch in a merge commit.

Working:
![image](https://cloud.githubusercontent.com/assets/8947010/21477835/b7da7268-cb6b-11e6-8c8d-7cbb99a0ee0f.png)

Further:

> A commit is a discrete change to one or more files. It is a critical part of Git.
A pull request is a request to merge one or more commits into a different branch. It is not part of Git; it is only part of GitHub

**Comment by robbyoconnor** [comment]
I made the change quite honestly -- pull requests are always being merged...so I see this as a non-issue.

**Comment by abishekvashok** [comment]
@robbyoconnor there are duplicate PR's and commits are fast! Don't feel I am debating I am just expressing ;)

**Comment by robbyoconnor** [comment]
Also @m1guelpf in this case, we are committing directly to this repo. Conflicts will always happen. I already made the change to have it directly commit.

**Comment by robbyoconnor** [comment]
Closing.
