### ISSUE TITLE
Loklak Tweet Issue

### ISSUE THREAD

**Issue by ankitrgadiya** [fossasia/gci16.fossasia.org#679]
In Loklak API Tweet section, *Previous Tweet!* and *Next Tweet!* buttons not working.
![screenshot from 2016-12-25 19-32-56](https://cloud.githubusercontent.com/assets/18071765/21471428/12a0d194-cad9-11e6-937d-ac33b2808dc8.png)

**Comment by codein-dwij** [comment]
The next button works for me but not previous :/

**Comment by abishekvashok** [comment]
@ankitrgadiya @codein-dwij it's working! Please check.

**Comment by ankitrgadiya** [comment]
@Abhi2424shek Yeah its working now, but last night it was not working. 
We can close it.
