### ISSUE TITLE
Website is not responsive

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/gci16.fossasia.org#695]
![image](https://cloud.githubusercontent.com/assets/8947010/21478554/7ef8897e-cb72-11e6-87ff-022702364a1d.png)
 See there are scroll bars at the bottom section, so section is overflowing. Please fix it.

**Comment by ankitrgadiya** [comment]
@Abhi2424shek I think this is due to broken footer.
![screenshot from 2016-12-26 14-23-53](https://cloud.githubusercontent.com/assets/18071765/21478989/ff0c7b62-cb76-11e6-8186-db383ea7622b.png)

There's already a PR waiting to get merged. #694

**Comment by abishekvashok** [comment]
Still overflowing in small screen sizes @ankitrgadiya :
![image](https://cloud.githubusercontent.com/assets/8947010/21479596/a2a0f4d4-cb7b-11e6-8785-b7e04cfa38e9.png)

**Comment by Elgayar** [comment]
Came across this as well: 
![image](https://cloud.githubusercontent.com/assets/6567844/21484018/8f810830-cb94-11e6-83cd-b853c2e1c17b.png)

**Comment by abishekvashok** [comment]
The github octact logo is overflowing.

**Comment by ankitrgadiya** [comment]
@Abhi2424shek the site is pretty responsive now. We can close this one. There's a separate issue for octocat. #794

**Comment by Elgayar** [comment]
Actually the issue with the overflowment of the octocat is because of something else that is overflowing, as octocat just sticks to the very corner of whatever size the page is on. @ankitrgadiya
