### ISSUE TITLE
In the PDF Transcription project can we restrict the user access? Like if there are 10 files can we allot it like one user can see the first files next 5 can be seen by some other user not the first one..

### ISSUE THREAD

**Issue by anjalysuresh** [fossasia/gci16.fossasia.org#699]

**Comment by abishekvashok** [comment]
@anjalysuresh what are you mentioning of please explain

**Comment by abishekvashok** [comment]
@robbyoconnor can we close this we are not having any kind of PDF Transcription project

**Comment by robbyoconnor** [comment]
It's spam. I see this every year. Students don't put the effort in.

**Comment by anjalysuresh** [comment]
The doubt is about PDF TRanscription project In Pybossa.
