### ISSUE TITLE
Some photos are skewed

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/gci16.fossasia.org#706]
Some of the photos added to the site are stretched and look a little unnatural.
This can be fixed.

Hints: I think, making them square, max 240x240 could be enough.

**Comment by Elgayar** [comment]
#707 Solved here.

**Comment by niccokunzmann** [comment]
I just found some more:

- [x] Abhijeet Manohar 
- [x] Nikhil Chandak 
- [x] Vishal Singh 
- [x] Pranav Sharma

**Comment by oanarosca** [comment]
I'll resize them quickly just now.
