### ISSUE TITLE
Compressing images for better performance

### ISSUE THREAD

**Issue by Elgayar** [fossasia/gci16.fossasia.org#712]
The website is painfully slow as mentioned in issue #632 by @robbyoconnor 
I opened this issue in order to discuss methods of compressing images on the website (preferably lossless compression).

I came across that API: https://imageoptim.com/api/start
Can you guys please take a look and say your opinion about it and if I should try using it?

**Comment by abishekvashok** [comment]
I am ok with it, if the community is ok i would like to work on this, this is how I plan to go ahead:
We will check the image sizes and dimensions using the ImgChecker and if the size is large we will optimize it and if the dimensions are large and are in aspect ratio 1:1 we will resize it, thus we will have more automation. So what are your suggestions shall I proceed pls.

**Comment by robbyoconnor** [comment]
@Abhi2424shek -- just add the check -- keep the structure I have set  up

**Comment by robbyoconnor** [comment]
Fail it if it's not optimized...I'd rather not push changes like that. Give students pointers in how to opitmize the images themselves.

**Comment by hemanthsavasere** [comment]
Hi @robbyoconnor  and @Abhi2424shek 
I will do it.

**Comment by abishekvashok** [comment]
@robbyoconnor ok sir then we will not push changes back!

**Comment by ankitrgadiya** [comment]
@Abhi2424shek @robbyoconnor @Elgayar We can use [Shrinkray.io](https://shrinkray.io)

**Comment by abishekvashok** [comment]
@ankitrgadiya @robbyoconnor @Elgayar what should be the maximum image size shall we fix it as 1mb.

**Comment by ankitrgadiya** [comment]
@Abhi2424shek Are you talking about 1mb for all images or 1mb/picture?
If 1mb/picture that's a lot, we have tons of images site will weight a lot.
And if you're talking about 1mb for all images, we cannot fix the size as more students with more pictures are contributing, it will be very irritating to limit it.
This is my opinion guys.

**Comment by Elgayar** [comment]
The images are already maximum 200 KB, so you're giving more than double what they need.
If the average size of the images is 200KB for example, then we should limit all images by compression to 150 KB for example, even if that will reduce quality.. @ankitrgadiya @Abhi2424shek

**Comment by ankitrgadiya** [comment]
@Elgayar 150kb is alot. All pictures in Students and Mentors section should be no more than 20kb, which most of them already are. And about Blog section the images should not be more than 50kb. 
And I know we need to give priority to size but we have to keep in mind that extremely low quality images will not look good as well. Also I'd like to add that, as pictures were added by different students and later manipulated but a lot of people, so few images even though slightly larger in size are extremely low quality.

Check this one
![screenshot from 2017-01-01 11-23-57](https://cloud.githubusercontent.com/assets/18071765/21580415/55378a58-d019-11e6-962c-e29002d3c400.png)

First image in low quality compared to second one. But guess what first one is around 32kb and second one is just 14kb. We have to do things like this.

**Comment by abishekvashok** [comment]
@ankitrgadiya @Elgayar then we will fix the cap at 100 kb for student's mentor's and project's images and a 200 kb for blog images...
Is that ok @robbyoconnor 
We would make Travis to fail by exiting with value other than 0 and print out all those images are bigger than the size specified. If the size is ok I would just deliver a quick PR!

**Comment by abishekvashok** [comment]
Hey someone already did this using shrinkray.io and are pushing back... So can we close this then I think it's @gaeun who did it anyways good work.
