### ISSUE TITLE
Coala can't push to gh-pages

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/gci16.fossasia.org#721]
Coala cant now push to `gh-pages` because it's a protected branch and I think someone removed @coala-auto-bot from the collaborators. If it's no the issue please come up with a fix ;)

Here's the Travis log: [Credits @ankitrgadiya]
![image](https://cloud.githubusercontent.com/assets/8947010/21504435/fc77a85e-cc84-11e6-9879-eefc376a764d.png)

**Comment by abishekvashok** [comment]
@robbyoconnor can you take a look at this pls.

**Comment by robbyoconnor** [comment]
Fixed it. The issue was that only certain teams can push to the gh-pages branch. Added the bot to that list.
