### ISSUE TITLE
Mobile User Interface extra whitespace

### ISSUE THREAD

**Issue by Elgayar** [fossasia/gci16.fossasia.org#722]
I think someone merged something that caused this to happen, we should find a fix...

![image](https://cloud.githubusercontent.com/assets/6567844/21505556/0fd9187e-cc71-11e6-841a-969e4da5f6a3.png)

**Comment by ankitrgadiya** [comment]
This is already reported. #695

**Comment by hoangvanthien** [comment]
Close due to duplication.
