### ISSUE TITLE
Adding a "Go To Top" Option

### ISSUE THREAD

**Issue by Elgayar** [fossasia/gci16.fossasia.org#745]
How about if we add an icon that appears when the user starts scrolling, and when it is clicked, it scrolls them back to the beginning of the website at the top?
Anyone is welcome to start working on this issue!

**Comment by robbyoconnor** [comment]
Oh dear god no. Please -- let's not.

**Comment by hemanthsavasere** [comment]
Hi @Elgayar 
I am ready for working on this issue.

**Comment by Elgayar** [comment]
@robbyoconnor Why not?? I'll close it if it is not necessary..

**Comment by robbyoconnor** [comment]
I mean I don't care -- just don't like those "go to the top of the page" That's what my scrollbar is for.

**Comment by Elgayar** [comment]
Yeah, you have a point, however, we can try implementing it, and if we found that it is disturbing the website's appearance, usability or performance we can delete it... @robbyoconnor

**Comment by robbyoconnor** [comment]
I don't have a personal stake either way...

**Comment by ankitrgadiya** [comment]
@Elgayar No Offence but website is already loading very slow, adding more javascript will surely not help.

**Comment by Elgayar** [comment]
@ankitrgadiya No problem, it was only a suggestion. And yeah you got a point :D The website doesn't need to be more slow.
