### ISSUE TITLE
Unequal Padding

### ISSUE THREAD

**Issue by ankitrgadiya** [fossasia/gci16.fossasia.org#758]
Blog Section, Design V1 Section and Design V2 section are not having equal horiziontal padding.
![screenshot from 2016-12-31 13-58-23](https://cloud.githubusercontent.com/assets/18071765/21576749/363e6562-cf61-11e6-9c52-b06451b17e63.png)
![screenshot from 2016-12-31 13-58-46](https://cloud.githubusercontent.com/assets/18071765/21576751/43bb2f04-cf61-11e6-9a5a-63b02d8956c7.png)

**Comment by ankitrgadiya** [comment]
I'll try to fix it.

**Comment by codein-dwij** [comment]
Go ahead... :)

**Comment by ankitrgadiya** [comment]
@codein-dwij Fixed! #760

**Comment by ankitrgadiya** [comment]
We can close this one now.

**Comment by Elgayar** [comment]
Great!
