### ISSUE TITLE
Fix Student Name overflow and add a message on hover "Click for more info" for pop up windows

### ISSUE THREAD

**Issue by codein-dwij** [fossasia/gci16.fossasia.org#777]
- [ ] First of all in the students section the overflow of name has come again! see pic below
![screenshot_5](https://cloud.githubusercontent.com/assets/16368363/21581392/d1dbc0dc-d056-11e6-8f7f-5ae85258fb7f.png)

- [ ] Now I think this part needs some improvement! Now we have a pop up window for students and mentors but our visitors will have no idea about this feature so we can fix it in this way :-
![screenshot_6](https://cloud.githubusercontent.com/assets/16368363/21581429/de19500c-d057-11e6-92d8-a93146996376.png)
Now instead of the links we will add the text for clicking there for pop up window .. This part is not needed as links are here -
![screenshot_7](https://cloud.githubusercontent.com/assets/16368363/21581436/06da7034-d058-11e6-884d-f6e76d659f9a.png)

Feel Free to work on this :)

**Comment by abishekvashok** [comment]
Why don't on hover display click for more info!

**Comment by codein-dwij** [comment]
Display on Hover but remove the links from hover... its already on pop up window

**Comment by abishekvashok** [comment]
Yep then add some check boxes about the procedure to the issue body and add this as well improve the pop-up to be like material design quantum paper.

**Comment by abishekvashok** [comment]
And @codein-dwij can you rename the title of the issue

**Comment by abishekvashok** [comment]
Lastly do you want to work at it @codein-dwij

**Comment by Elgayar** [comment]
Is anyone currently working on it?

**Comment by gaeun** [comment]
I can work on this if no one wants to.

**Comment by codein-dwij** [comment]
Gaeun work on this!
