### ISSUE TITLE
Automatically display live link

### ISSUE THREAD

**Issue by gaeun** [fossasia/gci16.fossasia.org#791]
Since a lot of people forget to post live preview links or don't know what they are, I was thinking it would be helpful to create a bot that automatically comments live links on new PRs. I noticed that newbies in particular get lost when it comes to providing previews, and some of them close their PRs when requested to give a live link.
I wrote a simple Python app that does this: https://github.com/gaeun/LiveLinkWebhook
Let me know what you think about hooking this up to the gci16 repo. I think it would be time-saving, since we wouldn't have to ask for live previews and wait for people to post them.

To provide a preview (oh the irony), here's a screenshot of what it looks like:
<img width="790" alt="screen shot 2017-01-02 at 10 37 53 pm" src="https://cloud.githubusercontent.com/assets/13972732/21591095/7cdb0be4-d144-11e6-8314-e4801f68d007.png">

**Comment by abishekvashok** [comment]
Can't we have it generated with danger as a part of the PR template, but I feel this is good.

**Comment by abishekvashok** [comment]
Can we have branch checks too @gaeun and display only when pushed from the gh-pages or the master branch as these branches only have the deployment status available?

**Comment by gaeun** [comment]
@Abhi2424shek Yeah, I can add that. As for danger, it's possible, but I found some convenient Python frameworks

**Comment by Elgayar** [comment]
@gaeun The thing is, not everyone has the gci16.fossasia.org pushed to their origin directly, some have different branches. So that's something the user has to supply by themselves when they issue a pull request.

**Comment by gaeun** [comment]
@Elgayar In the majority of cases, people's live links are http://username.github.io/gci16.fossasia.org/. I've seen a couple of PRs that use independent github pages, but in those cases, they could supply their own preview links and we can ignore the bot.

**Comment by ankitrgadiya** [comment]
@gaeun @Elgayar I agree with Elgayar, also I want to add that some people are using custom domains and personally I create PR using different branches. Also I've seen some students, using \<username\>.github.io for gci site.(as they just learnt about gh-pages for the so). but still for majority it holds true. Lets wait for few more reviews.

**Comment by Elgayar** [comment]
Yeah, @ankitrgadiya that's exactly what I mean. 
We'll wait 💃

**Comment by gaeun** [comment]
@ankitrgadiya That's a good point, but the bot only comments when the changes are pushed from gh-pages (added the condition after @Abhi2424shek suggested it). I've only seen one or two people use custom domains tbh...
@robbyoconnor Opinions from mentors?

**Comment by robbyoconnor** [comment]
I think students should provide it still. It's good practice in complying with the rules of an FOSS project.

**Comment by robbyoconnor** [comment]
I'm going to add this to danger -- UNLESS they provide it...so we're not removing it...but we're also not warning.

**Comment by robbyoconnor** [comment]
Added to danger in ba2b059fa4c3b8cef3dae154ccbdaccc954ce4a9

**Comment by robbyoconnor** [comment]
https://github.com/fossasia/gci16.fossasia.org/pull/800 for what it looks like
