### ISSUE TITLE
Cards in mentors, students and contributors section aren't centered

### ISSUE THREAD

**Issue by myfrom** [fossasia/gci16.fossasia.org#792]
They're slightly moved to the left.
![mentors students contributors to left](https://cloud.githubusercontent.com/assets/19410489/21593545/8fc497c4-d118-11e6-8f5b-2c58cf123388.png)

**Comment by abishekvashok** [comment]
@Witus13 would you like to work at it?

**Comment by myfrom** [comment]
@Abhi2424shek ok, I will

**Comment by abishekvashok** [comment]
You are assigned go for it
