### ISSUE TITLE
Octocat icon covering menu

### ISSUE THREAD

**Issue by myfrom** [fossasia/gci16.fossasia.org#794]
Octocat icon is displayed on menu icon in small viewports making menu button hard to click if not impossible.
![octocat icon menu](https://cloud.githubusercontent.com/assets/19410489/21593569/d5cd0134-d118-11e6-8b38-e85978eb8cbd.png)

**Comment by Elgayar** [comment]
What do you think could be a solution? Remove the octocat when screen is small? I can't think of something to work on.. @gaeun @ankitrgadiya @Abhi2424shek @oanarosca 
What are your thoughts on this?

**Comment by myfrom** [comment]
Maybe show it on corner of slideshow. Or maybe give it its own place in the menu instead of showing octocat on mobile

**Comment by Elgayar** [comment]
We need it to appear all the time, it should be fixed to the top. Maybe we can add some Javascript, and make it appear when the page is scrolled?

**Comment by myfrom** [comment]
Maybe show it as a second button next to the menu button

**Comment by abishekvashok** [comment]
@Witus13 shwoing as a button would be awesome but can we wait for some others as well...

**Comment by dannymout** [comment]
@gaeun @ankitrgadiya @Abhi2424shek @oanarosca Increase the padding or margin on the right of the button on smaller devices.
