### ISSUE TITLE
Students/Mentors info popup bug on mobile

### ISSUE THREAD

**Issue by myfrom** [fossasia/gci16.fossasia.org#795]
Popup is not displaying correctly in small viewport
![info not displaying correctly](https://cloud.githubusercontent.com/assets/19410489/21593577/fd15ad18-d118-11e6-91ca-f97e67f3bdfa.png)

**Comment by robbyoconnor** [comment]
THis is not fixed yet @gaeun -- handle the mentors section and when you can...
