### ISSUE TITLE
Make contributors section more compact and change to 8 contributors in one row

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci16.fossasia.org#806]
Some sections of the site are relatively large already.

Please help to make the site more compact:
* Reduce the size of "Contributors"
* Change from 4 to 8 contributors in a row

**Comment by Elgayar** [comment]
I can do that!

**Comment by Elgayar** [comment]
However making 8 contributors in a row will be hard because 12 does not divide by 8, this will require modifying the grid system to use 16 columns per row. Maybe I can do it with 6 only per row?

**Comment by oanarosca** [comment]
@Elgayar you can create 2 `col-6` divs on one row, and in each of those add one row and four `col-3` divs. It may not be very clear, but I think that's the way to solve this. Let me know if you need any help :blush:

**Comment by Elgayar** [comment]
I think that could be done, right. However, I think that some problems might occur in the responsiveness of the website. We'll try and see.
@oanarosca Thank you very much

**Comment by Elgayar** [comment]
`var getContributors = function(page) {
  // Fetching contributors list
  $.ajax({
    url: "https://api.github.com/repos/fossasia/gci16.fossasia.org/contributors?page="+page
  }).done(function(data) {
    if (data.length === 0) {
      // Fetching is done, now display name in Thanks section
      thank();
      return;
    }
    var x = 0;
    data.forEach(function(contributors) {
      contributorsList.push(contributors.login);
      // Ignore LineLengthBear
      var html = "<div class='col-xs-12 col-sm-6 col-md-4 col-lg-3'><div class='card'>";
      html += "<div class='avatar'>";
      html += "<img src=" + contributors.avatar_url + "><div class='contribs'><p>";
      html += contributors.contributions;
      if (contributors.contributions === 1) {
        html += " contribution";
      } else {
        html += " contributions";
      }
      html += "</p><a href=" + contributors.html_url + " class='contributor-gh'><i class='fa fa-github fa-2x' aria-hidden='true'></i></a></div>";
      html += "<span>";
      html += contributors.login + "</span></div></div></div>";
      x++;
      if(x%4 == 0){
        html += "</div><div class='col-lg-6'>"
        $("#contributors-list").append(html);
      }
      else{
        $("#contributors-list").append(html);
      }
    });
    getContributors(page+1);
  });
};`

Can someone please tell me what's missing, because it's not working, and what's happening is that the col-lg-6 self closes, I don't know why..

**Comment by Elgayar** [comment]
![image](https://cloud.githubusercontent.com/assets/6567844/21657928/24a5d9ba-d2cd-11e6-9c02-786bdd15fa43.png)

Can someone tell me what's wrong here, because it's not working, what seems to be happening is the col-lg-6 is self closing by itself.
https://elgayar.github.io/gci16.fossasia.org/

**Comment by Elgayar** [comment]
If it doesn't self close, everything will work perfect. But why does it do that?

**Comment by Elgayar** [comment]
Any ideas?

**Comment by abishekvashok** [comment]
@Elgayar updates pls, want some help?

**Comment by Elgayar** [comment]
Yes, I asked if someone has a comment on my code in the screenshot

**Comment by mariobehling** [comment]
Hey, if it is easier please simply use 6 in a row. The idea is to make it more compact. Thank you!

**Comment by Elgayar** [comment]
Yess, it is easier to make it 6 in a row! I will do it now.

**Comment by Elgayar** [comment]
Solved!
