### ISSUE TITLE
Propose and implement ways to reduce size of website and increase loading speed

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci16.fossasia.org#807]
The website has grown largely. This results in slow loading. Please propose ways to reduce the size and load times of the site.

**Comment by abishekvashok** [comment]
@mariobehling, We are having the images optimized every week, so images are fine, what we can look for is to reduce JavaScript and introdice the concept of DRY code I.e, Don't repeat yourself and remove the unwanted code if any, further sir, i would like to emphasise the need to use css vicely, although it's worked out nice, there are portions which are repeating themselves, we could make some sections load on scrolled position too but that requires JavaScript!

**Comment by abishekvashok** [comment]
Reducing the use of Dom elements is another way.

**Comment by myfrom** [comment]
Are JavaScripts loaded with `async` attribute? If not it could speed up the page. Also how about moving some CSS that is not necessary at start to `body` so it won't block render.

**Comment by abishekvashok** [comment]
But @Witus13 some putting the needy ones aayi would make some other ones fail as asynchronous doesn't have an oder to load them, loading JavaScript in asynchronous mode would give us a bit of speed by but many errors would occur instead we should reduce js with the concept of DRY code.

**Comment by myfrom** [comment]
I'm not sure if I understood you but maybe we could fix those errors by
doing something like event listeners, eg. If function depends on other
script let's make this script fire an event when loaded and then the first
function can listen for this event and execute after receiving it.

**Comment by abishekvashok** [comment]
Lisentors are already over the limit
