### ISSUE TITLE
Making projects drop down menu automatic when hovered 

### ISSUE THREAD

**Issue by gautamjajoo** [fossasia/gci16.fossasia.org#832]
So, let us add a new feature of making the drop down menu of the PROJECTS tab automatic when hovered on it. Please confirm.. @DishantK1807 @robbyoconnor

**Comment by Elgayar** [comment]
I can do this.

**Comment by gautamjajoo** [comment]
Even I can do this but I had to confirm from the mentors

**Comment by robbyoconnor** [comment]
Yay more javascript to make the site slow?

**Comment by Elgayar** [comment]
@robbyoconnor Actually, I did that without JavaScript 😂

**Comment by robbyoconnor** [comment]
Nevermind then -- it's all good -- nice work!

**Comment by codein-dwij** [comment]
Since its done closing this...
