### ISSUE TITLE
Making pointing Cursor when clicked on "Show more Information" on any photo

### ISSUE THREAD

**Issue by gautamjajoo** [fossasia/gci16.fossasia.org#834]
So, let us change the cursor as a pointer when clicked on "Show more Information" on any photo of the website.. this needs one line code which has to be changed in css file that is cursor:pointer; .. Mentors please confirm @DishantK1807  @robbyoconnor ..

**Comment by Elgayar** [comment]
IMHO, I think this is unnecessary and won't make a difference on the website.

**Comment by myfrom** [comment]
I think it's a good idea and one line of CSS won't slow down the page load.
It would nicely indicate that clicking on card triggers an action, now it's not so clear if you have to click on card, "Click for more info" text or where.

**Comment by Elgayar** [comment]
Go ahead and do it then! @gautamjajoo

**Comment by gautamjajoo** [comment]
@Elgayar I am not able to do it.. please help me out

**Comment by abishekvashok** [comment]
You just need to customize the .avatar to contain the `cursor:pointer` css markup!

**Comment by myfrom** [comment]
Maybe whole .card, not only .avatar ?

**Comment by abishekvashok** [comment]
I don't know whether it is basically a card or avatar at head but try to look while in developer mode.

**Comment by Elgayar** [comment]
Read this: https://developer.mozilla.org/en/docs/Web/CSS/cursor @gautamjajoo

**Comment by gautamjajoo** [comment]
This I know.. My question is in whichfile should i change.

**Comment by myfrom** [comment]
stylesheets/main.css

**Comment by ankitrgadiya** [comment]
@gautamjajoo Updates??

**Comment by smsunarto** [comment]
I'll take this on since there's no update coming from op
