### ISSUE TITLE
Add installation instructions in readme

### ISSUE THREAD

**Issue by ananyo2012** [fossasia/gci16.fossasia.org#837]
It would be very helpful for first timers to setup a local instance of the website if instructions for installation is provided, specially who are completely new to open source and not acquainted with jekyll.

**Comment by robbyoconnor** [comment]
@ananyo2012 the task has instructions. Students never read those. I don't think this is entirely necessary. We link to https://pages.github.com -- which has installation instructions for jekyll.

**Comment by robbyoconnor** [comment]
The README has a lot of information.

**Comment by ananyo2012** [comment]
@robbyoconnor Well students tend to overlook the task instructions. If the installation instructions are included in the readme itself it will be easier for them to catch. We can perhaps create wiki pages for this and link them in readme. That won't make the README long. And also it would help in further contribution even after GCI.

**Comment by ankitrgadiya** [comment]
@ananyo2012 I'd like to write Wiki pages but I'm currently not able to. Permission issues probably.

**Comment by ananyo2012** [comment]
I think wiki pages are disabled as of now. @robbyoconnor If this seems valid can you enable them?

**Comment by jigyasa-grover** [comment]
Enabled Wiki.

**Comment by ananyo2012** [comment]
@jig08 I don't have the permissions for this repo. So I can't access the wiki. Strangely the wiki page should show up still. I think this may be since there is no wiki page yet. If you give the permissions I will be happy to work on this.

**Comment by m1guelpf** [comment]
@ananyo2012 Created the wiki. Try now!

**Comment by ananyo2012** [comment]
Need the permission to edit wiki too.

**Comment by robbyoconnor** [comment]
@ananyo2012 added you as a collaborator -- you should be able to do it now

**Comment by ananyo2012** [comment]
@robbyoconnor Added the installation instructions at https://github.com/fossasia/gci16.fossasia.org/wiki/Installation. I have used RVM for Ruby installation because that's perhaps the best way to manage Ruby as I know. Do you suggest any changes in the Instructions before I add the link in readme?

**Comment by robbyoconnor** [comment]
This assumes people are on Linux, if they are not...this doesn't work.

**Comment by robbyoconnor** [comment]
Fixed it.

**Comment by ananyo2012** [comment]
The same works on Mac OSX but I am not acquainted with Windows. Looking for a possible solution for Windows.

**Comment by robbyoconnor** [comment]
@ananyo2012 Neither am I. What you could have done is exactly what I did, :link: to [jekyll's installation guide](https://jekyllrb.com/docs/windows/).

**Comment by ananyo2012** [comment]
Perhaps we should add a line in readme so that people can follow the installation instructions.

**Comment by robbyoconnor** [comment]
One problem: nobody _READS_ the README...

**Comment by ananyo2012** [comment]
@robbyoconnor Yes. But its good to make an effort to make things easier. Done in #910
