### ISSUE TITLE
Clicking on students icon on mobile doesn't fire the popup

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/gci16.fossasia.org#845]
The pop-up is not working in the mobile on clicking the students and the mentors section, it just displayed click for more info and when on clicking does nothing!

**Comment by codein-dwij** [comment]
Working for me! ITS a problem just for you I guess

**Comment by abishekvashok** [comment]
Btw i am running chrome latest on mui latest, and I still can't get it right?

**Comment by codein-dwij** [comment]
I am using android in built browser

**Comment by abishekvashok** [comment]
That must be chrome but really i am facing this issue

**Comment by myfrom** [comment]
Maybe you could run [Chrome Remote Debugging](https://developers.google.com/web/tools/chrome-devtools/remote-debugging/) to find the problem

**Comment by abishekvashok** [comment]
Here's a shot
![screenshot_2017-01-08-18-09-44-872_com android chrome](https://cloud.githubusercontent.com/assets/8947010/21749850/be90438c-d5cd-11e6-929c-d0472ecdfdb4.png)

**Comment by ankitrgadiya** [comment]
@Abhi2424shek Its working for me now. Can anybody confirm it.

**Comment by myfrom** [comment]
Working for me as well

**Comment by abishekvashok** [comment]
It's working
