### ISSUE TITLE
Avoid use of nested for loops

### ISSUE THREAD

**Issue by ananyo2012** [fossasia/gci16.fossasia.org#874]
The entire point of [these lines of code](https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/index.html#L726-L769) is putting a map marker right? Use of nested for loops aren't required. It takes more execution time. Addresses #807

**Comment by abishekvashok** [comment]
Yes you are correct we could just do both within one loop

**Comment by Elgayar** [comment]
There have to be two loops because one will be looping inside the mentors'
file and the other in the students'. However, I think making separate loops
won't be a problem.

**Comment by ananyo2012** [comment]
Yes. Just take care the marker text is different for mentor and students. Find a way to implement that

**Comment by Elgayar** [comment]
I can work on that.

**Comment by ananyo2012** [comment]
@Elgayar Yes either implement two single loops or just use one thinking some way to separate marker text.

**Comment by abishekvashok** [comment]
@Elgayar any updates.
