### ISSUE TITLE
Broken image link for Louis Gagnon in mentors section

### ISSUE THREAD

**Issue by jigyasa-grover** [fossasia/gci16.fossasia.org#91]
There is a broken image link for `Louis Gagnon` in the mentors section of http://gci16.fossasia.org/.

<img width="1280" alt="screen shot 2016-12-02 at 4 06 09 pm" src="https://cloud.githubusercontent.com/assets/9291400/20831102/8fd1665c-b8a9-11e6-99f6-e5b3be6822e0.png">

**Comment by louisgag** [comment]
Hi, it worked when I first upload my image file. Not sure what happened or whether someone move it; anyhow, I reuploaded it to the mentors folder but the issue remains...

**Comment by louisgag** [comment]
Well, looks like its fixed now...

**Comment by jigyasa-grover** [comment]
Yes, fixed.

Thanks !

<img width="1280" alt="screen shot 2016-12-02 at 4 29 32 pm" src="https://cloud.githubusercontent.com/assets/9291400/20831743/854beede-b8ac-11e6-9d50-6a7e58ee9d6c.png">
