### ISSUE TITLE
Security / Ads issue: Do not load content from onclkds.com

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci16.fossasia.org#918]
On the live site an iframe is loaded from an advertising site: onclkds.com

Please find the service adding this data and delete it. I got this one for example: 
src="//onclkds.com/fac.php?geo=DE&zoneid=936512&aid=1&rtg=0"

**Comment by jayvdb** [comment]
Note https://github.com/fossasia/gci16.fossasia.org/issues/614 was the previous issue about a similar (or the same) problem.
