### ISSUE TITLE
Delete Flickrembed service and possible substitute by official flickr service

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci16.fossasia.org#919]
Flickrembed is an inofficial service, that is not associated with flickr. We do not know who is running this service and should avoid using it.

Please take out this service.

Optional: Substitute it with an official Flickr widget.

**Comment by jayvdb** [comment]
https://flickrembed.com/privacy-policy.php does mention ads by Google.
But #918 mentions onclkds.com , which isnt Google.
So either flickrembed.com is not telling the whole truth, or #918 isnt fixed yet.

But either way, this fix was necessary and can be closed. Nice work @oanarosca

**Comment by jayvdb** [comment]
Note that the flickrembed comes from https://github.com/fossasia/gci16.fossasia.org/pull/173 , and @witus13 noted this was the source of ads at https://github.com/fossasia/gci16.fossasia.org/issues/614#issuecomment-268332387
