### ISSUE TITLE
Let's give attribution to all contributors

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci16.fossasia.org#920]
Some students might have contributed their first time to an Open Source project and it would probably be great for them to be listed on the website. As the contest is getting to the end, let's include everyone in the list of contributors, not just people who made more than 4 contributions.

**Comment by oanarosca** [comment]
I know this has been an issue for some time, but now it seems that all contributors appear in the section (maybe after changes in the Github API?). So closing this.
