### ISSUE TITLE
Add a copy of blog articles to site in repository

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci16.fossasia.org#922]
In the blog section, we see a lot of interesting blog articles. The nature of the Internet is: That things and links change. Therefore it would be nice to keep a copy of the articles/pages on the actual FOSSASIA GCI site.

* [ ] Please download the article/page and save it in a folder on the site
* [ ] Also add a link in each blog square to the "Local Version"

**Comment by ankitrgadiya** [comment]
@mariobehling Even better we can use this https://archive.org/web/ 
It is reliable.

**Comment by mariobehling** [comment]
@ankitrgadiya Yes, we know them, but it is not a hosting service and not always superfast. If you would like to take up this issue and add the content here into this repo, please go ahead.

**Comment by ankitrgadiya** [comment]
@mariobehling Do you want to just copy just the articles as in plain text?? As not all the students are using github pages to host. Some are using Wordpress, edublogs, blogspot, etc. So we will not be able to copy the actual pages.

**Comment by mariobehling** [comment]
Please save the full page including images etc. and store it on the site as a copy, each article in a separate folder. Cheers.

**Comment by ankitrgadiya** [comment]
I'll do this one.

**Comment by jayvdb** [comment]
Has this been done with previous years GCI?

**Comment by codein-dwij** [comment]
Are we doing this?

**Comment by jigyasa-grover** [comment]
Yes @codein-dwij , would you like to take this up ?

**Comment by abishekvashok** [comment]
I think @ankitrgadiya is on it can we have a reply from him?

**Comment by codein-dwij** [comment]
If you see , Ankit created the PR but @robbyoconnor isn't approving this. So we need to sort out whether we are doing this or not. Check PR #951

**Comment by abishekvashok** [comment]
@robbyoconnor whts your status then

**Comment by robbyoconnor** [comment]
I didn't see this issue...it makes sense...if somebody wants to do it -- go ahead.

**Comment by m1guelpf** [comment]
My vote goes for archive.org

**Comment by robbyoconnor** [comment]
I'm against throwing backups for the entire site in git... archive.org exists...Use that.

**Comment by robbyoconnor** [comment]
Which is why I rejected the PR.

**Comment by ankitrgadiya** [comment]
@robbyoconnor i suggested the same thing but @mariobehling didn't liked the idea. Check first comments.

**Comment by robbyoconnor** [comment]
@mariobehling why is using archive.org not sufficient? storing the blog articles makes the git repo larger...

**Comment by jayvdb** [comment]
There are many legal issues with creating backups of webpages, and there are additional ethical issues when creating backups of webpages created by minors.
IMO it is better to leave that to people who know what they are doing in that arena.

**Comment by robbyoconnor** [comment]
Doesn't archive.org create backups anyways? Do we want to do this? I think we should just run the risk that a site may go stale...I know many students likely only did it to complete the task...so it's a non-issue if it goes offline..

**Comment by jayvdb** [comment]
archive.org only keeps backups of webpages it finds, or is told about.
If it hasnt already found the webpage (unlikely for GCI), it needs to be told about the webpage (hence https://github.com/coala/coala-bears/issues/1322)

**Comment by robbyoconnor** [comment]
I guess...we should do the archive.org route...I REALLY dislike storing the articles... It's unnecessary.

**Comment by jayvdb** [comment]
I dislike creating custom hacks for one website.  Better to build generic tools that everyone can use.

**Comment by abishekvashok** [comment]
May we still need this, @mariobehling

**Comment by robbyoconnor** [comment]
I personally think this can be accomplished better via a coala bear...in a way that can be used for other apps. I am in agreement with @jayvdb 110%

**Comment by codein-dwij** [comment]
Any other option that can be done?

**Comment by robbyoconnor** [comment]
For now, not really.

**Comment by jayvdb** [comment]
fwiw, coala already has a bear which archives all URLs to archive.org ;-)
