### ISSUE TITLE
Enhance the footer section

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci16.fossasia.org#923]
The information on the footer can be enhance in a few ways:
* [x] Ensure the same margins on the right and left of the footer to the edge of the window
* [x] Expand the middle section similar to the standard FOSSASIA site
* [x] Move the absolute bottom footer (© Copyright 2009-2016 FOSSASIA | Made with  for Google Code-In) a bit more (increase the distance the the 3 column footer) 
* [x] Add a link to http://fossasia.org to "Copyright 2009-2016 FOSSASIA"
* [x] Add suitable icons instead of the link symbol to the right hand column for each list item

![screenshot from 2017-01-14 21-53-35](https://cloud.githubusercontent.com/assets/1583873/21958035/72c5f79a-daa4-11e6-9482-ed52535a88bc.png)

**Comment by ankitrgadiya** [comment]
I'll do this one

**Comment by mariobehling** [comment]
Please align heading and paragraph text below.
