### ISSUE TITLE
Add mentors to site

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci16.fossasia.org#925]
In GCI a lot of mentors contributed and worked with students directly on the GCI system, in Github or they organized local meetups. Please help to give attribution and find images and links to mentors. Please tick mentors that are already on the website and add missing ones.

* [x] 	André Rebentisch
* [x] 	Dishant Khanna
* [x] 	Agata Kowalska
* [ ] 	Terry Hill
* [ ] 	Olakunle Oladiran
* [x] 	Yathannsh Kulshrestha
* [ ] 	SoongChee Gi
* [x] 	Yiping Deng
* [ ] 	Lorenz
* [x] 	Arnav Gupta
* [x] 	Aditya Vyas
* [ ] 	Minal Patil
* [x] 	Aayush Arora
* [ ] 	srisankethu
* [ ] 	gichoya
* [x] 	Jigyasa Grover
* [x] 	Sopan Khosla
* [ ] 	sils
* [x] 	Ajinkya Wavare
* [x] 	Gnovi
* [x] 	Bill Acha
* [ ] 	Rahul Prabhukhanolkar
* [x] 	Hoang Phu Nguyen
* [ ] 	Andrea Zanoni
* [ ] 	Lisa
* [x] 	Shiven Mian
* [x] 	Nicco Kunzmann
* [x] 	ANANYA MAITI
* [ ] 	Venkata Chilkuri
* [x] 	Sudheesh Singanamalla
* [ ] 	Larry Ndumbe
* [ ] 	harley
* [ ] 	AbdealiJK
* [x] 	Rafał Kowalski
* [x] 	Hon Nguyen
* [x] 	Jason Wong
* [x] 	John Vandenberg
* [x] 	Michael Christen
* [ ] 	Jeff Warren
* [ ] 	Udayan Tandon
* [ ] 	Tony McCormick
* [x] 	Robby O'Connor
* [ ] 	astroiseur
* [x] 	the-dagger
* [ ] 	Niranjan Rajendran
* [x] 	SaptakS
* [x] 	Louis Gagnon
* [ ] 	Art Eaton
* [x] 	Hemant Jadon
* [x] 	princu7
* [x] 	Damini Satya
* [x] 	Shubham Padia
* [x] 	Pawan Pal
* [x] 	Mario Behling
* [x] 	Vu Hung Nguyen
* [x] 	Manan Wason
* [x] 	Sreeja Kamishetty
* [ ] 	Nguyễn Hồng Quân
* [x] 	Adrian-Gabriel Zatreanu
* [x] 	Harsh Vardhan
* [x] 	Hong Phuc Dang
* [x] 	aviaryan
* [ ] 	Tchuenkam Ulrich

**Comment by m1guelpf** [comment]
@mariobehling Are the checkboxes updated?

**Comment by jigyasa-grover** [comment]
@m1guelpf Could you pls cross-check from the website ?

**Comment by m1guelpf** [comment]
@jig08 I believe this can be closed...
