### ISSUE TITLE
Merge areas MBDYN design logos and V2 logos and add V2 info to overlay

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci16.fossasia.org#928]
There are two areas for the MBDYN designs. The second areas shows enhanced version of some students. 

* [x] Please merge the two areas and add "Version 2" to the overlay text to indicate that these are enhanced versions.
* [x] Take out MBDYN version 2 from the top menu bar as well

**Comment by oanarosca** [comment]
It seems that this has been done. So closing it.
