### ISSUE TITLE
Increase size of "Thank you" and make it into a separate section with a different colorful background

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci16.fossasia.org#930]
Let's make this more outstanding: Increase size of "Thank you" and make it into a separate section with a different colorful background.

![screenshot from 2017-01-14 22-27-16](https://cloud.githubusercontent.com/assets/1583873/21958200/c9660ae6-daa8-11e6-8032-07b256ff670f.png)

**Comment by Elgayar** [comment]
Solved!
