### ISSUE TITLE
Research and find more student projects to add them on the site

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci16.fossasia.org#931]
Many student projects have been done during the contest. Please research more student projects and add them to the site. You might search on twitter for students and their projects.

**Comment by abishekvashok** [comment]
We could fetch them from twitter using loklak @mariobehling

**Comment by mariobehling** [comment]
@Abhi2424shek This issue is more about the blog and student project sections. If you would like to do something with loklak please feel free to add another issue.

**Comment by abishekvashok** [comment]
I ment most of the tasks requires to be tweeted and hence we could get those projects from loklak, i was giving a hint!
