### ISSUE TITLE
Add a GCI logo with a colorful background to the menu bar

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci16.fossasia.org#938]
The info that this site is about GCI is not very clear on the site. Therefore add the logo with a nice colorful background to the top right of the menu bar.

![screenshot from 2017-01-15 01-13-10](https://cloud.githubusercontent.com/assets/1583873/21959208/6b75d96c-dac0-11e6-818f-2e359ba70551.png)

Why not take some inspiration from last years page?

![screenshot from 2017-01-15 01-18-26](https://cloud.githubusercontent.com/assets/1583873/21959212/8ea25622-dac0-11e6-978b-531e1149109d.png)

**Comment by abishekvashok** [comment]
This is done, not happy to see this is not closed still.
