### ISSUE TITLE
Add a video gallery of videos students made during the contest

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci16.fossasia.org#944]
There were a lot of wonderful videos that were made during the contest. Please add an Open Source video gallery where users can click on videos of students.

**Comment by hemanthsavasere** [comment]
I would like to work on this @mariobehling

**Comment by mariobehling** [comment]
You can also make a simple section with a large video and use this code:
```
          <iframe width="1280" height="720" src="https://www.youtube-nocookie.com/embed/videoseries?list=PLzZVLecTsGpK544UhC1_Gm4sl4eW3lTEq" frameborder="0" allowfullscreen></iframe>
```

**Comment by mariobehling** [comment]
Edited above code. Pasted wrong one first..

**Comment by oanarosca** [comment]
Any updates @hemanthsavasere?
