### ISSUE TITLE
Change the color of some sections on scroll over

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci16.fossasia.org#946]
It's a student site, so let's make it colorful!

Please implement a color change of the background color on scroll over of the follow secionts:
* mentor section
* student section
* contributors section

**Comment by mariobehling** [comment]
Contributors section and latest issue section does not work anymore after this PR. Please help to fix it. Thanks.

**Comment by Elgayar** [comment]
Actually, I can see them working just fine?
