### ISSUE TITLE
In the student section: "Show more information" on scroll over instead of clicking

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci16.fossasia.org#948]
At the moment users need to click to see more information in the student section. Please implement as follows instead:
* Show more information on scroll over

![screenshot from 2017-01-15 02-33-35](https://cloud.githubusercontent.com/assets/1583873/21959565/44d348fc-dacb-11e6-863d-3dadc5dbccbf.png)

**Comment by Elgayar** [comment]
I think we had this implemented but removed it because it affected the responsiveness, especially that it won't work well on mobile devices.

**Comment by abishekvashok** [comment]
@mariobehling we had this earlier and changed to the pop-up, can we make the pop-up more beautiful or do as your instruction? It affected the responsiveness last time!

**Comment by mariobehling** [comment]
We have this kind of feature working well on the open event app speakers page. Mobile responsiveness is another question. Having to close each students expansion (which now opens on scroll over), is slowing users down. If I scroll down I also wonder, why I cannot click on other students -> because I have to close some student I opened elsewhere before I can do that.

Let's keep it simple: Open on scroll over and close on scroll out, please.

**Comment by abishekvashok** [comment]
K

**Comment by mariobehling** [comment]
This issue is not yet solved in a way that functions. As soon as the scroll over shows the additional information and a user tries to access the displayed links in the additional info box, the box disappears or "flickers". It is not possible to click the links in the box. Please help to make this work.
