### ISSUE TITLE
Add a cool effect to each heading and propose and implement a more interesting font

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci16.fossasia.org#954]
Let's add some spice to the headings of sections. Please:

* [ ] add a cool effect to the headings (ensure it is an open source effect)
* [ ] propose and implement a more interesting font, e.g. a Google font

![screenshot from 2017-01-15 10-03-13](https://cloud.githubusercontent.com/assets/1583873/21961448/2e42a9cc-db0a-11e6-923b-ba7cb6c40ac8.png)

**Comment by abishekvashok** [comment]
We could use free style font, which is a bit classic your opinions.

**Comment by Elgayar** [comment]
I'll work on this.
