### ISSUE TITLE
Reduce the space between rows in blog section

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci16.fossasia.org#955]
The blog section has a rather large space between rows. Please reduce the space to the same space between columns.

![screenshot from 2017-01-15 10-18-16](https://cloud.githubusercontent.com/assets/1583873/21961527/133a8e2c-db0c-11e6-9068-d51cb12e2e36.png)

**Comment by Elgayar** [comment]
This issue has been solved.
![image](https://cloud.githubusercontent.com/assets/6567844/22047576/93dad73c-dd30-11e6-817e-9e01c4dfbccf.png)
