### ISSUE TITLE
Implement "More Student Info" closes and scroll "out"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci16.fossasia.org#958]
The more info only closes when the user clicks "Close" on the bottom right of the area. Please implement that the area closes when the user scrolls out of the area.

![screenshot from 2017-01-15 10-34-00](https://cloud.githubusercontent.com/assets/1583873/21961609/60adec1a-db0e-11e6-97c4-97e657cab95b.png)

**Comment by abishekvashok** [comment]
Solved
