### ISSUE TITLE
Fickr slider in the social media section not responsive

### ISSUE THREAD

**Issue by Elgayar** [fossasia/gci16.fossasia.org#961]
The flickr slider is causing an overflowment when the website is accessed from a mobile device.

**Comment by Elgayar** [comment]
![screenshot_2017-01-15-13-18-04](https://cloud.githubusercontent.com/assets/6567844/21962100/a2a122f6-db25-11e6-89c0-b5efcf68ab56.png)

**Comment by mariobehling** [comment]
Please take this issue into account here: https://github.com/fossasia/gci16.fossasia.org/issues/924
