### ISSUE TITLE
Hovering over students to show more information popup flickers

### ISSUE THREAD

**Issue by robbyoconnor** [fossasia/gci16.fossasia.org#971]
The hovering over students to show more information flickers like crazy. 

To reproduce: 

- Hover over the 2nd student...or any student in a row other than the first row...you'll see it.

**Comment by mittalprince** [comment]
Sir i want to work on this issue .
But would you please elaborate the issue first

**Comment by mittalprince** [comment]
Means on hover popup window flicker, what you want to do

**Comment by robbyoconnor** [comment]
This is no longer an issue.

**Comment by mittalprince** [comment]
k sir 
thanks
