### ISSUE TITLE
Why don't we make use of the official github folder for templates

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/gci16.fossasia.org#972]
We are currently using danger for PR template there is an official github solution to it, it further supports an issue template and can be used and is user-friendly as it appears on the PR and the issue text boxes.

**Comment by abishekvashok** [comment]
We could also think to issue the PR template by danger if the template has been deleted manually!

**Comment by m1guelpf** [comment]
@Abhi2424shek What official Github solution?

**Comment by abishekvashok** [comment]
Having the .github folder and making the ISSUE_TEMPLATE.md and PULL_REQUEST_TEMPLATE.md files contain in it.

**Comment by abishekvashok** [comment]
If we specify it there, it will appear on new issues and new pr text boxes which the users would need to fill up @m1guelpf

**Comment by m1guelpf** [comment]
@Abhi2424shek We already have a Github pull request template, but it isn't needed to put it in the .github folder...

**Comment by abishekvashok** [comment]
It is implemented by danger and doesn't appear on the text area where we write the description for the PR putting it as described above would make it appear :)

**Comment by robbyoconnor** [comment]
@Abhi2424shek we're not using danger for that. I do use it for the PR template, but my reason for not using is that students already don't read it...I wanted it prominently. PR template can go there because people don't have to read it...You can very easily put it in the `.github` directory...

**Comment by robbyoconnor** [comment]
THis is the `.github` folder: https://github.com/fossasia/gci16.fossasia.org/tree/gh-pages/.github

**Comment by abishekvashok** [comment]
Can we have the issue template as well? @robbyoconnor

**Comment by robbyoconnor** [comment]
Sure, write one.
