### ISSUE TITLE
Convert Bootstrap to MaterializeCSS framework

### ISSUE THREAD

**Issue by smsunarto** [fossasia/gci16.fossasia.org#975]
From what I see, the overall design is pretty much going towards a material design. 

So why not implement an actual material design css framework instead of using bootstrap?

[MaterializeCSS ](http://materializecss.com/about.html) is a pretty good example.

**Comment by m1guelpf** [comment]
@smsunarto I like to use flatty.css that provides a flat UI simply by replacing boostrap.min.css with flatty.min.css

**Comment by abishekvashok** [comment]
@smsunarto that would make our slider to go down, anyway if we can have more discussion in this, i would be happy.

**Comment by smsunarto** [comment]
@Abhi2424shek Currently. we don't use bootstrap's slider. We use something from http://imageslidermaker.com/. And to add on top of that, materializecss have it's own slider.

@m1guelpf that would be only one of those "Bootstrap theme".

**Comment by abishekvashok** [comment]
@smsunarto we are going to replace it, see issue #917 , we'd need more discussions maybe @robbyoconnor could say his opinion here.

**Comment by robbyoconnor** [comment]
I think replacing bootstrap is a fantastic idea. I never really liked it all that much...it's over-used.

**Comment by robbyoconnor** [comment]
MaterializeCSS is great -- but it's not the only show in town. There are others as well: 

[Google's Material Design Lite](https://getmdl.io/), [MUI](https://www.muicss.com/), and probably more.

**Comment by ankitrgadiya** [comment]
I like Material Design Lite, and I'll try to recreate the current site with mdl.

**Comment by abishekvashok** [comment]
@ankitrgadiya sure go on

**Comment by smsunarto** [comment]
@ankitrgadiya MDL are not built for responsiveness natively (unlike bootstrap) one thing to keep mind.

**Comment by ankitrgadiya** [comment]
@smsunarto It does have grid though. I guess it can handle, although I'll keep checking responsiveness. Thanks for mentioning.
