### ISSUE TITLE
Link to all past GCI sites

### ISSUE THREAD

**Issue by robbyoconnor** [fossasia/gci16.fossasia.org#979]
It would be super nice if we linked to all past GCI sites in a drop-down menu. 

*Bonus points if you show which site you're on in the dropdown! 

_*Bonus points are simply glory, fame, and your name in the commit history._

**Comment by Elgayar** [comment]
Isn't that already implemented?
![image](https://cloud.githubusercontent.com/assets/6567844/22407864/85fcf654-e677-11e6-952d-9eac5664b703.png)

**Comment by Elgayar** [comment]
#933

**Comment by robbyoconnor** [comment]
ooops
