### ISSUE TITLE
Overlap of the images/design in the contribution section.

### ISSUE THREAD

**Issue by harshit98** [fossasia/gci16.fossasia.org#980]
![selection_010](https://cloud.githubusercontent.com/assets/22245418/22626467/f4c63e5e-ebd3-11e6-831d-e86a9556b426.png)
On the screen-size of mobile 320px (using developer tools), the images/design in the contribution section seems to overlap each other.

**Comment by codein-dwij** [comment]
Would you like fixing it or you are too busy with your PR?

**Comment by harshit98** [comment]
@codein-dwij Busy with my PR. However, if you're interested to solve this issue go ahead. :)
