### ISSUE TITLE
Add an info section similar to the GCI website 2017 below the header

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci16.fossasia.org#991]
The info section should include:
* 700+ students
More than 350 successfully completed tasks in Google Code-In with FOSSASIA in 2016.

* 1500+ tasks
1549 tasks were completed this year, from solving issues, to building web apps, setting up applications and creating blog posts.

* 40 mentors
Mentors are developers, engineers, university students, professors, and generally contributors who love to share and be a part of our open source community. They help creating better software for a better and just world.

![screenshot from 2018-02-09 12-34-41](https://user-images.githubusercontent.com/1583873/36026383-0a311486-0d97-11e8-84f6-8326c4a11a73.png)

**Comment by yashLadha** [comment]
I am sending a patch for the same.

**Comment by abhi40308** [comment]
As this issue has been inactive from a quite long time. I would like to claim it @yashLadha

**Comment by yashLadha** [comment]
GFI @abhi40308 :+1:
